package ini

import (
	"strings"

	"consema.dev/consema/core"
	"consema.dev/consema/document"
	"consema.dev/consema/protocol"
)

// This file implements the canonical PortableValue materialization for
// explicit INI profiles (consema-ini materialization.rs; RFC 0009 §11).
// Materialization consumes a complete nested EntryMapping or a uniquely
// representable Object and creates a new Document; it is not a formatter
// for an existing source. The generated bytes are reparsed under the exact
// target profile and reprojected under the request's policy before
// success; output bytes, provenance, fidelity, report, and limits are
// atomic.

// MaterializationFidelity is the materialization fidelity classification.
type MaterializationFidelity string

// The two frozen fidelity levels.
const (
	// MaterializationFidelityExact means the target directly represents
	// the input semantics.
	MaterializationFidelityExact MaterializationFidelity = "Exact"
	// MaterializationFidelityTransformed means complete semantics survive
	// an explicit reversible re-encoding.
	MaterializationFidelityTransformed MaterializationFidelity = "Transformed"
)

// MaterializationFailureKind classifies a stable materialization failure
// (materialization.rs: the frozen failure classes).
type MaterializationFailureKind uint8

// The stable materialization failure classes.
const (
	// MaterializationUnsupportedProfile: the requested target profile is
	// unavailable.
	MaterializationUnsupportedProfile MaterializationFailureKind = iota
	// MaterializationUnsupportedStyle: the requested style is unavailable.
	MaterializationUnsupportedStyle
	// MaterializationUnsupportedEncoding: the target does not support the
	// requested encoding.
	MaterializationUnsupportedEncoding
	// MaterializationUnsupportedNewline: the target style does not support
	// the requested newline policy.
	MaterializationUnsupportedNewline
	// MaterializationUnrepresentable: the portable input cannot be
	// represented by the target profile.
	MaterializationUnrepresentable
	// MaterializationResourceLimit: a declared resource limit was reached.
	MaterializationResourceLimit
	// MaterializationFormationFailed: generated bytes did not form the
	// target profile.
	MaterializationFormationFailed
)

// MaterializationFailure is the typed materialization failure. It
// implements error and the RFC 0016 §6 Code() contract with the frozen
// registered codes.
type MaterializationFailure struct {
	// Kind identifies the failure.
	Kind MaterializationFailureKind
	// Path is the offending input value path of Unrepresentable failures.
	Path protocol.ValuePath
	// KindName is the offending PortableValue kind name of Unrepresentable
	// failures.
	KindName string
	// LimitName is the stable limit name of ResourceLimit failures.
	LimitName string
}

// Code returns the frozen registered code.
func (f *MaterializationFailure) Code() string {
	switch f.Kind {
	case MaterializationUnsupportedProfile:
		return "core.materialization.unsupported-profile@1"
	case MaterializationUnsupportedStyle:
		return "core.materialization.unsupported-style@1"
	case MaterializationUnsupportedEncoding:
		return "core.materialization.unsupported-encoding@1"
	case MaterializationUnsupportedNewline:
		return "core.materialization.unsupported-newline@1"
	case MaterializationUnrepresentable:
		return "core.materialization.unrepresentable@1"
	case MaterializationResourceLimit:
		return "core.materialization.resource-limit@1"
	case MaterializationFormationFailed:
		return "core.materialization.formation-failed@1"
	}
	return "core.materialization.invalid-request@1"
}

// Error implements error; the text is human presentation only.
func (f *MaterializationFailure) Error() string {
	switch f.Kind {
	case MaterializationUnsupportedProfile:
		return "ini: unsupported materialization profile"
	case MaterializationUnsupportedStyle:
		return "ini: unsupported materialization style"
	case MaterializationUnsupportedEncoding:
		return "ini: unsupported materialization encoding"
	case MaterializationUnsupportedNewline:
		return "ini: unsupported materialization newline policy"
	case MaterializationUnrepresentable:
		return "ini: input kind " + f.KindName + " is not representable"
	case MaterializationResourceLimit:
		return "ini: materialization resource limit " + f.LimitName + " was reached"
	case MaterializationFormationFailed:
		return "ini: generated bytes did not form an INI document"
	}
	return "ini: materialization failed"
}

// MaterializationReport is the complete ordered materialization report
// (always empty for INI: no transformation events exist on the exact
// path).
type MaterializationReport struct {
	events []*protocol.Diagnostic
}

// Events returns the ordered transformation/loss events. The returned
// slice is a copy.
func (r MaterializationReport) Events() []*protocol.Diagnostic {
	return append([]*protocol.Diagnostic(nil), r.events...)
}

// MaterializationRelation is the input-to-output relation of one
// materialized origin.
type MaterializationRelation string

// The three frozen relations.
const (
	// MaterializationRelationDirect is a direct native semantic origin.
	MaterializationRelationDirect MaterializationRelation = "Direct"
	// MaterializationRelationGenerated is an output identity synthesized
	// by the materializer.
	MaterializationRelationGenerated MaterializationRelation = "Generated"
	// MaterializationRelationReencoded is an explicitly re-encoded input
	// origin.
	MaterializationRelationReencoded MaterializationRelation = "Reencoded"
)

// MaterializationInputLocation is one input value or association location.
type MaterializationInputLocation struct {
	// Path is the portable value location of Value locations.
	Path protocol.ValuePath
	// Association is the portable association location of Association
	// locations.
	Association *protocol.AssociationLocation
	// Kind is "Value" or "Association".
	Kind string
}

// MaterializedOrigin is one exact materialized output origin.
type MaterializedOrigin struct {
	// Snapshot is the output document snapshot.
	Snapshot document.SnapshotIdentity
	// Node is the exact structural identity.
	Node document.NodeRef
	// Span is the exact source range.
	Span document.Span
	// Relation is the output relation.
	Relation MaterializationRelation
}

// MaterializationProvenanceEntry is one input-to-outputs mapping entry.
type MaterializationProvenanceEntry struct {
	// Input is the input value or association location.
	Input MaterializationInputLocation
	// Outputs are the ordered output origins.
	Outputs []MaterializedOrigin
}

// MaterializationProvenanceMap is the immutable input-to-output provenance
// map.
type MaterializationProvenanceMap struct {
	entries []MaterializationProvenanceEntry
}

// Entries returns the deterministic entries. The returned slice is a copy.
func (m MaterializationProvenanceMap) Entries() []MaterializationProvenanceEntry {
	return append([]MaterializationProvenanceEntry(nil), m.entries...)
}

// CompleteMaterialization is the complete value materialization result.
type CompleteMaterialization struct {
	// Document is the new immutable target document.
	Document *Document
	// Fidelity is the fidelity of the whole operation.
	Fidelity MaterializationFidelity
	// Report is the machine-readable transformation report.
	Report MaterializationReport
	// Provenance maps every input value and association to its outputs.
	Provenance MaterializationProvenanceMap
}

// FailedMaterializationAttempt is the failed attempt without a document.
type FailedMaterializationAttempt struct {
	// Failure is the typed failure.
	Failure MaterializationFailure
	// Report holds the events discovered before the failure.
	Report MaterializationReport
	// AnalyzedInputPaths are the input paths analyzed before failure.
	AnalyzedInputPaths []protocol.ValuePath
}

// MaterializationResult is the materialization completion algebra.
// Exactly one outcome is non-nil.
type MaterializationResult struct {
	// Complete is the complete success outcome.
	Complete *CompleteMaterialization
	// Failed is the failed attempt with no document.
	Failed *FailedMaterializationAttempt
}

// Materialize materializes one nested String mapping into a new canonical
// INI document under an exact profile, style, encoding, and newline
// contract (materialization.rs:27-41).
func Materialize(value core.Value,
	request document.MaterializationRequest) MaterializationResult {
	analyzed := make([]protocol.ValuePath, 0, 16)
	complete, failure := materializeComplete(value, request, &analyzed)
	if failure != nil {
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure: *failure, AnalyzedInputPaths: analyzed,
		}}
	}
	return MaterializationResult{Complete: complete}
}

// materializeComplete runs the whole atomic pipeline (materialization.rs:
// 43-75).
func materializeComplete(value core.Value, request document.MaterializationRequest,
	analyzed *[]protocol.ValuePath) (*CompleteMaterialization, *MaterializationFailure) {
	profile, failure := requestedProfile(request)
	if failure != nil {
		return nil, failure
	}
	if failure := validateRequest(request, profile); failure != nil {
		return nil, failure
	}
	utf8Budget, failure := textBudget(request.Encoding(), request.Limits().MaxOutputBytes)
	if failure != nil {
		return nil, failure
	}
	writer := &materializationWriter{
		profile: profile, limits: request.Limits(),
		inputNodes: 0, output: boundedText{maxBytes: utf8Budget}, analyzed: analyzed,
	}
	sections, failure := writer.document(value, protocol.RootValuePath(), 0)
	if failure != nil {
		return nil, failure
	}
	text := writer.output.finish()
	bytes, failure := encodeText(text, request.Encoding(), request.Limits().MaxOutputBytes)
	if failure != nil {
		return nil, failure
	}
	selection := parseEncodingSelection(profile, request.Encoding())
	materialized, formationFailure := Parse(bytes, profile, selection, parseLimits(request.Limits()))
	if formationFailure != nil {
		return nil, &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	if materialized.FormationStatus() != document.FormationStatusComplete {
		return nil, &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	if failure := verifyClosure(value, request, materialized); failure != nil {
		return nil, failure
	}
	provenance, failure := buildProvenance(value, sections, materialized, request.Limits())
	if failure != nil {
		return nil, failure
	}
	return &CompleteMaterialization{
		Document: materialized, Fidelity: MaterializationFidelityExact,
		Provenance: provenance,
	}, nil
}

// requestedProfile resolves the frozen target profile (materialization.rs:
// 77-89).
func requestedProfile(request document.MaterializationRequest) (IniProfile, *MaterializationFailure) {
	switch {
	case request.TargetProfile().ID() == "ini.portable" && request.TargetProfile().Version() == 1:
		return PortableV1, nil
	case request.TargetProfile().ID() == "ini.windows" && request.TargetProfile().Version() == 1:
		return WindowsV1, nil
	case request.TargetProfile().ID() == "ini.python-configparser" &&
		request.TargetProfile().Version() == 1:
		return PythonConfigParserV1, nil
	}
	return IniProfile{}, &MaterializationFailure{Kind: MaterializationUnsupportedProfile}
}

// validateRequest enforces the exact style/newline/encoding contract
// (materialization.rs:91-127).
func validateRequest(request document.MaterializationRequest,
	profile IniProfile) *MaterializationFailure {
	styleMatches := false
	switch {
	case profile.isPortable():
		styleMatches = request.Style().ID() == "ini.portable-canonical" &&
			request.Style().Version() == 1
	case profile.isWindows():
		styleMatches = request.Style().ID() == "ini.windows-canonical" &&
			request.Style().Version() == 1
	case profile.isPython():
		styleMatches = request.Style().ID() == "ini.python-configparser-canonical" &&
			request.Style().Version() == 1
	}
	if !styleMatches {
		return &MaterializationFailure{Kind: MaterializationUnsupportedStyle}
	}
	expectedNewline := document.NewlineLf
	if profile.isWindows() {
		expectedNewline = document.NewlineCrLf
	}
	if request.Newline() != expectedNewline {
		return &MaterializationFailure{Kind: MaterializationUnsupportedNewline}
	}
	encodingValid := false
	switch {
	case profile.isPortable():
		encodingValid = request.Encoding().Equal(document.Utf8Encoding())
	case profile.isWindows():
		encodingValid = request.Encoding().Equal(document.Utf16LeEncoding()) ||
			request.Encoding().Kind() == document.EncodingWindowsCodePage
	case profile.isPython():
		encodingValid = request.Encoding().Kind() != document.EncodingBinary
	}
	if !encodingValid {
		return &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
	}
	return nil
}

// parseEncodingSelection maps one output encoding onto the parse
// selection (materialization.rs:129-135).
func parseEncodingSelection(profile IniProfile,
	encoding document.SourceEncoding) IniEncodingSelection {
	if (profile.isPortable() || profile.isPython()) &&
		encoding.Equal(document.Utf8Encoding()) {
		return IniEncodingProfileDefault()
	}
	if profile.isWindows() && encoding.Equal(document.Utf16LeEncoding()) {
		return IniEncodingProfileDefault()
	}
	return IniEncodingExplicit(encoding)
}

// parseLimits maps the materialization limits onto the parse limits
// (materialization.rs:137-160).
func parseLimits(limits document.MaterializationLimits) IniParseLimits {
	return IniParseLimits{
		Common: document.ParseLimits{
			MaxSourceBytes:  limits.MaxOutputBytes,
			MaxNestingDepth: limits.MaxDepth,
			MaxTokenCount:   limits.MaxOutputBytes,
			MaxNodeCount:    limits.MaxOutputBytes,
			MaxDiagnostics:  limits.MaxReportEntries,
		},
		MaxDecodedUTF8Bytes:      limits.MaxOutputBytes * 3,
		MaxDecodedScalars:        limits.MaxOutputBytes,
		MaxPhysicalLines:         limits.MaxOutputBytes,
		MaxPhysicalLineBytes:     limits.MaxOutputBytes,
		MaxPhysicalLineScalars:   limits.MaxOutputBytes,
		MaxLogicalLines:          limits.MaxInputNodes,
		MaxLogicalLineBytes:      limits.MaxOutputBytes,
		MaxLogicalLineScalars:    limits.MaxOutputBytes,
		MaxContinuationLines:     limits.MaxOutputBytes,
		MaxSections:              limits.MaxInputNodes,
		MaxEntries:               limits.MaxInputNodes,
		MaxDuplicateGroupMembers: limits.MaxInputNodes,
		MaxRecoveryRegions:       limits.MaxReportEntries,
	}
}

// mappingShape is the closed input mapping shape.
type mappingShape uint8

const (
	shapeObject mappingShape = iota
	shapeEntryMapping
)

// inputSection and inputEntry track the input locations for provenance.
type inputEntry struct {
	association protocol.AssociationLocation
	key         MaterializationInputLocation
	value       MaterializationInputLocation
}

type inputSection struct {
	association protocol.AssociationLocation
	key         MaterializationInputLocation
	value       MaterializationInputLocation
	entries     []inputEntry
}

type mappingItem struct {
	key         string
	value       core.Value
	association protocol.AssociationLocation
	keyLocation MaterializationInputLocation
	valuePath   protocol.ValuePath
}

// materializationWriter renders the canonical text with the frozen styles.
type materializationWriter struct {
	profile    IniProfile
	limits     document.MaterializationLimits
	inputNodes int
	output     boundedText
	analyzed   *[]protocol.ValuePath
}

func (w *materializationWriter) document(value core.Value, path protocol.ValuePath,
	depth int) ([]inputSection, *MaterializationFailure) {
	shape, outer, failure := w.mappingItems(value, path, depth)
	if failure != nil {
		return nil, failure
	}
	if shape == shapeObject && w.profile.isWindows() {
		if failure := rejectCaseEquivalentObjectNames(outer); failure != nil {
			return nil, failure
		}
	}
	var sections []inputSection
	for _, section := range outer {
		if failure := w.validateSectionName(section.key); failure != nil {
			return nil, failure
		}
		if failure := w.output.pushString("["); failure != nil {
			return nil, failure
		}
		if failure := w.output.pushString(section.key); failure != nil {
			return nil, failure
		}
		if failure := w.output.pushString("]"); failure != nil {
			return nil, failure
		}
		if failure := w.newline(); failure != nil {
			return nil, failure
		}
		entryShape, entries, failure := w.mappingItems(section.value, section.valuePath, depth+1)
		if failure != nil {
			return nil, failure
		}
		if entryShape == shapeObject && w.profile.isWindows() {
			if failure := rejectCaseEquivalentObjectNames(entries); failure != nil {
				return nil, failure
			}
		}
		var inputEntries []inputEntry
		for _, entry := range entries {
			if failure := w.validateKey(entry.key); failure != nil {
				return nil, failure
			}
			if failure := w.analyze(&entry.valuePath, depth+2); failure != nil {
				return nil, failure
			}
			text, ok := entry.value.(core.String)
			if !ok {
				return nil, &MaterializationFailure{Kind: MaterializationUnrepresentable,
					Path: entry.valuePath, KindName: entry.value.Kind().String()}
			}
			if failure := w.writeEntry(entry.key, string(text)); failure != nil {
				return nil, failure
			}
			inputEntries = append(inputEntries, inputEntry{
				association: entry.association, key: entry.keyLocation,
				value: MaterializationInputLocation{Kind: "Value", Path: entry.valuePath},
			})
		}
		sections = append(sections, inputSection{
			association: section.association, key: section.keyLocation,
			value:   MaterializationInputLocation{Kind: "Value", Path: section.valuePath},
			entries: inputEntries,
		})
	}
	return sections, nil
}

func (w *materializationWriter) mappingItems(value core.Value, path protocol.ValuePath,
	depth int) (mappingShape, []mappingItem, *MaterializationFailure) {
	if failure := w.analyze(&path, depth); failure != nil {
		return 0, nil, failure
	}
	var length int
	switch typed := value.(type) {
	case *core.Object:
		length = typed.Len()
	case *core.EntryMapping:
		length = typed.Len()
	default:
		return 0, nil, &MaterializationFailure{Kind: MaterializationUnrepresentable,
			Path: path, KindName: value.Kind().String()}
	}
	if length > w.limits.MaxInputNodes {
		return 0, nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "input-nodes"}
	}
	items := make([]mappingItem, 0, length)
	switch typed := value.(type) {
	case *core.Object:
		for index, entry := range typed.Entries() {
			ordinal := uint64(index)
			items = append(items, mappingItem{
				key: entry.Key, value: entry.Value,
				association: protocol.NewAssociationLocation(path, ordinal,
					protocol.AssociationRoleObjectEntry),
				keyLocation: MaterializationInputLocation{Kind: "Association",
					Association: associationPtr(protocol.NewAssociationLocation(path, ordinal,
						protocol.AssociationRoleObjectKey))},
				valuePath: path.Child(protocol.ValuePathSegment{Kind: "ObjectValue",
					Key: entry.Key}),
			})
		}
		return shapeObject, items, nil
	case *core.EntryMapping:
		for index, entry := range typed.Entries() {
			ordinal := uint64(index)
			keyPath := path.Child(protocol.ValuePathSegment{Kind: "EntryKey", Index: ordinal})
			if failure := w.analyze(&keyPath, depth+1); failure != nil {
				return 0, nil, failure
			}
			key, ok := entry.Key.(core.String)
			if !ok {
				return 0, nil, &MaterializationFailure{Kind: MaterializationUnrepresentable,
					Path: keyPath, KindName: entry.Key.Kind().String()}
			}
			items = append(items, mappingItem{
				key: string(key), value: entry.Value,
				association: protocol.NewAssociationLocation(path, ordinal,
					protocol.AssociationRoleEntryMappingItem),
				keyLocation: MaterializationInputLocation{Kind: "Value", Path: keyPath},
				valuePath: path.Child(protocol.ValuePathSegment{Kind: "EntryValue",
					Index: ordinal}),
			})
		}
		return shapeEntryMapping, items, nil
	}
	return 0, nil, &MaterializationFailure{Kind: MaterializationUnrepresentable,
		Path: path, KindName: value.Kind().String()}
}

func (w *materializationWriter) analyze(path *protocol.ValuePath,
	depth int) *MaterializationFailure {
	if depth > w.limits.MaxDepth {
		return &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "input-depth"}
	}
	w.inputNodes++
	if w.inputNodes > w.limits.MaxInputNodes {
		return &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "input-nodes"}
	}
	*w.analyzed = append(*w.analyzed, *path)
	return nil
}

func (w *materializationWriter) validateSectionName(value string) *MaterializationFailure {
	valid := false
	switch {
	case w.profile.isPortable():
		valid = len(value) > 0 && allBytes(value, isPortableName)
	case w.profile.isWindows():
		valid = len(value) > 0 && allBytes(value, isWindowsName)
	case w.profile.isPython():
		valid = len(value) > 0 && !strings.ContainsAny(value, "\x00\r\n")
	}
	if valid {
		return nil
	}
	return &MaterializationFailure{Kind: MaterializationUnrepresentable,
		KindName: "section name is not representable"}
}

func (w *materializationWriter) validateKey(value string) *MaterializationFailure {
	valid := false
	switch {
	case w.profile.isPortable():
		valid = len(value) > 0 && allBytes(value, isPortableName)
	case w.profile.isWindows():
		valid = len(value) > 0 && allBytes(value, isWindowsName)
	case w.profile.isPython():
		valid = len(value) > 0 && !strings.ContainsAny(value, "\x00\r\n=:") &&
			trimHorizontal(value) == value
	}
	if valid {
		return nil
	}
	return &MaterializationFailure{Kind: MaterializationUnrepresentable,
		KindName: "entry key is not representable"}
}

func (w *materializationWriter) writeEntry(key, value string) *MaterializationFailure {
	switch {
	case w.profile.isPortable():
		if !allBytes(value, isPortableValue) {
			return &MaterializationFailure{Kind: MaterializationUnrepresentable,
				KindName: "portable value is not representable"}
		}
		if failure := w.output.pushString(key); failure != nil {
			return failure
		}
		if failure := w.output.pushString("="); failure != nil {
			return failure
		}
		if failure := w.output.pushString(value); failure != nil {
			return failure
		}
		return w.newline()
	case w.profile.isWindows():
		if strings.ContainsAny(value, "\x00\r\n") {
			return &MaterializationFailure{Kind: MaterializationUnrepresentable,
				KindName: "Windows value is not representable"}
		}
		if failure := w.output.pushString(key); failure != nil {
			return failure
		}
		if failure := w.output.pushString("="); failure != nil {
			return failure
		}
		if windowsValueNeedsQuotes(value) {
			quote := byte('"')
			if len(value) >= 2 && value[0] == '"' && value[len(value)-1] == '"' {
				quote = '\''
			}
			if failure := w.output.pushByte(quote); failure != nil {
				return failure
			}
			if failure := w.output.pushString(value); failure != nil {
				return failure
			}
			if failure := w.output.pushByte(quote); failure != nil {
				return failure
			}
		} else if failure := w.output.pushString(value); failure != nil {
			return failure
		}
		return w.newline()
	default:
		return w.writePythonEntry(key, value)
	}
}

func (w *materializationWriter) writePythonEntry(key, value string) *MaterializationFailure {
	if strings.ContainsAny(value, "\x00\r") {
		return &MaterializationFailure{Kind: MaterializationUnrepresentable,
			KindName: "Python value is not representable"}
	}
	if strings.HasSuffix(value, "\n") {
		return &MaterializationFailure{Kind: MaterializationUnrepresentable,
			KindName: "trailing empty Python value line is not representable"}
	}
	lines := strings.Split(value, "\n")
	first := lines[0]
	if failure := validatePythonValueLine(first); failure != nil {
		return failure
	}
	if failure := w.output.pushString(key); failure != nil {
		return failure
	}
	if failure := w.output.pushString(" ="); failure != nil {
		return failure
	}
	if len(first) > 0 {
		if failure := w.output.pushString(" "); failure != nil {
			return failure
		}
		if failure := w.output.pushString(first); failure != nil {
			return failure
		}
	}
	if failure := w.newline(); failure != nil {
		return failure
	}
	for _, line := range lines[1:] {
		if failure := validatePythonValueLine(line); failure != nil {
			return failure
		}
		if len(line) > 0 {
			if failure := w.output.pushString("    "); failure != nil {
				return failure
			}
			if failure := w.output.pushString(line); failure != nil {
				return failure
			}
		}
		if failure := w.newline(); failure != nil {
			return failure
		}
	}
	return nil
}

func (w *materializationWriter) newline() *MaterializationFailure {
	if w.profile.isWindows() {
		return w.output.pushString("\r\n")
	}
	return w.output.pushString("\n")
}

// validatePythonValueLine rejects per-line edge whitespace that the frozen
// parser would normalize away (materialization.rs:463-471).
func validatePythonValueLine(line string) *MaterializationFailure {
	if trimHorizontal(line) == line {
		return nil
	}
	return &MaterializationFailure{Kind: MaterializationUnrepresentable,
		KindName: "Python value line edge whitespace is not representable"}
}

// rejectCaseEquivalentObjectNames rejects Object input that would fabricate
// Windows case-equivalent collisions (materialization.rs:473-487).
func rejectCaseEquivalentObjectNames(items []mappingItem) *MaterializationFailure {
	seen := map[string]bool{}
	for _, item := range items {
		lowered := stringsToLowerASCII(item.key)
		if seen[lowered] {
			return &MaterializationFailure{Kind: MaterializationUnrepresentable,
				KindName: "Object cannot fabricate Windows case-equivalent collisions"}
		}
		seen[lowered] = true
	}
	return nil
}

// verifyClosure reprojects the materialized document under the request's
// policy and requires exact equality with the input
// (materialization.rs:489-535).
func verifyClosure(input core.Value, request document.MaterializationRequest,
	document *Document) *MaterializationFailure {
	projectionLimits := ProjectionLimits{
		MaxSourceAssociations: request.Limits().MaxInputNodes,
		MaxValueNodes:         request.Limits().MaxInputNodes,
		MaxReportEntries:      request.Limits().MaxReportEntries,
		MaxProvenanceUnits:    request.Limits().MaxProvenanceEntries,
	}
	var projection ProjectionResult
	if _, isObject := input.(*core.Object); isObject {
		projection = document.Project(RequireObjectV1(ComparisonOriginalExact,
			CollisionPolicyReject).WithLimits(projectionLimits))
	} else {
		projection = document.Project(BestExactEntryMappingV1().WithLimits(projectionLimits))
	}
	switch {
	case projection.Complete != nil && core.Equal(projection.Complete.Value, input):
		return nil
	case projection.Failed != nil && len(projection.Failed.Diagnostics) > 0 &&
		projection.Failed.Diagnostics[0].Code == "core.projection.resource-limit@1":
		limit := projection.Failed.Diagnostics[0].Arguments["limit"]
		switch limit {
		case "max_source_associations", "max_value_nodes":
			return &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "input-nodes"}
		case "max_report_entries":
			return &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "report-entries"}
		case "max_provenance_units":
			return &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "provenance-entries"}
		default:
			return &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "projection"}
		}
	default:
		return &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
}

// buildProvenance maps every input location to its materialized outputs
// (materialization.rs:537-627).
func buildProvenance(input core.Value, sections []inputSection, document *Document,
	limits document.MaterializationLimits) (MaterializationProvenanceMap, *MaterializationFailure) {
	var entries []MaterializationProvenanceEntry
	rootSpan, ok := document.span(0, document.source.Len())
	if !ok {
		return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	entries = append(entries, MaterializationProvenanceEntry{
		Input: MaterializationInputLocation{Kind: "Value", Path: protocol.RootValuePath()},
		Outputs: []MaterializedOrigin{{
			Snapshot: document.SnapshotIdentity(), Node: document.rootNode,
			Span: rootSpan, Relation: MaterializationRelationReencoded,
		}},
	})
	entryOffset := 0
	for sectionIndex, inputSection := range sections {
		if sectionIndex >= len(document.sections) {
			return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
		section := document.sections[sectionIndex]
		entries = append(entries, provenanceEntry(
			MaterializationInputLocation{Kind: "Association",
				Association: associationPtr(inputSection.association)},
			section.node, section.span, document))
		entries = append(entries, provenanceEntry(inputSection.key, section.node,
			section.nameSpan, document))
		entries = append(entries, provenanceEntry(inputSection.value, section.node,
			section.span, document))
		for _, inputEntry := range inputSection.entries {
			if entryOffset >= len(document.entries) {
				return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFormationFailed}
			}
			entry := document.entries[entryOffset]
			if entry.section != section.node {
				return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFormationFailed}
			}
			entries = append(entries, provenanceEntry(
				MaterializationInputLocation{Kind: "Association",
					Association: associationPtr(inputEntry.association)},
				entry.node, entry.span, document))
			entries = append(entries, provenanceEntry(inputEntry.key, entry.node,
				entry.keySpan, document))
			outputs := []MaterializedOrigin{{
				Snapshot: document.SnapshotIdentity(), Node: entry.node,
				Span: entry.valueSpan, Relation: MaterializationRelationReencoded,
			}}
			appendContinuationOutputs(document, entry, &outputs)
			entries = append(entries, MaterializationProvenanceEntry{
				Input: inputEntry.value, Outputs: outputs,
			})
			entryOffset++
		}
	}
	switch input.(type) {
	case *core.Object, *core.EntryMapping:
	default:
		return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	if entryOffset != len(document.entries) {
		return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	if len(entries) > limits.MaxProvenanceEntries {
		return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "provenance-entries"}
	}
	return MaterializationProvenanceMap{entries: entries}, nil
}

// appendContinuationOutputs adds the continuation-line value origins
// (materialization.rs:629-659).
func appendContinuationOutputs(document *Document, entry IniEntry,
	outputs *[]MaterializedOrigin) {
	logical, ok := document.LogicalLine(entry.logicalLine)
	if !ok {
		return
	}
	for _, physicalNode := range logical.PhysicalLines()[1:] {
		physical, ok := document.PhysicalLine(physicalNode)
		if !ok {
			continue
		}
		start := 0
		pieces := document.index.Pieces()
		for index, piece := range pieces {
			if piece.Span().EndByte() <= physical.contentSpan.StartByte() {
				start = index + 1
			}
		}
		for ordinal := start; ordinal < len(pieces); ordinal++ {
			pieceSpan := pieces[ordinal].Span()
			if pieceSpan.StartByte() >= physical.contentSpan.EndByte() {
				break
			}
			if document.kinds[ordinal] == SyntaxKindEntryValue {
				*outputs = append(*outputs, MaterializedOrigin{
					Snapshot: document.SnapshotIdentity(), Node: entry.node,
					Span: pieceSpan, Relation: MaterializationRelationReencoded,
				})
			}
		}
	}
}

// provenanceEntry builds one single-output provenance entry.
func provenanceEntry(input MaterializationInputLocation, node document.NodeRef,
	span document.Span, document *Document) MaterializationProvenanceEntry {
	return MaterializationProvenanceEntry{
		Input: input,
		Outputs: []MaterializedOrigin{{
			Snapshot: document.SnapshotIdentity(), Node: node, Span: span,
			Relation: MaterializationRelationReencoded,
		}},
	}
}

// boundedText is the limit-bounded output accumulator.
type boundedText struct {
	text     string
	maxBytes int
}

func (b *boundedText) pushString(value string) *MaterializationFailure {
	if len(b.text)+len(value) > b.maxBytes {
		return &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "output-bytes"}
	}
	b.text += value
	return nil
}

func (b *boundedText) pushByte(value byte) *MaterializationFailure {
	if len(b.text)+1 > b.maxBytes {
		return &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "output-bytes"}
	}
	b.text += string([]byte{value})
	return nil
}

func (b *boundedText) finish() string { return b.text }

// textBudget projects the raw output budget onto the decoded-text budget
// (materialization.rs:724-738).
func textBudget(encoding document.SourceEncoding,
	maxOutputBytes int) (int, *MaterializationFailure) {
	switch encoding.Kind() {
	case document.EncodingUtf16Le, document.EncodingUtf16Be, document.EncodingLatin1:
		return maxOutputBytes * 2, nil
	case document.EncodingWindowsCodePage:
		if page, ok := encoding.WindowsCodePage(); ok && page.Number() != 65001 {
			return maxOutputBytes * 3, nil
		}
		return maxOutputBytes, nil
	case document.EncodingBinary:
		return 0, &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
	default:
		return maxOutputBytes, nil
	}
}

// encodeText encodes one text with the exact output encoding and BOM
// policy (materialization.rs:740-768).
func encodeText(text string, encoding document.SourceEncoding,
	maxOutputBytes int) ([]byte, *MaterializationFailure) {
	bomBytes := 0
	if encoding.Equal(document.Utf16LeEncoding()) || encoding.Equal(document.Utf16BeEncoding()) {
		bomBytes = 2
	}
	fragmentLimit := maxOutputBytes - bomBytes
	if fragmentLimit < 0 {
		return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "output-bytes"}
	}
	fragment, failure := encodeFragment(text, encoding, fragmentLimit)
	if failure != nil {
		return nil, failure
	}
	if bomBytes == 0 {
		return fragment, nil
	}
	output := make([]byte, 0, len(fragment)+2)
	if encoding.Equal(document.Utf16LeEncoding()) {
		output = append(output, 0xFF, 0xFE)
	} else {
		output = append(output, 0xFE, 0xFF)
	}
	return append(output, fragment...), nil
}

// encodeFragment encodes one text fragment strictly
// (materialization.rs:770-829). UTF-16 output never gains a marker here;
// Windows code pages encode exactly through the frozen tables (the
// two-byte 936/949/950 pages are not admitted on the encode side, matching
// go/document's decode posture).
func encodeFragment(text string, encoding document.SourceEncoding,
	maxOutputBytes int) ([]byte, *MaterializationFailure) {
	var output []byte
	switch encoding.Kind() {
	case document.EncodingUtf8:
		if len(text) > maxOutputBytes {
			return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "output-bytes"}
		}
		return []byte(text), nil
	case document.EncodingUtf16Le, document.EncodingUtf16Be:
		units := 0
		for _, character := range text {
			if character >= 0x10000 {
				units += 2
			} else {
				units++
			}
		}
		if units*2 > maxOutputBytes {
			return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "output-bytes"}
		}
		littleEndian := encoding.Kind() == document.EncodingUtf16Le
		for _, character := range text {
			if character >= 0x10000 {
				value := character - 0x10000
				output = appendUTF16(output, uint16(0xD800+value>>10), littleEndian)
				output = appendUTF16(output, uint16(0xDC00+value&0x3FF), littleEndian)
				continue
			}
			output = appendUTF16(output, uint16(character), littleEndian)
		}
		return output, nil
	case document.EncodingLatin1:
		if len(text) > maxOutputBytes {
			return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "output-bytes"}
		}
		for _, character := range text {
			if character > 0xFF {
				return nil, &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
			}
			output = append(output, byte(character))
		}
		return output, nil
	case document.EncodingWindowsCodePage:
		page, ok := encoding.WindowsCodePage()
		if !ok {
			return nil, &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
		}
		return encodeCodePage(text, page, maxOutputBytes)
	default:
		return nil, &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
	}
}

// appendUTF16 appends one UTF-16 code unit in the requested byte order.
func appendUTF16(output []byte, unit uint16, littleEndian bool) []byte {
	if littleEndian {
		return append(output, byte(unit), byte(unit>>8))
	}
	return append(output, byte(unit>>8), byte(unit))
}

// windowsValueNeedsQuotes reports whether one Windows canonical value must
// be quoted to preserve its semantic content (materialization.rs:874-888).
func windowsValueNeedsQuotes(value string) bool {
	if len(value) > 0 {
		first := value[0]
		last := value[len(value)-1]
		if first == ' ' || first == '\t' || last == ' ' || last == '\t' {
			return true
		}
		if len(value) >= 2 && ((first == '\'' && last == '\'') ||
			(first == '"' && last == '"')) {
			return true
		}
	}
	return false
}

// trimHorizontal trims leading and trailing horizontal whitespace.
func trimHorizontal(value string) string {
	start, end := trimHorizontalBounds(value)
	return value[start:end]
}

// allBytes reports whether every byte satisfies the predicate.
func allBytes(value string, predicate func(byte) bool) bool {
	for index := 0; index < len(value); index++ {
		if !predicate(value[index]) {
			return false
		}
	}
	return true
}

// associationPtr wraps one association location.
func associationPtr(location protocol.AssociationLocation) *protocol.AssociationLocation {
	return &location
}
