package json

import (
	"context"

	"consema.dev/consema/core"
	"consema.dev/consema/document"
	"consema.dev/consema/protocol"
)

// This file implements deterministic PortableValue materialization for the
// JSON-family profiles (consema-rs/consema-json/src/materialization.rs).
// Materialization is two-phase: the exact writer produces bytes under the
// resource budgets, then the bytes are reparsed into an immutable target
// document and the provenance facts are collected against it.

// MaterializationFailureKind is the stable materialization failure
// category (consema-document materialization.rs).
type MaterializationFailureKind uint8

// The closed materialization failure categories.
const (
	// MaterializationFailureInvalidRequest: request fields are
	// contradictory.
	MaterializationFailureInvalidRequest MaterializationFailureKind = iota
	// MaterializationFailureUnsupportedProfile: the target profile is
	// unavailable.
	MaterializationFailureUnsupportedProfile
	// MaterializationFailureUnsupportedStyle: the target style is
	// unavailable for the profile.
	MaterializationFailureUnsupportedStyle
	// MaterializationFailureUnsupportedEncoding: the target encoding is
	// unsupported.
	MaterializationFailureUnsupportedEncoding
	// MaterializationFailureUnsupportedNewline: the target style does not
	// support the newline policy.
	MaterializationFailureUnsupportedNewline
	// MaterializationFailureUnrepresentable: a portable input cannot be
	// represented by the target profile.
	MaterializationFailureUnrepresentable
	// MaterializationFailureResourceLimit: a configured bound was reached;
	// output is not truncated to success.
	MaterializationFailureResourceLimit
	// MaterializationFailureFormationFailed: the generated bytes did not
	// form the required target document.
	MaterializationFailureFormationFailed
)

// MaterializationFailure is the typed materialization failure. It
// implements error and the RFC 0016 §6 Code() contract with the frozen
// registered codes.
type MaterializationFailure struct {
	// Kind identifies the failure.
	Kind MaterializationFailureKind
	// Path is the offending input location of Unrepresentable.
	Path protocol.ValuePath
	// ValueKind is the offending PortableValue kind of Unrepresentable.
	ValueKind core.Kind
	// LimitName is the stable limit name of a ResourceLimit.
	LimitName string
}

// Error implements error.
func (e *MaterializationFailure) Error() string {
	switch e.Kind {
	case MaterializationFailureInvalidRequest:
		return "json: materialization request fields are contradictory"
	case MaterializationFailureUnsupportedProfile:
		return "json: materialization profile is unavailable"
	case MaterializationFailureUnsupportedStyle:
		return "json: materialization style is unavailable for the profile"
	case MaterializationFailureUnsupportedEncoding:
		return "json: materialization encoding is unsupported"
	case MaterializationFailureUnsupportedNewline:
		return "json: materialization newline policy is unsupported by the style"
	case MaterializationFailureUnrepresentable:
		return "json: portable kind " + e.ValueKind.String() + " is not representable"
	case MaterializationFailureResourceLimit:
		return "json: materialization limit " + e.LimitName + " reached"
	case MaterializationFailureFormationFailed:
		return "json: generated bytes did not form the target document"
	}
	return "json: materialization failure"
}

// Code returns the frozen registered code for the failure
// (consema-document materialization.rs).
func (e *MaterializationFailure) Code() string {
	switch e.Kind {
	case MaterializationFailureInvalidRequest:
		return "core.materialization.invalid-request@1"
	case MaterializationFailureUnsupportedProfile:
		return "core.materialization.unsupported-profile@1"
	case MaterializationFailureUnsupportedStyle:
		return "core.materialization.unsupported-style@1"
	case MaterializationFailureUnsupportedEncoding:
		return "core.materialization.unsupported-encoding@1"
	case MaterializationFailureUnsupportedNewline:
		return "core.materialization.unsupported-newline@1"
	case MaterializationFailureUnrepresentable:
		return "core.materialization.unrepresentable@1"
	case MaterializationFailureResourceLimit:
		return "core.materialization.resource-limit@1"
	case MaterializationFailureFormationFailed:
		return "core.materialization.formation-failed@1"
	}
	return "core.materialization.formation-failed@1"
}

// MaterializationFidelity is the closed materialization fidelity
// (consema-document materialization.rs).
type MaterializationFidelity uint8

// The two frozen fidelity classes.
const (
	// MaterializationFidelityExact means every input fact round-trips
	// through the target's exact projection contract.
	MaterializationFidelityExact MaterializationFidelity = iota
	// MaterializationFidelityTransformed means complete semantics survive
	// an explicit reversible re-encoding.
	MaterializationFidelityTransformed
)

// String returns the stable fidelity name.
func (f MaterializationFidelity) String() string {
	switch f {
	case MaterializationFidelityExact:
		return "Exact"
	case MaterializationFidelityTransformed:
		return "Transformed"
	}
	return "Exact"
}

// MaterializationRelation is the source-to-output relation of one
// materialization provenance origin (consema-document materialization.rs).
type MaterializationRelation string

// The three frozen relations.
const (
	// MaterializationRelationDirect is a direct native semantic origin.
	MaterializationRelationDirect MaterializationRelation = "Direct"
	// MaterializationRelationGenerated is a generated structural origin.
	MaterializationRelationGenerated MaterializationRelation = "Generated"
	// MaterializationRelationReencoded is a reversible re-encoding origin.
	MaterializationRelationReencoded MaterializationRelation = "Reencoded"
)

// MaterializedOrigin is one exact output origin.
type MaterializedOrigin struct {
	// Snapshot is the target document snapshot.
	Snapshot document.SnapshotIdentity
	// Node is the exact output structural identity.
	Node document.NodeRef
	// Span is the exact output source range.
	Span document.Span
	// Relation is the source relation.
	Relation MaterializationRelation
}

// MaterializationInputLocation is one input value or association location.
type MaterializationInputLocation struct {
	// IsAssociation reports whether the location is an association.
	IsAssociation bool
	// Path is the input value location.
	Path protocol.ValuePath
	// Association is the input association location.
	Association protocol.AssociationLocation
}

// MaterializationProvenanceEntry is one input-to-outputs mapping entry.
type MaterializationProvenanceEntry struct {
	// Input is the exact input location.
	Input MaterializationInputLocation
	// Outputs are the output origins.
	Outputs []MaterializedOrigin
}

// MaterializationProvenanceMap is the immutable input-to-output
// provenance map.
type MaterializationProvenanceMap struct {
	entries []MaterializationProvenanceEntry
}

// Entries returns the ordered entries. The returned slice is a copy.
func (m *MaterializationProvenanceMap) Entries() []MaterializationProvenanceEntry {
	return append([]MaterializationProvenanceEntry(nil), m.entries...)
}

// MaterializationReport is the complete materialization report; JSON v1
// materialization never transforms, so the report is empty by default.
type MaterializationReport struct {
	events []*protocol.Diagnostic
}

// Events returns the ordered report events. The returned slice is a copy.
func (r *MaterializationReport) Events() []*protocol.Diagnostic {
	return append([]*protocol.Diagnostic(nil), r.events...)
}

// CompleteMaterialization is the complete successful materialization.
type CompleteMaterialization struct {
	// Document is the new immutable target document.
	Document *Document
	// Fidelity is the worst fidelity of the whole operation.
	Fidelity MaterializationFidelity
	// Report is the transformation/loss report.
	Report MaterializationReport
	// Provenance is the input-to-output provenance map.
	Provenance MaterializationProvenanceMap
}

// FailedMaterializationAttempt is a failed attempt without a document.
type FailedMaterializationAttempt struct {
	// Failure is the stable failure.
	Failure *MaterializationFailure
	// Report holds the events discovered before the failed completion
	// check.
	Report MaterializationReport
	// AnalyzedInputPaths are the stable path descriptions of locally
	// analyzed input regions.
	AnalyzedInputPaths []protocol.ValuePath
}

// MaterializationResult is the sealed materialization outcome: exactly one
// of Complete or Failed is set.
type MaterializationResult struct {
	// Complete is the successful outcome.
	Complete *CompleteMaterialization
	// Failed is the failed attempt.
	Failed *FailedMaterializationAttempt
}

// Materialize materializes one complete PortableValue into a new immutable
// JSON or JSONC document (materialization.rs).
func Materialize(value core.Value, request document.MaterializationRequest) MaterializationResult {
	analyzed := make([]protocol.ValuePath, 0, 16)
	complete, failure := materializeComplete(value, request, &analyzed)
	if failure != nil {
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure:            failure,
			Report:             MaterializationReport{},
			AnalyzedInputPaths: analyzed,
		}}
	}
	return MaterializationResult{Complete: complete}
}

// canonicalFragment renders one value as a canonical profile fragment; it
// is the exact writer used by structural edits (materialization.rs).
func canonicalFragment(value core.Value, profile JsonProfile,
	limits document.MaterializationLimits) ([]byte, *MaterializationFailure) {
	analyzed := make([]protocol.ValuePath, 0, 16)
	style := jsonStyleCompact
	if profile.isJSON5() {
		style = jsonStyleJson5Compact
	}
	writer := newJSONWriter(style, document.NewlineNone, limits, &analyzed)
	if failure := writer.value(value, protocol.RootValuePath(), 0); failure != nil {
		return nil, failure
	}
	return writer.output.finish(), nil
}

// materializeComplete runs the two-phase materialization
// (materialization.rs).
func materializeComplete(value core.Value, request document.MaterializationRequest,
	analyzed *[]protocol.ValuePath) (*CompleteMaterialization, *MaterializationFailure) {
	profile, failure := requestedProfile(request)
	if failure != nil {
		return nil, failure
	}
	style, failure := requestedStyle(request, profile)
	if failure != nil {
		return nil, failure
	}
	if !request.Encoding().IsText() || request.Encoding().AsStr() != "utf-8" {
		return nil, &MaterializationFailure{Kind: MaterializationFailureUnsupportedEncoding}
	}
	if style.isPretty() && request.Newline() == document.NewlineNone {
		return nil, &MaterializationFailure{Kind: MaterializationFailureUnsupportedNewline}
	}
	writer := newJSONWriter(style, request.Newline(), request.Limits(), analyzed)
	if failure := writer.value(value, protocol.RootValuePath(), 0); failure != nil {
		return nil, failure
	}
	if request.Newline() != document.NewlineNone {
		if failure := writer.output.pushBytes(request.Newline().Bytes()); failure != nil {
			return nil, failure
		}
	}
	bytes := writer.output.finish()
	target, formationFailure := Parse(contextBackground(), bytes, profile, parseLimitsFor(request.Limits()))
	if formationFailure != nil {
		return nil, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	if target.formationStatus != document.FormationStatusComplete {
		return nil, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	builder := &provenanceBuilder{document: target, limits: request.Limits()}
	if failure := builder.collect(value, protocol.RootValuePath(), target.Root()); failure != nil {
		return nil, failure
	}
	provenance := &MaterializationProvenanceMap{entries: builder.entries}
	return &CompleteMaterialization{
		Document:   target,
		Fidelity:   MaterializationFidelityExact,
		Report:     MaterializationReport{},
		Provenance: *provenance,
	}, nil
}

// jsonStyle is the closed output style.
type jsonStyle uint8

const (
	jsonStyleCompact jsonStyle = iota
	jsonStylePretty
	jsonStyleJson5Compact
	jsonStyleJson5Pretty
)

func (s jsonStyle) isPretty() bool {
	return s == jsonStylePretty || s == jsonStyleJson5Pretty
}

func (s jsonStyle) isJSON5() bool {
	return s == jsonStyleJson5Compact || s == jsonStyleJson5Pretty
}

// requestedProfile resolves the target profile (materialization.rs).
func requestedProfile(request document.MaterializationRequest) (JsonProfile, *MaterializationFailure) {
	profile := request.TargetProfile()
	switch {
	case profile.ID() == "json.strict" && profile.Version() == 1:
		return JsonProfileStrictV1, nil
	case profile.ID() == "jsonc.bounded" && profile.Version() == 1:
		return JsonProfileJsoncBoundedV1, nil
	case profile.ID() == "json5.standard" && profile.Version() == 1:
		return JsonProfileJson5StandardV1, nil
	}
	return JsonProfileStrictV1, &MaterializationFailure{Kind: MaterializationFailureUnsupportedProfile}
}

// requestedStyle resolves the output style (materialization.rs).
func requestedStyle(request document.MaterializationRequest, profile JsonProfile) (jsonStyle, *MaterializationFailure) {
	style := request.Style()
	switch {
	case (profile == JsonProfileStrictV1 || profile == JsonProfileJsoncBoundedV1) &&
		style.ID() == "json.canonical-compact" && style.Version() == 1:
		return jsonStyleCompact, nil
	case (profile == JsonProfileStrictV1 || profile == JsonProfileJsoncBoundedV1) &&
		style.ID() == "json.canonical-pretty" && style.Version() == 1:
		return jsonStylePretty, nil
	case profile == JsonProfileJson5StandardV1 &&
		style.ID() == "json5.canonical-compact" && style.Version() == 1:
		return jsonStyleJson5Compact, nil
	case profile == JsonProfileJson5StandardV1 &&
		style.ID() == "json5.canonical-pretty" && style.Version() == 1:
		return jsonStyleJson5Pretty, nil
	}
	return jsonStyleCompact, &MaterializationFailure{Kind: MaterializationFailureUnsupportedStyle}
}

// parseLimitsFor derives the reparse limits from the materialization
// budgets (materialization.rs).
func parseLimitsFor(limits document.MaterializationLimits) document.ParseLimits {
	return document.ParseLimits{
		MaxSourceBytes:  limits.MaxOutputBytes,
		MaxNestingDepth: limits.MaxDepth,
		MaxTokenCount:   limits.MaxOutputBytes,
		MaxNodeCount:    limits.MaxInputNodes * 3,
		MaxDiagnostics:  limits.MaxReportEntries,
	}
}

// jsonWriter is the bounded deterministic writer.
type jsonWriter struct {
	style    jsonStyle
	newline  document.NewlinePolicy
	limits   document.MaterializationLimits
	input    int
	output   boundedOutput
	analyzed *[]protocol.ValuePath
}

func newJSONWriter(style jsonStyle, newline document.NewlinePolicy,
	limits document.MaterializationLimits, analyzed *[]protocol.ValuePath) *jsonWriter {
	return &jsonWriter{
		style:    style,
		newline:  newline,
		limits:   limits,
		output:   boundedOutput{max: limits.MaxOutputBytes},
		analyzed: analyzed,
	}
}

// value writes one value (materialization.rs).
func (w *jsonWriter) value(value core.Value, path protocol.ValuePath,
	depth int) *MaterializationFailure {
	if failure := w.analyze(path, depth); failure != nil {
		return failure
	}
	switch value.Kind() {
	case core.KindNull:
		return w.output.pushBytes([]byte("null"))
	case core.KindBoolean:
		if value.(core.Boolean) {
			return w.output.pushBytes([]byte("true"))
		}
		return w.output.pushBytes([]byte("false"))
	case core.KindInteger:
		return w.output.pushBytes([]byte(value.(core.Integer).String()))
	case core.KindDecimal:
		decimal := value.(core.Decimal)
		return w.output.pushBytes([]byte(decimal.Coefficient().String() + "e" + decimal.Exponent().String()))
	case core.KindBinaryFloat64:
		if !w.style.isJSON5() {
			return &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
				Path: path, ValueKind: core.KindBinaryFloat64}
		}
		return w.writeBinaryFloat64(value.(core.BinaryFloat64), path)
	case core.KindString:
		return w.writeString(string(value.(core.String)), path)
	case core.KindArray:
		return w.writeSequence(value.(*core.Array).Items(), path, depth)
	case core.KindObject:
		return w.writeObject(value.(*core.Object).Entries(), path, depth)
	case core.KindEntryMapping:
		return w.writeEntryMapping(value.(*core.EntryMapping).Entries(), path, depth)
	}
	return &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
		Path: path, ValueKind: value.Kind()}
}

// writeString writes one escaped string (materialization.rs).
func (w *jsonWriter) writeString(value string, path protocol.ValuePath) *MaterializationFailure {
	if failure := w.output.pushByte('"'); failure != nil {
		return failure
	}
	for _, character := range value {
		switch character {
		case '"':
			if failure := w.output.pushBytes([]byte(`\"`)); failure != nil {
				return failure
			}
		case '\\':
			if failure := w.output.pushBytes([]byte(`\\`)); failure != nil {
				return failure
			}
		case '\b':
			if failure := w.output.pushBytes([]byte(`\b`)); failure != nil {
				return failure
			}
		case '\f':
			if failure := w.output.pushBytes([]byte(`\f`)); failure != nil {
				return failure
			}
		case '\n':
			if failure := w.output.pushBytes([]byte(`\n`)); failure != nil {
				return failure
			}
		case '\r':
			if failure := w.output.pushBytes([]byte(`\r`)); failure != nil {
				return failure
			}
		case '\t':
			if failure := w.output.pushBytes([]byte(`\t`)); failure != nil {
				return failure
			}
		default:
			if character <= '\u001f' {
				if failure := w.output.pushBytes([]byte(escapeLowerHex(character))); failure != nil {
					return failure
				}
			} else if (character == '\u2028' || character == '\u2029') && w.style.isJSON5() {
				if failure := w.output.pushBytes([]byte(escapeLowerHex(character))); failure != nil {
					return failure
				}
			} else {
				if failure := w.output.pushRune(character); failure != nil {
					return failure
				}
			}
		}
	}
	return w.output.pushByte('"')
}

// escapeLowerHex renders one \u00xx escape with lowercase hex digits
// (the materialization writer spelling).
func escapeLowerHex(character rune) string {
	const digits = "0123456789abcdef"
	value := uint32(character)
	return "\\u" + string([]byte{
		digits[(value>>12)&0xf], digits[(value>>8)&0xf], digits[(value>>4)&0xf], digits[value&0xf],
	})
}

// writeBinaryFloat64 writes one frozen JSON5 non-finite literal
// (materialization.rs).
func (w *jsonWriter) writeBinaryFloat64(value core.BinaryFloat64, path protocol.ValuePath) *MaterializationFailure {
	var spelling []byte
	switch value.Bits() {
	case 0x7ff0_0000_0000_0000:
		spelling = []byte("Infinity")
	case 0xfff0_0000_0000_0000:
		spelling = []byte("-Infinity")
	case 0x7ff8_0000_0000_0000:
		spelling = []byte("NaN")
	case 0xfff8_0000_0000_0000:
		spelling = []byte("-NaN")
	default:
		return &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
			Path: path, ValueKind: core.KindBinaryFloat64}
	}
	return w.output.pushBytes(spelling)
}

// writeSequence writes one array (materialization.rs).
func (w *jsonWriter) writeSequence(values []core.Value, path protocol.ValuePath,
	depth int) *MaterializationFailure {
	if failure := w.output.pushByte('['); failure != nil {
		return failure
	}
	if len(values) > 0 && w.style.isPretty() {
		if failure := w.layoutNewline(depth + 1); failure != nil {
			return failure
		}
	}
	for index, item := range values {
		if index != 0 {
			if failure := w.output.pushByte(','); failure != nil {
				return failure
			}
			if w.style.isPretty() {
				if failure := w.layoutNewline(depth + 1); failure != nil {
					return failure
				}
			}
		}
		if failure := w.value(item,
			path.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)}),
			depth+1); failure != nil {
			return failure
		}
	}
	if len(values) > 0 && w.style.isPretty() {
		if failure := w.layoutNewline(depth); failure != nil {
			return failure
		}
	}
	return w.output.pushByte(']')
}

// writeObject writes one unique-key object (materialization.rs).
func (w *jsonWriter) writeObject(entries []core.Entry, path protocol.ValuePath,
	depth int) *MaterializationFailure {
	if failure := w.output.pushByte('{'); failure != nil {
		return failure
	}
	if len(entries) > 0 && w.style.isPretty() {
		if failure := w.layoutNewline(depth + 1); failure != nil {
			return failure
		}
	}
	for index, entry := range entries {
		if failure := w.memberSeparator(index, depth); failure != nil {
			return failure
		}
		if failure := w.writeString(entry.Key, path); failure != nil {
			return failure
		}
		if failure := w.output.pushByte(':'); failure != nil {
			return failure
		}
		if w.style.isPretty() {
			if failure := w.output.pushByte(' '); failure != nil {
				return failure
			}
		}
		if failure := w.value(entry.Value,
			path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: entry.Key}),
			depth+1); failure != nil {
			return failure
		}
	}
	if len(entries) > 0 && w.style.isPretty() {
		if failure := w.layoutNewline(depth); failure != nil {
			return failure
		}
	}
	return w.output.pushByte('}')
}

// writeEntryMapping writes one ordered mapping (materialization.rs).
func (w *jsonWriter) writeEntryMapping(entries []core.EntryMappingEntry, path protocol.ValuePath,
	depth int) *MaterializationFailure {
	if failure := w.output.pushByte('{'); failure != nil {
		return failure
	}
	if len(entries) > 0 && w.style.isPretty() {
		if failure := w.layoutNewline(depth + 1); failure != nil {
			return failure
		}
	}
	for index, entry := range entries {
		if failure := w.memberSeparator(index, depth); failure != nil {
			return failure
		}
		keyPath := path.Child(protocol.ValuePathSegment{Kind: "EntryKey", Index: uint64(index)})
		if failure := w.analyze(keyPath, depth+1); failure != nil {
			return failure
		}
		key, ok := entry.Key.(core.String)
		if !ok {
			return &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
				Path: keyPath, ValueKind: entry.Key.Kind()}
		}
		if failure := w.writeString(string(key), keyPath); failure != nil {
			return failure
		}
		if failure := w.output.pushByte(':'); failure != nil {
			return failure
		}
		if w.style.isPretty() {
			if failure := w.output.pushByte(' '); failure != nil {
				return failure
			}
		}
		if failure := w.value(entry.Value,
			path.Child(protocol.ValuePathSegment{Kind: "EntryValue", Index: uint64(index)}),
			depth+1); failure != nil {
			return failure
		}
	}
	if len(entries) > 0 && w.style.isPretty() {
		if failure := w.layoutNewline(depth); failure != nil {
			return failure
		}
	}
	return w.output.pushByte('}')
}

// analyze applies the input node and depth budgets
// (materialization.rs).
func (w *jsonWriter) analyze(path protocol.ValuePath, depth int) *MaterializationFailure {
	if depth > w.limits.MaxDepth {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
			LimitName: "input-depth"}
	}
	w.input++
	if w.input > w.limits.MaxInputNodes {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
			LimitName: "input-nodes"}
	}
	*w.analyzed = append(*w.analyzed, path)
	return nil
}

// memberSeparator writes the comma and layout before one member.
func (w *jsonWriter) memberSeparator(index, depth int) *MaterializationFailure {
	if index == 0 {
		return nil
	}
	if failure := w.output.pushByte(','); failure != nil {
		return failure
	}
	if w.style.isPretty() {
		return w.layoutNewline(depth + 1)
	}
	return nil
}

// layoutNewline writes the newline and indentation
// (materialization.rs).
func (w *jsonWriter) layoutNewline(depth int) *MaterializationFailure {
	if failure := w.output.pushBytes(w.newline.Bytes()); failure != nil {
		return failure
	}
	for count := 0; count < depth; count++ {
		if failure := w.output.pushBytes([]byte("  ")); failure != nil {
			return failure
		}
	}
	return nil
}

// boundedOutput is the byte-budgeted output buffer
// (materialization.rs).
type boundedOutput struct {
	bytes []byte
	max   int
}

func (o *boundedOutput) pushByte(octet byte) *MaterializationFailure {
	return o.pushBytes([]byte{octet})
}

func (o *boundedOutput) pushRune(character rune) *MaterializationFailure {
	var encoded [4]byte
	width := runeWidth(character, encoded[:])
	return o.pushBytes(encoded[:width])
}

func (o *boundedOutput) pushBytes(bytes []byte) *MaterializationFailure {
	newLength := len(o.bytes) + len(bytes)
	if newLength < len(o.bytes) || newLength > o.max {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
			LimitName: "output-bytes"}
	}
	o.bytes = append(o.bytes, bytes...)
	return nil
}

func (o *boundedOutput) finish() []byte { return o.bytes }

// runeWidth encodes one scalar and returns its UTF-8 width.
func runeWidth(character rune, buffer []byte) int {
	switch {
	case character < 0x80:
		buffer[0] = byte(character)
		return 1
	case character < 0x800:
		buffer[0] = 0xc0 | byte(character>>6)
		buffer[1] = 0x80 | byte(character&0x3f)
		return 2
	case character < 0x10000:
		buffer[0] = 0xe0 | byte(character>>12)
		buffer[1] = 0x80 | byte((character>>6)&0x3f)
		buffer[2] = 0x80 | byte(character&0x3f)
		return 3
	default:
		buffer[0] = 0xf0 | byte(character>>18)
		buffer[1] = 0x80 | byte((character>>12)&0x3f)
		buffer[2] = 0x80 | byte((character>>6)&0x3f)
		buffer[3] = 0x80 | byte(character&0x3f)
		return 4
	}
}

// provenanceBuilder collects the input-to-output provenance facts
// (materialization.rs).
type provenanceBuilder struct {
	document *Document
	limits   document.MaterializationLimits
	units    int
	entries  []MaterializationProvenanceEntry
}

// collect walks one input value against its output value.
func (b *provenanceBuilder) collect(input core.Value, path protocol.ValuePath,
	output JsonValue) *MaterializationFailure {
	var expected JsonValueKind
	switch input.Kind() {
	case core.KindNull:
		expected = JsonValueKindNull
	case core.KindBoolean:
		expected = JsonValueKindBoolean
	case core.KindInteger:
		expected = JsonValueKindInteger
	case core.KindDecimal:
		expected = JsonValueKindDecimal
	case core.KindBinaryFloat64:
		expected = JsonValueKindBinaryFloat64
	case core.KindString:
		expected = JsonValueKindString
	case core.KindArray:
		expected = JsonValueKindArray
	case core.KindObject, core.KindEntryMapping:
		expected = JsonValueKindObject
	default:
		return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	availability := output.Kind()
	if !availability.IsAvailable() || availability.Value() != expected {
		return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	if input.Kind() == core.KindBinaryFloat64 {
		outputBits := output.AsBinaryFloat64()
		if !outputBits.IsAvailable() || *outputBits.Value() != input.(core.BinaryFloat64) {
			return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
	}
	if failure := b.pushOrigin(MaterializationInputLocation{Path: path},
		b.origin(output.NodeRef(), output.Span(), MaterializationRelationDirect)); failure != nil {
		return failure
	}
	switch input.Kind() {
	case core.KindArray:
		values := input.(*core.Array).Items()
		elements := output.ArrayElements()
		if !elements.IsAvailable() || len(elements.Value()) != len(values) {
			return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		elementValues := elements.Value()
		for index, item := range values {
			childPath := path.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
			if failure := b.collect(item, childPath, elementValues[index].Value()); failure != nil {
				return failure
			}
			if failure := b.addOutput(&MaterializationInputLocation{Path: childPath},
				b.origin(elementValues[index].NodeRef(), elementValues[index].Span(),
					MaterializationRelationGenerated)); failure != nil {
				return failure
			}
		}
	case core.KindObject:
		entries := input.(*core.Object).Entries()
		members, failure := availableMembers(output)
		if failure != nil {
			return failure
		}
		if len(entries) != len(members) {
			return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		for index, entry := range entries {
			member := members[index]
			name := member.Name()
			if !name.IsAvailable() || *name.Value() != entry.Key {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
			ordinal := uint64(index)
			if failure := b.pushOrigin(MaterializationInputLocation{
				IsAssociation: true,
				Association: protocol.NewAssociationLocation(path, ordinal,
					protocol.AssociationRoleObjectEntry),
			}, b.origin(member.NodeRef(), member.Span(), MaterializationRelationDirect)); failure != nil {
				return failure
			}
			keyEntity := b.document.entity(member.index).member
			keySpan := b.document.span(keyEntity.key)
			if failure := b.pushOrigin(MaterializationInputLocation{
				IsAssociation: true,
				Association: protocol.NewAssociationLocation(path, ordinal,
					protocol.AssociationRoleObjectKey),
			}, b.origin(member.KeyNodeRef(), keySpan, MaterializationRelationDirect)); failure != nil {
				return failure
			}
			if failure := b.collect(entry.Value,
				path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: entry.Key}),
				member.Value()); failure != nil {
				return failure
			}
		}
	case core.KindEntryMapping:
		entries := input.(*core.EntryMapping).Entries()
		members, failure := availableMembers(output)
		if failure != nil {
			return failure
		}
		if len(entries) != len(members) {
			return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		for index, entry := range entries {
			member := members[index]
			key, ok := entry.Key.(core.String)
			if !ok {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
			name := member.Name()
			if !name.IsAvailable() || *name.Value() != string(key) {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
			ordinal := uint64(index)
			if failure := b.pushOrigin(MaterializationInputLocation{
				IsAssociation: true,
				Association: protocol.NewAssociationLocation(path, ordinal,
					protocol.AssociationRoleEntryMappingItem),
			}, b.origin(member.NodeRef(), member.Span(), MaterializationRelationDirect)); failure != nil {
				return failure
			}
			keyPath := path.Child(protocol.ValuePathSegment{Kind: "EntryKey", Index: ordinal})
			keyEntity := b.document.entity(member.index).member
			keySpan := b.document.span(keyEntity.key)
			if failure := b.pushOrigin(MaterializationInputLocation{Path: keyPath},
				b.origin(member.KeyNodeRef(), keySpan, MaterializationRelationReencoded)); failure != nil {
				return failure
			}
			if failure := b.collect(entry.Value,
				path.Child(protocol.ValuePathSegment{Kind: "EntryValue", Index: ordinal}),
				member.Value()); failure != nil {
				return failure
			}
		}
	}
	return nil
}

// availableMembers resolves the output members of an object value.
func availableMembers(output JsonValue) ([]JsonObjectMember, *MaterializationFailure) {
	members := output.ObjectMembers()
	if !members.IsAvailable() {
		return nil, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	return members.Value(), nil
}

// origin builds one output origin.
func (b *provenanceBuilder) origin(node document.NodeRef, span document.Span,
	relation MaterializationRelation) MaterializedOrigin {
	return MaterializedOrigin{
		Snapshot: b.document.SnapshotIdentity(),
		Node:     node,
		Span:     span,
		Relation: relation,
	}
}

// pushOrigin records one new input-to-output mapping; every origin costs
// two provenance units (materialization.rs).
func (b *provenanceBuilder) pushOrigin(input MaterializationInputLocation,
	output MaterializedOrigin) *MaterializationFailure {
	b.units += 2
	if b.units > b.limits.MaxProvenanceEntries {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
			LimitName: "provenance-entries"}
	}
	b.entries = append(b.entries, MaterializationProvenanceEntry{
		Input:   input,
		Outputs: []MaterializedOrigin{output},
	})
	return nil
}

// addOutput appends one output origin to an existing mapping
// (materialization.rs).
func (b *provenanceBuilder) addOutput(input *MaterializationInputLocation,
	output MaterializedOrigin) *MaterializationFailure {
	b.units++
	if b.units > b.limits.MaxProvenanceEntries {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
			LimitName: "provenance-entries"}
	}
	for index := range b.entries {
		if b.entries[index].Input.Path.Equal(input.Path) && !b.entries[index].Input.IsAssociation {
			b.entries[index].Outputs = append(b.entries[index].Outputs, output)
			return nil
		}
	}
	return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
}

// contextBackground returns the background context for the internal
// reparse; the materialization surface is not cancellable.
func contextBackground() context.Context { return context.Background() }
