package plist

// This file implements the canonical `plist.xml-canonical@1` /
// `plist.binary-canonical@1` materialization (consema-plist
// materialization.rs; RFC 0013 §10). Materialization consumes one
// `plist.value-tree@1` record and creates a new `plist.xml@1` or
// `plist.binary@1` Document. It is not a formatter for an existing source:
// the input is the projected value tree, the output is a new snapshot whose
// complete native model equals the promised input semantics (RFC 0013
// §10.3).
//
// The record contract is the exact `plist.value-tree@1` record the
// projection publishes: an Object with `record`, `root`, and an optional
// `truncate_policy` member. Dict associations are ordered and duplicate
// keys are preserved; the numeric payloads are accepted as the exact binary
// float kinds (the projection emission) or as Decimal (the consema-json
// projection of the conformance vectors).
//
// Every style validates the complete input before proportional allocation,
// encodes, reparses the exact generated bytes under the promised Profile,
// and compares the reparsed native model to the promised input semantics.
// Failure returns no target Document, partial bytes, or partial provenance.

import (
	"math"
	"strconv"
	"strings"

	"consema.dev/consema/core"
	"consema.dev/consema/document"
	"consema.dev/consema/protocol"
)

// The frozen materialization style identifiers (RFC 0013 §10).
const (
	styleXML    = "plist.xml-canonical"
	styleBinary = "plist.binary-canonical"
)

// The versioned value-tree record name (RFC 0013 §9).
const valueTreeRecord = "plist.value-tree@1"

// The only admitted truncation policy (RFC 0013 §10.1).
const truncatePolicy = "TruncateWithReport"

// The stable truncation report/failure code (RFC 0013 §10.1, §12).
const fractionalDateCode = "plist.materialization.fractional-date@1"

// MaterializationStyle is the closed canonical style of one request.
type materializationStyle uint8

const (
	styleXMLValue materializationStyle = iota
	styleBinaryValue
)

// MaterializationFailureKind is the stable materialization failure
// category (consema-document materialization.rs).
type MaterializationFailureKind uint8

// The closed materialization failure categories.
const (
	// MaterializationFailureInvalidRequest: request fields are
	// contradictory.
	MaterializationFailureInvalidRequest MaterializationFailureKind = iota
	// MaterializationFailureUnsupportedProfile: the target profile is
	// unavailable.
	MaterializationFailureUnsupportedProfile
	// MaterializationFailureUnsupportedStyle: the target style is
	// unavailable for the profile.
	MaterializationFailureUnsupportedStyle
	// MaterializationFailureUnsupportedEncoding: the target encoding is
	// unsupported.
	MaterializationFailureUnsupportedEncoding
	// MaterializationFailureUnsupportedNewline: the target style does not
	// support the newline policy.
	MaterializationFailureUnsupportedNewline
	// MaterializationFailureUnrepresentable: a portable input cannot be
	// represented by the target profile.
	MaterializationFailureUnrepresentable
	// MaterializationFailureResourceLimit: a configured bound was reached;
	// output is not truncated to success.
	MaterializationFailureResourceLimit
	// MaterializationFailureFormationFailed: the generated bytes did not
	// form the required target document.
	MaterializationFailureFormationFailed
)

// MaterializationFailure is the typed materialization failure. It
// implements error and the RFC 0016 §6 Code() contract.
type MaterializationFailure struct {
	// Kind identifies the failure.
	Kind MaterializationFailureKind
	// Path is the offending input location of Unrepresentable.
	Path protocol.ValuePath
	// ValueKind is the offending PortableValue kind of Unrepresentable.
	ValueKind core.Kind
	// LimitName is the stable limit name of a ResourceLimit.
	LimitName string
}

// Error implements error.
func (e *MaterializationFailure) Error() string {
	switch e.Kind {
	case MaterializationFailureInvalidRequest:
		return "plist: materialization request fields are contradictory"
	case MaterializationFailureUnsupportedProfile:
		return "plist: materialization profile is unavailable"
	case MaterializationFailureUnsupportedStyle:
		return "plist: materialization style is unavailable for the profile"
	case MaterializationFailureUnsupportedEncoding:
		return "plist: materialization encoding is unsupported"
	case MaterializationFailureUnsupportedNewline:
		return "plist: materialization newline policy is unsupported by the style"
	case MaterializationFailureUnrepresentable:
		return "plist: portable kind " + e.ValueKind.String() + " is not representable"
	case MaterializationFailureResourceLimit:
		return "plist: materialization limit " + e.LimitName + " reached"
	case MaterializationFailureFormationFailed:
		return "plist: generated bytes did not form the target document"
	}
	return "plist: materialization failure"
}

// Code returns the frozen registered code for the failure. The plist suite
// maps a Date-kind Unrepresentable to the plist fractional-date code and
// every other plist-materialization failure to its plist code (RFC 0013
// §10); the shared request/formation failures carry the shared
// core.materialization codes.
func (e *MaterializationFailure) Code() string {
	switch e.Kind {
	case MaterializationFailureUnrepresentable:
		if e.ValueKind == core.KindDate {
			return fractionalDateCode
		}
		return "plist.materialization.unrepresentable@1"
	case MaterializationFailureResourceLimit:
		return "plist.materialization.resource-limit@1"
	case MaterializationFailureInvalidRequest:
		return "core.materialization.invalid-request@1"
	case MaterializationFailureUnsupportedProfile:
		return "core.materialization.unsupported-profile@1"
	case MaterializationFailureUnsupportedStyle:
		return "core.materialization.unsupported-style@1"
	case MaterializationFailureUnsupportedEncoding:
		return "core.materialization.unsupported-encoding@1"
	case MaterializationFailureUnsupportedNewline:
		return "core.materialization.unsupported-newline@1"
	case MaterializationFailureFormationFailed:
		return "core.materialization.formation-failed@1"
	}
	return "core.materialization.formation-failed@1"
}

// MaterializationFidelity is the closed materialization fidelity
// (consema-document materialization.rs).
type MaterializationFidelity uint8

// The two frozen fidelity classes.
const (
	// MaterializationFidelityExact: every input fact round-trips through
	// the target's exact projection contract.
	MaterializationFidelityExact MaterializationFidelity = iota
	// MaterializationFidelityTransformed: complete semantics survive an
	// explicit reversible re-encoding.
	MaterializationFidelityTransformed
)

// String returns the stable fidelity name.
func (f MaterializationFidelity) String() string {
	switch f {
	case MaterializationFidelityExact:
		return "Exact"
	case MaterializationFidelityTransformed:
		return "Transformed"
	}
	return "Exact"
}

// MaterializationReport is the complete materialization report; the plist
// report carries the authorized fractional-date truncation events.
type MaterializationReport struct {
	events []*protocol.Diagnostic
}

// Events returns the ordered report events. The returned slice is a copy.
func (r *MaterializationReport) Events() []*protocol.Diagnostic {
	return append([]*protocol.Diagnostic(nil), r.events...)
}

// CompleteMaterialization is the complete successful materialization.
type CompleteMaterialization struct {
	// Document is the new immutable target document.
	Document *Document
	// Fidelity is the worst fidelity of the whole operation.
	Fidelity MaterializationFidelity
	// Report is the transformation/loss report.
	Report MaterializationReport
}

// FailedMaterializationAttempt is a failed attempt without a document.
type FailedMaterializationAttempt struct {
	// Failure is the stable failure.
	Failure *MaterializationFailure
	// Report holds the events discovered before the failed completion
	// check.
	Report MaterializationReport
	// AnalyzedInputPaths are the stable path descriptions of locally
	// analyzed input regions.
	AnalyzedInputPaths []protocol.ValuePath
}

// MaterializationResult is the sealed materialization outcome: exactly one
// of Complete or Failed is set.
type MaterializationResult struct {
	// Complete is the successful outcome.
	Complete *CompleteMaterialization
	// Failed is the failed attempt.
	Failed *FailedMaterializationAttempt
}

// Materialize materializes one complete `plist.value-tree@1` record into a
// new canonical plist document (RFC 0013 §10).
func Materialize(value core.Value, request document.MaterializationRequest) MaterializationResult {
	analyzed := make([]protocol.ValuePath, 0, 16)
	complete, failure := materializeComplete(value, request, &analyzed)
	if failure != nil {
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure: failure, Report: MaterializationReport{},
			AnalyzedInputPaths: analyzed,
		}}
	}
	return MaterializationResult{Complete: complete}
}

// materializeComplete runs the two-phase materialization
// (materialization.rs:193-233).
func materializeComplete(value core.Value, request document.MaterializationRequest,
	analyzed *[]protocol.ValuePath) (*CompleteMaterialization, *MaterializationFailure) {
	style, failure := validateRequest(request)
	if failure != nil {
		return nil, failure
	}
	limits := request.Limits()
	record, failure := validateRecord(value, request, analyzed)
	if failure != nil {
		return nil, failure
	}
	native, events, transformed, failure := buildNative(record, style, request)
	if failure != nil {
		return nil, failure
	}
	var bytes []byte
	switch style {
	case styleXMLValue:
		bytes, failure = serializeXMLRecord(record, limits)
	case styleBinaryValue:
		bytes, failure = serializeBinaryRecord(record, limits)
	}
	if failure != nil {
		return nil, failure
	}
	var target *Document
	var formationFailure *FormationFailure
	if style == styleXMLValue {
		target, formationFailure = parseXML(bytes, parseLimitsFor(limits))
	} else {
		target, formationFailure = parseBinary(bytes, parseLimitsFor(limits))
	}
	if formationFailure != nil {
		return nil, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	if target.status != document.FormationStatusComplete {
		return nil, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	if !target.native.Equal(native) {
		return nil, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	fidelity := MaterializationFidelityExact
	if transformed {
		fidelity = MaterializationFidelityTransformed
	}
	return &CompleteMaterialization{
		Document: target, Fidelity: fidelity,
		Report: MaterializationReport{events: events},
	}, nil
}

// validateRequest validates the request against the frozen style contracts
// (RFC 0013 §10).
func validateRequest(request document.MaterializationRequest) (materializationStyle, *MaterializationFailure) {
	profile := request.TargetProfile()
	styleID := request.Style()
	selected := materializationStyle(0)
	switch {
	case profile.ID() == "plist.xml" && profile.Version() == 1 &&
		styleID.ID() == styleXML && styleID.Version() == 1:
		selected = styleXMLValue
	case profile.ID() == "plist.binary" && profile.Version() == 1 &&
		styleID.ID() == styleBinary && styleID.Version() == 1:
		selected = styleBinaryValue
	case profile.ID() != "plist.xml" && profile.ID() != "plist.binary":
		return 0, &MaterializationFailure{Kind: MaterializationFailureUnsupportedProfile}
	default:
		return 0, &MaterializationFailure{Kind: MaterializationFailureUnsupportedStyle}
	}
	switch selected {
	case styleXMLValue:
		if !request.Encoding().Equal(document.Utf8Encoding()) {
			return 0, &MaterializationFailure{Kind: MaterializationFailureUnsupportedEncoding}
		}
		if request.Newline() != document.NewlineLf {
			return 0, &MaterializationFailure{Kind: MaterializationFailureUnsupportedNewline}
		}
	case styleBinaryValue:
		if !request.Encoding().Equal(document.BinaryEncoding()) {
			return 0, &MaterializationFailure{Kind: MaterializationFailureUnsupportedEncoding}
		}
		if request.Newline() != document.NewlineNone {
			return 0, &MaterializationFailure{Kind: MaterializationFailureUnsupportedNewline}
		}
	}
	return selected, nil
}

// parseLimitsFor derives the closure reparse limits from the request so a
// bounded input cannot fail its own closure (materialization.rs:274-304).
func parseLimitsFor(limits document.MaterializationLimits) PlistParseLimits {
	base := DefaultPlistParseLimits()
	base.Common = document.ParseLimits{
		MaxSourceBytes:  limits.MaxOutputBytes,
		MaxNestingDepth: limits.MaxDepth + 2,
		MaxTokenCount:   limits.MaxOutputBytes,
		MaxNodeCount:    limits.MaxInputNodes,
		MaxDiagnostics:  limits.MaxReportEntries,
	}
	base.MaxDecodedUTF8Bytes = limits.MaxOutputBytes * 3
	base.MaxDecodedScalars = limits.MaxOutputBytes
	base.MaxObjectCount = limits.MaxInputNodes * 2
	base.MaxContainerDepth = limits.MaxDepth
	base.MaxDictEntries = limits.MaxInputNodes
	base.MaxArrayElements = limits.MaxInputNodes
	base.MaxDuplicateKeyGroupMembers = limits.MaxInputNodes
	base.MaxStringCodeUnits = limits.MaxOutputBytes
	base.MaxDataBytes = limits.MaxOutputBytes
	base.MaxUIDCount = limits.MaxInputNodes
	base.MaxExtendedSizeIntegers = limits.MaxInputNodes * 2
	base.MaxExtendedSizeValue = limits.MaxInputNodes
	base.MaxOffsetTableBytes = limits.MaxOutputBytes * 8
	base.MaxSyntaxPieces = limits.MaxOutputBytes
	base.MaxBinaryFacts = limits.MaxOutputBytes * 16
	base.MaxConversionNodes = limits.MaxInputNodes
	base.MaxReportEvents = limits.MaxReportEntries
	base.MaxRecoveryRegions = limits.MaxReportEntries
	return base
}

// materializationValueKind is one validated value kind of the record.
type materializationValueKind uint8

// The closed validated value kinds.
const (
	valueKindDict materializationValueKind = iota
	valueKindArray
	valueKindString
	valueKindInteger
	valueKindReal
	valueKindBoolean
	valueKindDate
	valueKindData
	valueKindUID
)

// materializationValueNode is one validated value record with its input
// path.
type materializationValueNode struct {
	path protocol.ValuePath
	kind materializationValueKind
	// Dict.
	dictEntries []materializationDictEntry
	// Array.
	elements []materializationValueNode
	// String.
	str PlistString
	// Integer.
	integer int64
	// Real.
	real PlistReal
	// Boolean.
	boolean bool
	// Date: seconds, possibly truncated by an authorized policy.
	seconds float64
	// Data.
	bytes []byte
	// UID.
	uid uint32
}

// materializationDictEntry is one validated dictionary association.
type materializationDictEntry struct {
	key     PlistString
	keyPath protocol.ValuePath
	value   materializationValueNode
}

// materializationRecord is one validated `plist.value-tree@1` record.
type materializationRecord struct {
	root   materializationValueNode
	policy bool
}

// validateRecord validates the record shape, the truncation policy, the
// value tree, the input node budget, and the container depth budget
// (materialization.rs:389-436).
func validateRecord(value core.Value, request document.MaterializationRequest,
	analyzed *[]protocol.ValuePath) (*materializationRecord, *MaterializationFailure) {
	*analyzed = append(*analyzed, protocol.RootValuePath())
	limits := request.Limits()
	object, ok := value.(*core.Object)
	if !ok {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest}
	}
	recordField, ok := objectField(object, "record")
	if !ok {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest}
	}
	recordText, ok := recordField.(core.String)
	if !ok || string(recordText) != valueTreeRecord {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest}
	}
	policy := false
	if policyField, exists := objectField(object, "truncate_policy"); exists {
		policyText, ok := policyField.(core.String)
		if !ok {
			return nil, &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
				ValueKind: policyField.Kind()}
		}
		if string(policyText) != truncatePolicy {
			return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest}
		}
		policy = true
	}
	rootField, ok := objectField(object, "root")
	if !ok {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest}
	}
	rootPath := protocol.RootValuePath().Child(protocol.ValuePathSegment{
		Kind: "ObjectValue", Key: "root"})
	validator := &materializationValidator{nodes: 0, limits: limits}
	root, failure := validateValue(rootField, rootPath, validator, analyzed, 0)
	if failure != nil {
		return nil, failure
	}
	return &materializationRecord{root: root, policy: policy}, nil
}

// materializationValidator is the input node budget and depth accounting
// during validation.
type materializationValidator struct {
	nodes  int
	limits document.MaterializationLimits
}

func (v *materializationValidator) step() *MaterializationFailure {
	v.nodes++
	if v.nodes > v.limits.MaxInputNodes {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
			LimitName: "input-nodes"}
	}
	return nil
}

// validateValue validates one value of the `plist.value-tree@1` record and
// its descendants (RFC 0013 §9; materialization.rs:438-655).
func validateValue(value core.Value, path protocol.ValuePath,
	validator *materializationValidator, analyzed *[]protocol.ValuePath,
	depth int) (materializationValueNode, *MaterializationFailure) {
	if failure := validator.step(); failure != nil {
		return materializationValueNode{}, failure
	}
	*analyzed = append(*analyzed, path)
	maxOutputBytes := validator.limits.MaxOutputBytes
	if entries, ok := value.(*core.EntryMapping); ok {
		// Ordered dictionary associations (RFC 0013 §9); the projection
		// emission keeps duplicate keys and association order.
		if depth+1 > validator.limits.MaxDepth {
			return materializationValueNode{}, &MaterializationFailure{
				Kind: MaterializationFailureResourceLimit, LimitName: "input-depth"}
		}
		dictEntries := make([]materializationDictEntry, 0, entries.Len())
		for ordinal, entry := range entries.Entries() {
			keyText, ok := entry.Key.(core.String)
			if !ok {
				keyPath := path.Child(protocol.ValuePathSegment{Kind: "EntryKey", Index: uint64(ordinal)})
				return materializationValueNode{}, &MaterializationFailure{
					Kind: MaterializationFailureUnrepresentable, Path: keyPath,
					ValueKind: entry.Key.Kind()}
			}
			keyPath := path.Child(protocol.ValuePathSegment{Kind: "EntryKey", Index: uint64(ordinal)})
			valuePath := path.Child(protocol.ValuePathSegment{Kind: "EntryValue", Index: uint64(ordinal)})
			valueNode, failure := validateValue(entry.Value, valuePath, validator, analyzed, depth+1)
			if failure != nil {
				return materializationValueNode{}, failure
			}
			dictEntries = append(dictEntries, materializationDictEntry{
				key: NewPlistStringFromUnicode(string(keyText)), keyPath: keyPath,
				value: valueNode,
			})
		}
		return materializationValueNode{path: path, kind: valueKindDict, dictEntries: dictEntries}, nil
	}
	if array, ok := value.(*core.Array); ok {
		// Ordered array elements (RFC 0013 §9).
		if depth+1 > validator.limits.MaxDepth {
			return materializationValueNode{}, &MaterializationFailure{
				Kind: MaterializationFailureResourceLimit, LimitName: "input-depth"}
		}
		elements := make([]materializationValueNode, 0, array.Len())
		for index, element := range array.Items() {
			elementPath := path.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
			elementNode, failure := validateValue(element, elementPath, validator, analyzed, depth+1)
			if failure != nil {
				return materializationValueNode{}, failure
			}
			elements = append(elements, elementNode)
		}
		return materializationValueNode{path: path, kind: valueKindArray, elements: elements}, nil
	}
	if text, ok := value.(core.String); ok {
		if len(text) > maxOutputBytes {
			return materializationValueNode{}, &MaterializationFailure{
				Kind: MaterializationFailureResourceLimit, LimitName: "output-bytes"}
		}
		return materializationValueNode{path: path, kind: valueKindString,
			str: NewPlistStringFromUnicode(string(text))}, nil
	}
	if integer, ok := value.(core.Integer); ok {
		number := integer.Int()
		if !number.IsInt64() {
			return materializationValueNode{}, &MaterializationFailure{
				Kind: MaterializationFailureUnrepresentable, Path: path,
				ValueKind: core.KindInteger}
		}
		return materializationValueNode{path: path, kind: valueKindInteger,
			integer: number.Int64()}, nil
	}
	if bits, ok := value.(core.BinaryFloat32); ok {
		return materializationValueNode{path: path, kind: valueKindReal,
			real: NewPlistRealSingle(float32FromBits32(uint32(bits)))}, nil
	}
	if bits, ok := value.(core.BinaryFloat64); ok {
		return materializationValueNode{path: path, kind: valueKindReal,
			real: NewPlistRealDouble(float64FromBits(uint64(bits)))}, nil
	}
	if decimal, ok := value.(core.Decimal); ok {
		converted, ok := decimalToFloat64(&decimal)
		if !ok {
			return materializationValueNode{}, &MaterializationFailure{
				Kind: MaterializationFailureUnrepresentable, Path: path,
				ValueKind: core.KindDecimal}
		}
		return materializationValueNode{path: path, kind: valueKindReal,
			real: NewPlistRealDouble(converted)}, nil
	}
	if boolean, ok := value.(core.Boolean); ok {
		return materializationValueNode{path: path, kind: valueKindBoolean,
			boolean: bool(boolean)}, nil
	}
	if bytes, ok := value.(core.Bytes); ok {
		if len(bytes) > maxOutputBytes {
			return materializationValueNode{}, &MaterializationFailure{
				Kind: MaterializationFailureResourceLimit, LimitName: "output-bytes"}
		}
		return materializationValueNode{path: path, kind: valueKindData,
			bytes: append([]byte(nil), bytes...)}, nil
	}
	if object, ok := value.(*core.Object); ok {
		// The JSON vector spelling maps containers and leaf records to
		// Objects; the member set dispatches them.
		if _, hasKind := objectField(object, "kind"); hasKind {
			// The explicit `{kind, ...}` record spelling is not the
			// `plist.value-tree@1` record (RFC 0013 §9).
			return materializationValueNode{}, &MaterializationFailure{
				Kind: MaterializationFailureUnrepresentable, Path: path,
				ValueKind: core.KindObject}
		}
		if epoch, hasEpoch := objectField(object, "epoch"); hasEpoch {
			secondsField, hasSeconds := objectField(object, "seconds")
			if !hasSeconds {
				return materializationValueNode{}, &MaterializationFailure{
					Kind: MaterializationFailureInvalidRequest}
			}
			epochText, ok := epoch.(core.String)
			if !ok || string(epochText) != plistEpochSpelling {
				return materializationValueNode{}, &MaterializationFailure{
					Kind: MaterializationFailureInvalidRequest}
			}
			var seconds float64
			if bits, ok := secondsField.(core.BinaryFloat64); ok {
				seconds = float64FromBits(uint64(bits))
			} else if decimal, ok := secondsField.(core.Decimal); ok {
				converted, ok := decimalToFloat64(&decimal)
				if !ok {
					return materializationValueNode{}, &MaterializationFailure{
						Kind: MaterializationFailureUnrepresentable, Path: path,
						ValueKind: core.KindDate}
				}
				seconds = converted
			} else {
				return materializationValueNode{}, &MaterializationFailure{
					Kind: MaterializationFailureUnrepresentable, Path: path,
					ValueKind: core.KindDate}
			}
			if !isFinite(seconds) {
				return materializationValueNode{}, &MaterializationFailure{
					Kind: MaterializationFailureUnrepresentable, Path: path,
					ValueKind: core.KindDate}
			}
			return materializationValueNode{path: path, kind: valueKindDate, seconds: seconds}, nil
		}
		if uidField, hasUID := objectField(object, "uid"); hasUID {
			integer, ok := uidField.(core.Integer)
			if !ok {
				uidPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "uid"})
				return materializationValueNode{}, &MaterializationFailure{
					Kind: MaterializationFailureUnrepresentable, Path: uidPath,
					ValueKind: uidField.Kind()}
			}
			number := integer.Int()
			if !number.IsInt64() || number.Sign() < 0 || number.Int64() > int64(^uint32(0)) {
				uidPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "uid"})
				return materializationValueNode{}, &MaterializationFailure{
					Kind: MaterializationFailureUnrepresentable, Path: uidPath,
					ValueKind: core.KindInteger}
			}
			return materializationValueNode{path: path, kind: valueKindUID,
				uid: uint32(number.Int64())}, nil
		}
		if hexField, hasHex := objectField(object, "hex"); hasHex {
			hexText, ok := hexField.(core.String)
			if !ok {
				hexPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "hex"})
				return materializationValueNode{}, &MaterializationFailure{
					Kind: MaterializationFailureUnrepresentable, Path: hexPath,
					ValueKind: hexField.Kind()}
			}
			if len(hexText)/2 > maxOutputBytes {
				return materializationValueNode{}, &MaterializationFailure{
					Kind: MaterializationFailureResourceLimit, LimitName: "output-bytes"}
			}
			bytes, ok := decodeHexText(string(hexText))
			if !ok {
				hexPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "hex"})
				return materializationValueNode{}, &MaterializationFailure{
					Kind: MaterializationFailureUnrepresentable, Path: hexPath,
					ValueKind: core.KindString}
			}
			return materializationValueNode{path: path, kind: valueKindData, bytes: bytes}, nil
		}
		// A dictionary spelled as an ordered JSON object.
		if depth+1 > validator.limits.MaxDepth {
			return materializationValueNode{}, &MaterializationFailure{
				Kind: MaterializationFailureResourceLimit, LimitName: "input-depth"}
		}
		dictEntries := make([]materializationDictEntry, 0, object.Len())
		for ordinal, entry := range object.Entries() {
			keyPath := path.Child(protocol.ValuePathSegment{Kind: "EntryKey", Index: uint64(ordinal)})
			valuePath := path.Child(protocol.ValuePathSegment{Kind: "EntryValue", Index: uint64(ordinal)})
			valueNode, failure := validateValue(entry.Value, valuePath, validator, analyzed, depth+1)
			if failure != nil {
				return materializationValueNode{}, failure
			}
			dictEntries = append(dictEntries, materializationDictEntry{
				key: NewPlistStringFromUnicode(entry.Key), keyPath: keyPath,
				value: valueNode,
			})
		}
		return materializationValueNode{path: path, kind: valueKindDict, dictEntries: dictEntries}, nil
	}
	return materializationValueNode{}, &MaterializationFailure{
		Kind: MaterializationFailureUnrepresentable, Path: path, ValueKind: value.Kind()}
}

// decimalToFloat64 converts one exact decimal to its double value; ok is
// false when the coefficient or exponent exceeds the exact i64 range (the
// decimal is then far outside double precision). The conversion
// intentionally rounds to the nearest double (RFC 0013 §6).
func decimalToFloat64(decimal *core.Decimal) (float64, bool) {
	coefficient := decimal.Coefficient()
	exponent := decimal.Exponent()
	if !coefficient.IsInt64() || !exponent.IsInt64() {
		return 0, false
	}
	coefficientValue := float64(coefficient.Int64())
	exponentValue := exponent.Int64()
	value := coefficientValue
	if exponentValue > 0 {
		power := exponentValue
		if power > 308 {
			power = 308
		}
		value *= math.Pow10(int(power))
	} else if exponentValue < 0 {
		power := -exponentValue
		if power > 308 {
			power = 308
		}
		value /= math.Pow10(int(power))
	}
	return value, true
}

// decodeHexText strictly decodes one even-length hex string (RFC 0013 §9
// data spelling).
func decodeHexText(text string) ([]byte, bool) {
	if len(text)%2 != 0 {
		return nil, false
	}
	bytes := make([]byte, 0, len(text)/2)
	for index := 0; index < len(text); index += 2 {
		high, okHigh := hexValue(text[index])
		low, okLow := hexValue(text[index+1])
		if !okHigh || !okLow {
			return nil, false
		}
		bytes = append(bytes, high<<4|low)
	}
	return bytes, true
}

func hexValue(byte byte) (byte, bool) {
	switch {
	case byte >= '0' && byte <= '9':
		return byte - '0', true
	case byte >= 'a' && byte <= 'f':
		return byte - 'a' + 10, true
	case byte >= 'A' && byte <= 'F':
		return byte - 'A' + 10, true
	}
	return 0, false
}

// buildNative builds the promised native document from the validated
// record, applying the XML expressibility boundary (RFC 0013 §7, hard gate
// 3) and the authorized date truncation policy. Truncation happens in place
// on the record so the serializer and the closure see the same promised
// semantics.
func buildNative(record *materializationRecord, style materializationStyle,
	request document.MaterializationRequest) (*PlistDocument, []*protocol.Diagnostic, bool, *MaterializationFailure) {
	limits := request.Limits()
	builder := NewPlistDocumentBuilderWithLimits(PlistArenaLimits{
		MaxObjects: limits.MaxInputNodes, MaxContainerDepth: limits.MaxDepth})
	var events []*protocol.Diagnostic
	transformed := false
	root, failure := buildValue(&builder, &record.root, style, record.policy,
		&events, &transformed)
	if failure != nil {
		return nil, nil, false, failure
	}
	document, err := builder.Build(root)
	if err != nil {
		return nil, nil, false, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	return document, events, transformed, nil
}

// buildValue builds one value node, applying the XML expressibility
// boundary and the authorized truncation policy.
func buildValue(builder *PlistDocumentBuilder, node *materializationValueNode, style materializationStyle,
	policy bool, events *[]*protocol.Diagnostic, transformed *bool) (PlistValueRef, *MaterializationFailure) {
	switch node.kind {
	case valueKindDict:
		dictEntries := make([]PlistDictEntry, 0, len(node.dictEntries))
		for index := range node.dictEntries {
			entry := &node.dictEntries[index]
			if style == styleXMLValue && !isXMLText(entry.key.CodeUnits()) {
				return PlistValueRef{}, unrepresentableFailure(&entry.keyPath, core.KindString)
			}
			valueRef, failure := buildValue(builder, &entry.value, style, policy, events, transformed)
			if failure != nil {
				return PlistValueRef{}, failure
			}
			dictEntries = append(dictEntries, NewPlistDictEntry(NewPlistKeyFromString(entry.key), valueRef))
		}
		reference, err := builder.Add(NewPlistValueDict(NewPlistDictFromEntries(dictEntries)))
		if err != nil {
			return PlistValueRef{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		return reference, nil
	case valueKindArray:
		elements := make([]PlistValueRef, 0, len(node.elements))
		for index := range node.elements {
			elementRef, failure := buildValue(builder, &node.elements[index], style, policy, events, transformed)
			if failure != nil {
				return PlistValueRef{}, failure
			}
			elements = append(elements, elementRef)
		}
		reference, err := builder.Add(NewPlistValueArray(NewPlistArrayFromElements(elements)))
		if err != nil {
			return PlistValueRef{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		return reference, nil
	case valueKindString:
		if style == styleXMLValue &&
			(node.str.Status() == PlistStringUnpairedSurrogate || !isXMLText(node.str.CodeUnits())) {
			return PlistValueRef{}, unrepresentableFailure(&node.path, core.KindString)
		}
		reference, err := builder.Add(NewPlistValueString(node.str))
		if err != nil {
			return PlistValueRef{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		return reference, nil
	case valueKindInteger:
		reference, err := builder.Add(NewPlistValueInteger(NewPlistInteger(node.integer)))
		if err != nil {
			return PlistValueRef{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		return reference, nil
	case valueKindReal:
		if style == styleXMLValue {
			if node.real.Width() == RealWidthFloat32 {
				return PlistValueRef{}, unrepresentableFailure(&node.path, core.KindBinaryFloat32)
			}
			if !realExpressible(node.real) {
				return PlistValueRef{}, unrepresentableFailure(&node.path, core.KindBinaryFloat64)
			}
		}
		reference, err := builder.Add(NewPlistValueReal(node.real))
		if err != nil {
			return PlistValueRef{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		return reference, nil
	case valueKindBoolean:
		reference, err := builder.Add(NewPlistValueBoolean(NewPlistBoolean(node.boolean)))
		if err != nil {
			return PlistValueRef{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		return reference, nil
	case valueKindDate:
		if style == styleXMLValue {
			if math.Float64bits(node.seconds) == negativeZeroBits {
				return PlistValueRef{}, unrepresentableFailure(&node.path, core.KindDate)
			}
			if _, _, _, _, _, _, dateError := wholeSecondDate(node.seconds); dateError != 0 {
				if dateError == dateRangeFractionalSeconds {
					if !policy {
						return PlistValueRef{}, unrepresentableFailure(&node.path, core.KindDate)
					}
					original := node.seconds
					truncated := math.Trunc(original)
					node.seconds = truncated
					if math.Float64bits(truncated) == negativeZeroBits {
						return PlistValueRef{}, unrepresentableFailure(&node.path, core.KindDate)
					}
					if _, _, _, _, _, _, truncateError := wholeSecondDate(truncated); truncateError != 0 {
						return PlistValueRef{}, unrepresentableFailure(&node.path, core.KindDate)
					}
					*events = append(*events, fractionalDateEvent(&node.path, original,
						uint64(len(*events))))
					*transformed = true
				} else {
					return PlistValueRef{}, unrepresentableFailure(&node.path, core.KindDate)
				}
			}
		}
		date, valid := NewPlistDateFromSeconds(node.seconds)
		if !valid {
			return PlistValueRef{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		reference, err := builder.Add(NewPlistValueDate(date))
		if err != nil {
			return PlistValueRef{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		return reference, nil
	case valueKindData:
		reference, err := builder.Add(NewPlistValueData(NewPlistDataFromBytes(node.bytes)))
		if err != nil {
			return PlistValueRef{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		return reference, nil
	case valueKindUID:
		if style == styleXMLValue {
			return PlistValueRef{}, unrepresentableFailure(&node.path, core.KindInteger)
		}
		reference, err := builder.Add(NewPlistValueUID(NewPlistUID(node.uid)))
		if err != nil {
			return PlistValueRef{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		return reference, nil
	}
	return PlistValueRef{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
}

// unrepresentableFailure builds one Date-or-other leaf failure; the Date
// kind is the fractional-date code contract of RFC 0013 §10.1.
func unrepresentableFailure(path *protocol.ValuePath, kind core.Kind) *MaterializationFailure {
	return &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
		Path: *path, ValueKind: kind}
}

// fractionalDateEvent is one authorized truncation report event (RFC 0013
// §10.1): the code is the stable fractional-date code, and the arguments
// carry the input value path and the original exact seconds.
func fractionalDateEvent(path *protocol.ValuePath, seconds float64, occurrence uint64) *protocol.Diagnostic {
	diagnostic := newDiagnostic(fractionalDateCode, protocol.CategoryMaterialization,
		protocol.SeverityWarning, nil,
		map[string]string{"path": renderPath(path), "seconds": formatFloat(seconds)}, 0)
	diagnostic.Occurrence = occurrence
	return diagnostic
}

// renderPath is the stable path rendering for diagnostic arguments
// (materialization.rs:887-913).
func renderPath(path *protocol.ValuePath) string {
	var out strings.Builder
	for _, segment := range path.Segments() {
		switch segment.Kind {
		case "ObjectValue":
			out.WriteString("/")
			out.WriteString(segment.Key)
		case "SequenceElement":
			out.WriteString("[")
			out.WriteString(strconvUint(segment.Index))
			out.WriteString("]")
		case "EntryKey":
			out.WriteString("[key ")
			out.WriteString(strconvUint(segment.Index))
			out.WriteString("]")
		case "EntryValue":
			out.WriteString("[value ")
			out.WriteString(strconvUint(segment.Index))
			out.WriteString("]")
		}
	}
	return out.String()
}

// formatFloat renders one double for diagnostic arguments.
func formatFloat(value float64) string {
	return strconvFormatFloat(value)
}

// serializeXMLRecord serializes one record as a `plist.xml@1` source (RFC
// 0013 §4, §10.1). The output uses the exact Apple header spelling,
// deterministic four-space indentation (the root value element at depth 1),
// LF line endings, keys in input association order, decimal integers,
// shortest-round-trip reals, whole-second dates, and base64 wrapped at
// `76 - 8 * depth` characters per line.
func serializeXMLRecord(record *materializationRecord,
	limits document.MaterializationLimits) ([]byte, *MaterializationFailure) {
	var out strings.Builder
	out.WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
	out.WriteString("<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n")
	out.WriteString("<plist version=\"1.0\">\n")
	failure := emitValue(&out, &record.root, 1, limits)
	if failure != nil {
		return nil, failure
	}
	out.WriteString("</plist>\n")
	return []byte(out.String()), nil
}

// emitValue emits one value element at the given depth.
func emitValue(out *strings.Builder, node *materializationValueNode, depth int,
	limits document.MaterializationLimits) *MaterializationFailure {
	switch node.kind {
	case valueKindDict:
		writeIndent(out, depth)
		if len(node.dictEntries) == 0 {
			out.WriteString("<dict></dict>\n")
		} else {
			out.WriteString("<dict>\n")
			for index := range node.dictEntries {
				entry := &node.dictEntries[index]
				writeIndent(out, depth+1)
				out.WriteString("<key>")
				keyText, err := entry.key.ToUnicode()
				if err != nil {
					return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
				}
				out.WriteString(escapeXMLText(keyText))
				out.WriteString("</key>\n")
				if failure := emitValue(out, &entry.value, depth+1, limits); failure != nil {
					return failure
				}
			}
			writeIndent(out, depth)
			out.WriteString("</dict>\n")
		}
	case valueKindArray:
		writeIndent(out, depth)
		if len(node.elements) == 0 {
			out.WriteString("<array></array>\n")
		} else {
			out.WriteString("<array>\n")
			for index := range node.elements {
				if failure := emitValue(out, &node.elements[index], depth+1, limits); failure != nil {
					return failure
				}
			}
			writeIndent(out, depth)
			out.WriteString("</array>\n")
		}
	case valueKindString:
		writeIndent(out, depth)
		text, err := node.str.ToUnicode()
		if err != nil {
			return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		out.WriteString("<string>")
		out.WriteString(escapeXMLText(text))
		out.WriteString("</string>\n")
	case valueKindInteger:
		writeIndent(out, depth)
		out.WriteString("<integer>")
		out.WriteString(itoa64(node.integer))
		out.WriteString("</integer>\n")
	case valueKindReal:
		writeIndent(out, depth)
		out.WriteString("<real>")
		out.WriteString(renderReal(node.real))
		out.WriteString("</real>\n")
	case valueKindBoolean:
		writeIndent(out, depth)
		if node.boolean {
			out.WriteString("<true/>\n")
		} else {
			out.WriteString("<false/>\n")
		}
	case valueKindDate:
		writeIndent(out, depth)
		out.WriteString("<date>")
		year, month, day, hour, minute, second, dateError := wholeSecondDate(node.seconds)
		if dateError != 0 {
			return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		out.WriteString(renderDate(year, month, day, hour, minute, second))
		out.WriteString("</date>\n")
	case valueKindData:
		writeIndent(out, depth)
		out.WriteString("<data>")
		out.WriteString(encodeBase64Wrapped(node.bytes, depth))
		out.WriteString("</data>\n")
	case valueKindUID:
		return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	if out.Len() > limits.MaxOutputBytes {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
			LimitName: "output-bytes"}
	}
	return nil
}

// scalarKey is the content key of one scalar object; String, Integer,
// Real, Date, and Data participate in first-occurrence deduplication (RFC
// 0013 §5.12, §10.2). Booleans and UIDs are always written fresh.
type scalarKey struct {
	kind    materializationValueKind
	str     PlistString
	integer int64
	real    PlistReal
	boolean bool
	date    uint64
	bytes   []byte
	uid     uint32
}

// deduplicates reports whether this scalar participates in first-occurrence
// deduplication (RFC 0013 §5.12: string, integer, real, date, data).
func (k scalarKey) deduplicates() bool {
	switch k.kind {
	case valueKindString, valueKindInteger, valueKindReal, valueKindDate, valueKindData:
		return true
	}
	return false
}

// scalarKeyEquals compares two scalar content keys exactly.
func scalarKeyEquals(left, right *scalarKey) bool {
	if left.kind != right.kind {
		return false
	}
	switch left.kind {
	case valueKindString:
		return left.str.Equal(right.str)
	case valueKindInteger:
		return left.integer == right.integer
	case valueKindReal:
		return left.real.Equal(right.real)
	case valueKindBoolean:
		return left.boolean == right.boolean
	case valueKindDate:
		return left.date == right.date
	case valueKindData:
		if len(left.bytes) != len(right.bytes) {
			return false
		}
		for index := range left.bytes {
			if left.bytes[index] != right.bytes[index] {
				return false
			}
		}
		return true
	case valueKindUID:
		return left.uid == right.uid
	}
	return false
}

// plannedObject is one planned binary object in object-table order.
type plannedObject struct {
	isDict      bool
	isArray     bool
	keyRefs     []int
	valueRefs   []int
	elementRefs []int
	scalar      *scalarKey
}

// serializeBinaryRecord serializes one record as a `plist.binary@1` source
// (RFC 0013 §5, §10.2). The object table is document-ordered (the root
// value is object 0, every dictionary is followed by its key objects and
// then its values), integers use the minimal width with negatives always 8
// bytes, Float32 width facts are preserved, identical deduplicable scalars
// share one object at first occurrence, UIDs use the minimal width, and the
// offset/ref sizes are the minimal widths satisfying the trailer
// sufficiency checks.
func serializeBinaryRecord(record *materializationRecord,
	limits document.MaterializationLimits) ([]byte, *MaterializationFailure) {
	objects, items := planBinary(&record.root)
	numObjects := len(objects)
	refSize := refSizeFor(numObjects)
	out := append([]byte(nil), binaryHeader...)
	offsets := make([]int, 0, numObjects)
	for _, object := range objects {
		offsets = append(offsets, len(out))
		out = writePlannedObject(out, object, refSize)
		if len(out) > limits.MaxOutputBytes {
			return nil, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
				LimitName: "output-bytes"}
		}
	}
	offsetTableOffset := len(out)
	offsetIntSize := refSizeFor(offsetTableOffset)
	for _, offset := range offsets {
		out = writeBE(out, uint64(offset), offsetIntSize)
	}
	out = append(out, 0, 0, 0, 0, 0)
	out = append(out, 0) // sortVersion
	out = append(out, byte(offsetIntSize))
	out = append(out, byte(refSize))
	out = writeBE(out, uint64(numObjects), 8)
	out = writeBE(out, 0, 8) // topObject: the root value is always object 0
	out = writeBE(out, uint64(offsetTableOffset), 8)
	_ = items
	return out, nil
}

// planBinary plans the document-ordered binary object table (RFC 0013
// §10.2; materialization.rs:1007-1092). The order is a pre-order of the
// value tree where a dictionary is written first, then its key objects,
// then its values recursively; identical deduplicable scalars share one
// object at first occurrence, and containers are always written fresh.
func planBinary(root *materializationValueNode) ([]plannedObject, []int) {
	var objects []plannedObject
	cache := map[string]int{}
	var planNode func(node *materializationValueNode) int
	planNode = func(node *materializationValueNode) int {
		switch node.kind {
		case valueKindDict:
			index := len(objects)
			objects = append(objects, plannedObject{isDict: true})
			keyRefs := make([]int, 0, len(node.dictEntries))
			for index := range node.dictEntries {
				key := scalarKey{kind: valueKindString, str: node.dictEntries[index].key}
				cacheKey := scalarCacheKey(&key)
				keyIndex, exists := cache[cacheKey]
				if !exists {
					keyIndex = len(objects)
					objects = append(objects, plannedObject{scalar: &key})
					cache[cacheKey] = keyIndex
				}
				keyRefs = append(keyRefs, keyIndex)
			}
			valueRefs := make([]int, 0, len(node.dictEntries))
			for index := range node.dictEntries {
				valueRefs = append(valueRefs, planNode(&node.dictEntries[index].value))
			}
			objects[index].keyRefs = keyRefs
			objects[index].valueRefs = valueRefs
			return index
		case valueKindArray:
			index := len(objects)
			objects = append(objects, plannedObject{isArray: true})
			elementRefs := make([]int, 0, len(node.elements))
			for index := range node.elements {
				elementRefs = append(elementRefs, planNode(&node.elements[index]))
			}
			objects[index].elementRefs = elementRefs
			return index
		default:
			key := scalarKeyFromNode(node)
			if key.deduplicates() {
				cacheKey := scalarCacheKey(&key)
				if existing, exists := cache[cacheKey]; exists {
					return existing
				}
				index := len(objects)
				objects = append(objects, plannedObject{scalar: &key})
				cache[cacheKey] = index
				return index
			}
			index := len(objects)
			objects = append(objects, plannedObject{scalar: &key})
			return index
		}
	}
	planNode(root)
	return objects, nil
}

// scalarCacheKey renders one scalar content key as a stable string; only
// deduplicable kinds reach the cache.
func scalarCacheKey(key *scalarKey) string {
	var builder strings.Builder
	builder.WriteByte(byte('0' + key.kind))
	switch key.kind {
	case valueKindString:
		units := key.str.CodeUnits()
		for _, unit := range units {
			builder.WriteByte(byte(unit >> 8))
			builder.WriteByte(byte(unit))
		}
	case valueKindInteger:
		builder.WriteString(itoa64(key.integer))
	case valueKindReal:
		builder.WriteByte(byte('0' + key.real.Width()))
		builder.WriteString(strconvUint(key.real.Bits()))
	case valueKindDate:
		builder.WriteString(strconvUint(key.date))
	case valueKindData:
		builder.Write(key.bytes)
	}
	return builder.String()
}

// scalarKeyFromNode builds the content key of one non-container value node.
func scalarKeyFromNode(node *materializationValueNode) scalarKey {
	switch node.kind {
	case valueKindString:
		return scalarKey{kind: valueKindString, str: node.str}
	case valueKindInteger:
		return scalarKey{kind: valueKindInteger, integer: node.integer}
	case valueKindReal:
		return scalarKey{kind: valueKindReal, real: node.real}
	case valueKindBoolean:
		return scalarKey{kind: valueKindBoolean, boolean: node.boolean}
	case valueKindDate:
		return scalarKey{kind: valueKindDate, date: math.Float64bits(node.seconds)}
	case valueKindData:
		return scalarKey{kind: valueKindData, bytes: node.bytes}
	case valueKindUID:
		return scalarKey{kind: valueKindUID, uid: node.uid}
	}
	return scalarKey{kind: valueKindDict}
}

// writePlannedObject writes one planned object: marker, size, payload, and
// references (RFC 0013 §5).
func writePlannedObject(out []byte, object plannedObject, refSize int) []byte {
	if object.isDict {
		count := len(object.keyRefs)
		out = writeSizedMarker(out, 0xD0, count)
		for _, key := range object.keyRefs {
			out = writeBE(out, uint64(key), refSize)
		}
		for _, value := range object.valueRefs {
			out = writeBE(out, uint64(value), refSize)
		}
		return out
	}
	if object.isArray {
		count := len(object.elementRefs)
		out = writeSizedMarker(out, 0xA0, count)
		for _, element := range object.elementRefs {
			out = writeBE(out, uint64(element), refSize)
		}
		return out
	}
	key := object.scalar
	switch key.kind {
	case valueKindString:
		out = writeStringObject(out, key.str)
	case valueKindInteger:
		width := integerWidth(key.integer)
		out = append(out, 0x10|byte(log2Width(width)))
		out = writeBE(out, uint64(key.integer), width)
	case valueKindReal:
		switch key.real.Width() {
		case RealWidthFloat64:
			out = append(out, 0x23)
			out = writeBE(out, key.real.Bits(), 8)
		case RealWidthFloat32:
			out = append(out, 0x22)
			out = writeBE(out, key.real.Bits(), 4)
		}
	case valueKindBoolean:
		if key.boolean {
			out = append(out, 0x09)
		} else {
			out = append(out, 0x08)
		}
	case valueKindDate:
		out = append(out, 0x33)
		out = writeBE(out, key.date, 8)
	case valueKindData:
		out = writeSizedMarker(out, 0x40, len(key.bytes))
		out = append(out, key.bytes...)
	case valueKindUID:
		width := uidWidth(uint64(key.uid))
		out = append(out, 0x80|byte(width-1))
		out = writeBE(out, uint64(key.uid), width)
	}
	return out
}

// objectField returns one named field of an Object value.
func objectField(object *core.Object, name string) (core.Value, bool) {
	return object.Get(name)
}

// strconvFormatFloat renders one double for diagnostics.
func strconvFormatFloat(value float64) string {
	return strconv.FormatFloat(value, 'g', -1, 64)
}
