package xml

// ---------------------------------------------------------------------------
// Benchmark baseline (milestone 0.19.0 G5.4; docs/go-implementation-plan.md
// §2.6). See go/json/json_bench_test.go for the shared discipline.
// ---------------------------------------------------------------------------

import (
	"bytes"
	"context"
	"testing"
)

// parseFixture is a representative `xml.1.0-safe@1` document (~1.5 KiB).
var parseFixture = []byte(`<?xml version="1.0" encoding="UTF-8"?>
<service xmlns="urn:consema:service" xmlns:cfg="urn:consema:config"
         name="consema-service" version="0.19.0" replicas="3"
         enabled="true" ratio="0.875">
  <cfg:server host="0.0.0.0" port="8080" tls="true">
    <cfg:timeouts read="30s" write="10s" idle="90s"/>
    <cfg:tls cert="/etc/consema/tls.crt" key="/etc/consema/tls.key"/>
  </cfg:server>
  <logging level="info" format="json" sample_rate="0.1">
    <outputs><output>stdout</output><output>/var/log/consema.log</output></outputs>
  </logging>
  <metrics enabled="true" port="9090" path="/metrics">
    <histogram-buckets>0.001</histogram-buckets>
    <histogram-buckets>0.01</histogram-buckets>
    <histogram-buckets>0.1</histogram-buckets>
    <histogram-buckets>1.0</histogram-buckets>
    <histogram-buckets>10.0</histogram-buckets>
  </metrics>
  <deployments>
    <deployment strategy="rolling-update" max-surge="25%">
      <pod name="web" replicas="3"><resources cpu="500m" memory="128Mi"/></pod>
      <pod name="worker" replicas="2"><resources cpu="1" memory="512Mi"/></pod>
    </deployment>
  </deployments>
  <annotation>中文 配置 &amp; 🦀 emoji</annotation>
  <comment><!-- generated by consema 0.19.0 --></comment>
  <cdata><![CDATA[raw <content> & more]]></cdata>
</service>
`)

// benchSink keeps benchmark results alive so the compiler cannot elide the
// measured work.
var benchSink []byte

// BenchmarkParse measures one full XML parse of the fixture under the
// production default limits.
func BenchmarkParse(b *testing.B) {
	b.SetBytes(int64(len(parseFixture)))
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		doc, failure := Parse(context.Background(), parseFixture, XmlProfileSafeV1,
			XmlEncodingProfileDefault(), DefaultXmlParseLimits())
		if failure != nil {
			b.Fatalf("parse: %v", failure)
		}
		benchSink = doc.Render()
	}
}

// BenchmarkRender measures the lossless render closure.
func BenchmarkRender(b *testing.B) {
	doc, failure := Parse(context.Background(), parseFixture, XmlProfileSafeV1,
		XmlEncodingProfileDefault(), DefaultXmlParseLimits())
	if failure != nil {
		b.Fatalf("parse: %v", failure)
	}
	b.SetBytes(int64(len(parseFixture)))
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		benchSink = doc.Render()
		if !bytes.Equal(benchSink, parseFixture) {
			b.Fatal("render closure violated")
		}
	}
}
