package toml

import (
	"fmt"
	"math"
	"strconv"
	"strings"

	"consema.dev/consema/core"
	"consema.dev/consema/document"
	"consema.dev/consema/protocol"
)

// MaterializationFidelity is the materialization fidelity classification
// (consema-document materialization.rs; the TOML materializer reports
// Exact for objects and Transformed for explicitly converted ordered
// mappings).
type MaterializationFidelity string

// The two frozen fidelity levels.
const (
	// MaterializationFidelityExact means the target directly represents
	// the input semantics.
	MaterializationFidelityExact MaterializationFidelity = "Exact"
	// MaterializationFidelityTransformed means complete semantics survive
	// an explicit reversible re-encoding.
	MaterializationFidelityTransformed MaterializationFidelity = "Transformed"
)

// MaterializationFailureKind classifies a stable materialization failure
// (consema-document materialization.rs MaterializationFailure).
type MaterializationFailureKind uint8

// The stable materialization failure classes.
const (
	// MaterializationUnsupportedProfile: the requested target profile is
	// unavailable.
	MaterializationUnsupportedProfile MaterializationFailureKind = iota
	// MaterializationUnsupportedStyle: the requested style is unavailable.
	MaterializationUnsupportedStyle
	// MaterializationUnsupportedEncoding: the target does not support the
	// requested encoding.
	MaterializationUnsupportedEncoding
	// MaterializationUnsupportedNewline: the target style does not support
	// the requested newline policy.
	MaterializationUnsupportedNewline
	// MaterializationUnrepresentable: the portable input cannot be
	// represented by the target profile.
	MaterializationUnrepresentable
	// MaterializationResourceLimit: a declared resource limit was reached.
	MaterializationResourceLimit
	// MaterializationFormationFailed: generated bytes did not form the
	// target profile.
	MaterializationFormationFailed
)

// MaterializationFailure is the typed materialization failure. It
// implements error and the RFC 0016 §6 Code() contract.
type MaterializationFailure struct {
	// Kind identifies the failure.
	Kind MaterializationFailureKind
	// Path is the offending input value path of Unrepresentable failures.
	Path protocol.ValuePath
	// KindName is the offending PortableValue kind name of
	// Unrepresentable failures.
	KindName string
	// LimitName is the stable limit name of ResourceLimit failures.
	LimitName string
}

// Code returns the frozen registered code.
func (f *MaterializationFailure) Code() string {
	switch f.Kind {
	case MaterializationUnsupportedProfile:
		return "core.materialization.unsupported-profile@1"
	case MaterializationUnsupportedStyle:
		return "core.materialization.unsupported-style@1"
	case MaterializationUnsupportedEncoding:
		return "core.materialization.unsupported-encoding@1"
	case MaterializationUnsupportedNewline:
		return "core.materialization.unsupported-newline@1"
	case MaterializationUnrepresentable:
		return "core.materialization.unrepresentable@1"
	case MaterializationResourceLimit:
		return "core.materialization.resource-limit@1"
	case MaterializationFormationFailed:
		return "core.materialization.formation-failed@1"
	}
	return "core.materialization.invalid-request@1"
}

// Error implements error; the text is human presentation only.
func (f *MaterializationFailure) Error() string {
	switch f.Kind {
	case MaterializationUnsupportedProfile:
		return "toml: unsupported materialization profile"
	case MaterializationUnsupportedStyle:
		return "toml: unsupported materialization style"
	case MaterializationUnsupportedEncoding:
		return "toml: unsupported materialization encoding"
	case MaterializationUnsupportedNewline:
		return "toml: unsupported materialization newline policy"
	case MaterializationUnrepresentable:
		return "toml: input kind " + f.KindName + " is not representable"
	case MaterializationResourceLimit:
		return "toml: materialization resource limit " + f.LimitName + " was reached"
	case MaterializationFormationFailed:
		return "toml: generated bytes did not form a TOML document"
	}
	return "toml: materialization failed"
}

// MaterializationReport is the complete ordered materialization report
// (consema-document materialization.rs MaterializationReport).
type MaterializationReport struct {
	events []*protocol.Diagnostic
}

// Events returns the ordered transformation/loss events.
func (r MaterializationReport) Events() []*protocol.Diagnostic {
	return append([]*protocol.Diagnostic(nil), r.events...)
}

// MaterializationRelation is the input-to-output relation of one
// materialized origin.
type MaterializationRelation string

// The three frozen relations.
const (
	// MaterializationRelationDirect is a direct native semantic origin.
	MaterializationRelationDirect MaterializationRelation = "Direct"
	// MaterializationRelationGenerated is an output identity synthesized
	// by the materializer.
	MaterializationRelationGenerated MaterializationRelation = "Generated"
	// MaterializationRelationReencoded is an explicitly re-encoded input
	// origin.
	MaterializationRelationReencoded MaterializationRelation = "Reencoded"
)

// MaterializationInputLocation is one input value or association location.
type MaterializationInputLocation struct {
	// Path is the portable value location of Value locations.
	Path protocol.ValuePath
	// Association is the portable association location of Association
	// locations.
	Association *protocol.AssociationLocation
	// Kind is "Value" or "Association".
	Kind string
}

// MaterializedOrigin is one exact materialized output origin.
type MaterializedOrigin struct {
	// Snapshot is the output document snapshot.
	Snapshot document.SnapshotIdentity
	// Node is the exact structural identity.
	Node document.NodeRef
	// Span is the exact source range.
	Span document.Span
	// Relation is the output relation.
	Relation MaterializationRelation
}

// MaterializationProvenanceEntry is one input-to-outputs mapping entry.
type MaterializationProvenanceEntry struct {
	// Input is the input value or association location.
	Input MaterializationInputLocation
	// Outputs are the ordered output origins.
	Outputs []MaterializedOrigin
}

// MaterializationProvenanceMap is the immutable input-to-output provenance
// map (consema-document materialization.rs
// MaterializationProvenanceMap).
type MaterializationProvenanceMap struct {
	entries []MaterializationProvenanceEntry
}

// Entries returns the deterministic entries.
func (m MaterializationProvenanceMap) Entries() []MaterializationProvenanceEntry {
	return append([]MaterializationProvenanceEntry(nil), m.entries...)
}

// CompleteMaterialization is the complete materialization result
// (consema-document materialization.rs CompleteMaterialization).
type CompleteMaterialization struct {
	// Document is the new immutable target document.
	Document *Document
	// Fidelity is the fidelity of the whole operation.
	Fidelity MaterializationFidelity
	// Report is the machine-readable transformation report.
	Report MaterializationReport
	// Provenance maps every input value and association to its outputs.
	Provenance MaterializationProvenanceMap
}

// FailedMaterializationAttempt is the failed attempt without a document.
type FailedMaterializationAttempt struct {
	// Failure is the typed failure.
	Failure MaterializationFailure
	// Report holds the events discovered before the failure.
	Report MaterializationReport
	// AnalyzedInputPaths are the input paths analyzed before failure.
	AnalyzedInputPaths []protocol.ValuePath
}

// MaterializationResult is the materialization completion algebra. Exactly
// one outcome is non-nil.
type MaterializationResult struct {
	// Complete is the complete success outcome.
	Complete *CompleteMaterialization
	// Failed is the failed attempt with no document.
	Failed *FailedMaterializationAttempt
}

// Materialize materializes one complete PortableValue into a new immutable
// TOML document (consema-toml materialization.rs:19-34). The request must
// target `toml.1.0@1` with the `toml.canonical-document@1` style, UTF-8,
// and an Lf or CrLf newline policy; the generated canonical bytes are
// re-parsed under the request's limits before the document is returned
// (the canonical byte-closure verification).
func Materialize(value core.Value, request document.MaterializationRequest) MaterializationResult {
	attempt := &materializationAttempt{}
	complete, failure := materializeComplete(value, request, attempt)
	if failure != nil {
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure:            *failure,
			Report:             attempt.report,
			AnalyzedInputPaths: attempt.analyzed,
		}}
	}
	return MaterializationResult{Complete: complete}
}

type materializationAttempt struct {
	report   MaterializationReport
	analyzed []protocol.ValuePath
}

func materializeComplete(value core.Value, request document.MaterializationRequest,
	attempt *materializationAttempt) (*CompleteMaterialization, *MaterializationFailure) {
	if failure := requestedContract(request); failure != nil {
		return nil, failure
	}
	prepared, failure := prepareRoot(value, request, &attempt.report)
	if failure != nil {
		return nil, failure
	}
	writer := &tomlWriter{
		newline:  request.Newline(),
		limits:   request.Limits(),
		analyzed: &attempt.analyzed,
	}
	if failure := writer.root(prepared); failure != nil {
		return nil, failure
	}
	bytes := writer.output
	document, formationFailure := Parse(bytes, Toml10V1, materializationParseLimits(request.Limits()))
	if formationFailure != nil {
		return nil, &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	builder := &provenanceBuilder{document: document, limits: request.Limits()}
	if failure := builder.collect(value, protocol.RootValuePath(), document.Root()); failure != nil {
		return nil, failure
	}
	return &CompleteMaterialization{
		Document:   document,
		Fidelity:   prepared.fidelity,
		Report:     attempt.report,
		Provenance: MaterializationProvenanceMap{entries: builder.entries},
	}, nil
}

func requestedContract(request document.MaterializationRequest) *MaterializationFailure {
	profile := request.TargetProfile()
	if profile.ID() != "toml.1.0" || profile.Version() != 1 {
		return &MaterializationFailure{Kind: MaterializationUnsupportedProfile}
	}
	style := request.Style()
	if style.ID() != "toml.canonical-document" || style.Version() != 1 {
		return &MaterializationFailure{Kind: MaterializationUnsupportedStyle}
	}
	if request.Encoding().Kind() != document.EncodingUtf8 {
		return &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
	}
	switch request.Newline() {
	case document.NewlineLf, document.NewlineCrLf:
	default:
		return &MaterializationFailure{Kind: MaterializationUnsupportedNewline}
	}
	return nil
}

// preparedRoot carries the prepared root value form.
type preparedRoot struct {
	object   *core.Object
	mapping  *core.EntryMapping
	fidelity MaterializationFidelity
}

// prepareRoot validates the root value form and applies the mapping
// policy (consema-toml materialization.rs:116-176).
func prepareRoot(value core.Value, request document.MaterializationRequest,
	report *MaterializationReport) (preparedRoot, *MaterializationFailure) {
	if object, ok := value.(*core.Object); ok {
		return preparedRoot{object: object, fidelity: MaterializationFidelityExact}, nil
	}
	mapping, ok := value.(*core.EntryMapping)
	if !ok {
		return preparedRoot{}, &MaterializationFailure{
			Kind: MaterializationUnrepresentable, Path: protocol.RootValuePath(),
			KindName: kindNameOf(value),
		}
	}
	if request.MappingPolicy() != document.MappingPolicyUniqueStringEntriesToObject {
		return preparedRoot{}, &MaterializationFailure{
			Kind: MaterializationUnrepresentable, Path: protocol.RootValuePath(),
			KindName: "EntryMapping",
		}
	}
	entries := mapping.Entries()
	if len(entries) > request.Limits().MaxInputNodes {
		return preparedRoot{}, &MaterializationFailure{
			Kind: MaterializationResourceLimit, LimitName: "input-nodes",
		}
	}
	keys := make(map[string]bool, len(entries))
	for index, entry := range entries {
		path := protocol.RootValuePath().Child(protocol.ValuePathSegment{Kind: "EntryKey", Index: uint64(index)})
		key, ok := entry.Key.(core.String)
		if !ok {
			return preparedRoot{}, &MaterializationFailure{
				Kind: MaterializationUnrepresentable, Path: path, KindName: kindNameOf(entry.Key),
			}
		}
		if keys[string(key)] {
			return preparedRoot{}, &MaterializationFailure{
				Kind: MaterializationUnrepresentable, Path: path, KindName: "String",
			}
		}
		keys[string(key)] = true
	}
	event, err := protocol.NewDiagnostic("core.materialization.mapping-transformed@1",
		protocol.CategoryMaterialization, protocol.SeverityInfo, nil, nil, map[string]string{
			"from":   "EntryMapping",
			"policy": "UniqueStringEntriesToObject",
			"to":     "Object",
		}, nil, nil, 0, protocol.NewErrorCodeRegistry(protocol.ErrorRegistryV7))
	if err != nil {
		return preparedRoot{}, &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	if len(report.events) >= request.Limits().MaxReportEntries {
		return preparedRoot{}, &MaterializationFailure{
			Kind: MaterializationResourceLimit, LimitName: "report-entries",
		}
	}
	report.events = append(report.events, event)
	return preparedRoot{mapping: mapping, fidelity: MaterializationFidelityTransformed}, nil
}

// materializationParseLimits maps the materialization limits onto the
// re-parse limits (consema-toml materialization.rs:178-186).
func materializationParseLimits(limits document.MaterializationLimits) document.ParseLimits {
	return document.ParseLimits{
		MaxSourceBytes:  limits.MaxOutputBytes,
		MaxNestingDepth: limits.MaxDepth,
		MaxTokenCount:   limits.MaxOutputBytes,
		MaxNodeCount:    limits.MaxInputNodes * 4,
		MaxDiagnostics:  limits.MaxReportEntries,
	}
}

// tomlWriter renders the canonical TOML 1.0 document (consema-toml
// materialization.rs:188-547).
type tomlWriter struct {
	newline    document.NewlinePolicy
	limits     document.MaterializationLimits
	inputNodes int
	output     []byte
	analyzed   *[]protocol.ValuePath
}

func (w *tomlWriter) analyze(path *protocol.ValuePath, depth int) *MaterializationFailure {
	if depth > w.limits.MaxDepth {
		return &MaterializationFailure{Kind: MaterializationResourceLimit, LimitName: "input-depth"}
	}
	w.inputNodes++
	if w.inputNodes > w.limits.MaxInputNodes {
		return &MaterializationFailure{Kind: MaterializationResourceLimit, LimitName: "input-nodes"}
	}
	*w.analyzed = append(*w.analyzed, *path)
	return nil
}

func (w *tomlWriter) pushBytes(bytes []byte) *MaterializationFailure {
	if len(w.output)+len(bytes) > w.limits.MaxOutputBytes {
		return &MaterializationFailure{Kind: MaterializationResourceLimit, LimitName: "output-bytes"}
	}
	w.output = append(w.output, bytes...)
	return nil
}

func (w *tomlWriter) pushByte(b byte) *MaterializationFailure {
	return w.pushBytes([]byte{b})
}

func (w *tomlWriter) pushText(text string) *MaterializationFailure {
	return w.pushBytes([]byte(text))
}

func (w *tomlWriter) root(root preparedRoot) *MaterializationFailure {
	path := protocol.RootValuePath()
	if failure := w.analyze(&path, 0); failure != nil {
		return failure
	}
	if root.object != nil {
		for _, entry := range root.object.Entries() {
			if failure := w.writeKey(entry.Key); failure != nil {
				return failure
			}
			if failure := w.pushBytes([]byte(" = ")); failure != nil {
				return failure
			}
			childPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: entry.Key})
			if failure := w.value(entry.Value, &childPath, 1); failure != nil {
				return failure
			}
			if failure := w.pushBytes(w.newline.Bytes()); failure != nil {
				return failure
			}
		}
		if root.object.Len() == 0 {
			return w.pushBytes(w.newline.Bytes())
		}
		return nil
	}
	for index, entry := range root.mapping.Entries() {
		keyPath := path.Child(protocol.ValuePathSegment{Kind: "EntryKey", Index: uint64(index)})
		if failure := w.analyze(&keyPath, 1); failure != nil {
			return failure
		}
		key, ok := entry.Key.(core.String)
		if !ok {
			return &MaterializationFailure{
				Kind: MaterializationUnrepresentable, Path: keyPath, KindName: kindNameOf(entry.Key),
			}
		}
		if failure := w.writeKey(string(key)); failure != nil {
			return failure
		}
		if failure := w.pushBytes([]byte(" = ")); failure != nil {
			return failure
		}
		valuePath := path.Child(protocol.ValuePathSegment{Kind: "EntryValue", Index: uint64(index)})
		if failure := w.value(entry.Value, &valuePath, 1); failure != nil {
			return failure
		}
		if failure := w.pushBytes(w.newline.Bytes()); failure != nil {
			return failure
		}
	}
	if root.mapping.Len() == 0 {
		return w.pushBytes(w.newline.Bytes())
	}
	return nil
}

func (w *tomlWriter) value(value core.Value, path *protocol.ValuePath, depth int) *MaterializationFailure {
	if failure := w.analyze(path, depth); failure != nil {
		return failure
	}
	switch typed := value.(type) {
	case core.Boolean:
		if typed {
			return w.pushBytes([]byte("true"))
		}
		return w.pushBytes([]byte("false"))
	case core.Integer:
		number := typed.Int()
		if !number.IsInt64() {
			return unrepresentable(path, "Integer")
		}
		return w.pushText(number.String())
	case core.BinaryFloat64:
		return w.writeFloat(uint64(typed), path)
	case core.String:
		return w.writeString(string(typed))
	case core.Date:
		return w.writeDate(typed, path)
	case core.Time:
		return w.writeTime(typed, path)
	case core.LocalDateTime:
		if failure := w.writeDate(typed.Date(), path); failure != nil {
			return failure
		}
		if failure := w.pushByte('T'); failure != nil {
			return failure
		}
		return w.writeTime(typed.Time(), path)
	case core.OffsetDateTime:
		if failure := w.writeDate(typed.Local().Date(), path); failure != nil {
			return failure
		}
		if failure := w.pushByte('T'); failure != nil {
			return failure
		}
		if failure := w.writeTime(typed.Local().Time(), path); failure != nil {
			return failure
		}
		seconds := typed.OffsetSeconds()
		if seconds == 0 {
			return w.pushByte('Z')
		}
		if seconds%60 != 0 {
			return unrepresentable(path, "OffsetDateTime")
		}
		minutes := seconds / 60
		if minutes < -24*60 || minutes >= 24*60 {
			return unrepresentable(path, "OffsetDateTime")
		}
		sign := byte('+')
		if minutes < 0 {
			sign = '-'
			minutes = -minutes
		}
		return w.pushText(fmt.Sprintf("%c%02d:%02d", sign, minutes/60, minutes%60))
	case *core.Array:
		return w.writeSequence(typed, path, depth)
	case *core.Object:
		return w.writeInlineObject(typed, path, depth)
	case *core.EntryMapping:
		return unrepresentable(path, "EntryMapping")
	}
	return unrepresentable(path, kindNameOf(value))
}

func unrepresentable(path *protocol.ValuePath, kind string) *MaterializationFailure {
	return &MaterializationFailure{
		Kind: MaterializationUnrepresentable, Path: *path, KindName: kind,
	}
}

func kindNameOf(value core.Value) string {
	switch value.(type) {
	case core.Null:
		return "Null"
	case core.Boolean:
		return "Boolean"
	case core.Integer:
		return "Integer"
	case core.Decimal:
		return "Decimal"
	case core.BinaryFloat32:
		return "BinaryFloat32"
	case core.BinaryFloat64:
		return "BinaryFloat64"
	case core.String:
		return "String"
	case core.Bytes:
		return "Bytes"
	case core.Date:
		return "Date"
	case core.Time:
		return "Time"
	case core.LocalDateTime:
		return "LocalDateTime"
	case core.OffsetDateTime:
		return "OffsetDateTime"
	case *core.Array:
		return "Sequence"
	case *core.Object:
		return "Object"
	case *core.EntryMapping:
		return "EntryMapping"
	}
	return "Unknown"
}

// writeKey writes a canonical quoted key (consema-toml
// materialization.rs:353-355).
func (w *tomlWriter) writeKey(value string) *MaterializationFailure {
	return w.writeString(value)
}

// writeString writes the canonical basic string (consema-toml
// materialization.rs:357-380).
func (w *tomlWriter) writeString(value string) *MaterializationFailure {
	if failure := w.pushByte('"'); failure != nil {
		return failure
	}
	for _, character := range value {
		switch character {
		case '\b':
			if failure := w.pushBytes([]byte(`\b`)); failure != nil {
				return failure
			}
		case '\t':
			if failure := w.pushBytes([]byte(`\t`)); failure != nil {
				return failure
			}
		case '\n':
			if failure := w.pushBytes([]byte(`\n`)); failure != nil {
				return failure
			}
		case '\f':
			if failure := w.pushBytes([]byte(`\f`)); failure != nil {
				return failure
			}
		case '\r':
			if failure := w.pushBytes([]byte(`\r`)); failure != nil {
				return failure
			}
		case '"':
			if failure := w.pushBytes([]byte(`\"`)); failure != nil {
				return failure
			}
		case '\\':
			if failure := w.pushBytes([]byte(`\\`)); failure != nil {
				return failure
			}
		default:
			if character <= 0x1F || character == 0x7F {
				if failure := w.pushText(fmt.Sprintf("\\u%04X", character)); failure != nil {
					return failure
				}
				continue
			}
			if failure := w.pushBytes([]byte(string(character))); failure != nil {
				return failure
			}
		}
	}
	return w.pushByte('"')
}

// writeFloat writes the canonical float (consema-toml
// materialization.rs:382-407): only the frozen NaN payloads are
// representable.
func (w *tomlWriter) writeFloat(bits uint64, path *protocol.ValuePath) *MaterializationFailure {
	float := math.Float64frombits(bits)
	if math.IsNaN(float) {
		switch bits {
		case 0x7ff8000000000000:
			return w.pushBytes([]byte("nan"))
		case 0xfff8000000000000:
			return w.pushBytes([]byte("-nan"))
		}
		return unrepresentable(path, "BinaryFloat64")
	}
	if math.IsInf(float, 1) {
		return w.pushBytes([]byte("inf"))
	}
	if math.IsInf(float, -1) {
		return w.pushBytes([]byte("-inf"))
	}
	output := strconv.FormatFloat(float, 'f', -1, 64)
	if !strings.ContainsAny(output, ".eE") {
		output += ".0"
	}
	return w.pushText(output)
}

// writeDate writes the canonical local date (consema-toml
// materialization.rs:409-424).
func (w *tomlWriter) writeDate(value core.Date, path *protocol.ValuePath) *MaterializationFailure {
	year := value.Year().Int()
	if !year.IsInt64() {
		return unrepresentable(path, "Date")
	}
	yearNumber := year.Int64()
	if yearNumber < 0 || yearNumber > 9999 {
		return unrepresentable(path, "Date")
	}
	return w.pushText(fmt.Sprintf("%04d-%02d-%02d", yearNumber, value.Month(), value.Day()))
}

// writeTime writes the canonical local time (consema-toml
// materialization.rs:426-448).
func (w *tomlWriter) writeTime(value core.Time, path *protocol.ValuePath) *MaterializationFailure {
	nanoseconds, ok := exactNanoseconds(value.FractionalSecond())
	if !ok {
		return unrepresentable(path, "Time")
	}
	if failure := w.pushText(fmt.Sprintf("%02d:%02d:%02d", value.Hour(), value.Minute(), value.Second())); failure != nil {
		return failure
	}
	if nanoseconds != 0 {
		width := 9
		for nanoseconds%10 == 0 {
			nanoseconds /= 10
			width--
		}
		if failure := w.pushText(fmt.Sprintf(".%0*d", width, nanoseconds)); failure != nil {
			return failure
		}
	}
	return nil
}

// writeSequence writes the canonical array (consema-toml
// materialization.rs:488-507).
func (w *tomlWriter) writeSequence(value *core.Array, path *protocol.ValuePath, depth int) *MaterializationFailure {
	if failure := w.pushByte('['); failure != nil {
		return failure
	}
	for index, item := range value.Items() {
		if index != 0 {
			if failure := w.pushBytes([]byte(", ")); failure != nil {
				return failure
			}
		}
		childPath := path.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
		if failure := w.value(item, &childPath, depth+1); failure != nil {
			return failure
		}
	}
	return w.pushByte(']')
}

// writeInlineObject writes the canonical inline table (consema-toml
// materialization.rs:510-536).
func (w *tomlWriter) writeInlineObject(value *core.Object, path *protocol.ValuePath, depth int) *MaterializationFailure {
	if failure := w.pushByte('{'); failure != nil {
		return failure
	}
	entries := value.Entries()
	if len(entries) != 0 {
		if failure := w.pushByte(' '); failure != nil {
			return failure
		}
	}
	for index, entry := range entries {
		if index != 0 {
			if failure := w.pushBytes([]byte(", ")); failure != nil {
				return failure
			}
		}
		if failure := w.writeKey(entry.Key); failure != nil {
			return failure
		}
		if failure := w.pushBytes([]byte(" = ")); failure != nil {
			return failure
		}
		childPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: entry.Key})
		if failure := w.value(entry.Value, &childPath, depth+1); failure != nil {
			return failure
		}
	}
	if len(entries) != 0 {
		if failure := w.pushByte(' '); failure != nil {
			return failure
		}
	}
	return w.pushByte('}')
}

// exactNanoseconds converts one core fractional-second decimal into
// nanoseconds (consema-toml materialization.rs:549-567).
func exactNanoseconds(value core.Decimal) (uint32, bool) {
	coefficient := value.Coefficient()
	if !coefficient.IsInt64() {
		return 0, false
	}
	coefficientNumber := coefficient.Int64()
	if coefficientNumber == 0 {
		return 0, true
	}
	if coefficientNumber < 0 {
		return 0, false
	}
	exponent := value.Exponent()
	if !exponent.IsInt64() {
		return 0, false
	}
	exponentNumber := exponent.Int64()
	if exponentNumber < -9 || exponentNumber >= 0 {
		return 0, false
	}
	nanoseconds := coefficientNumber
	for index := int64(0); index < exponentNumber+9; index++ {
		nanoseconds *= 10
		if nanoseconds >= 1_000_000_000 {
			return 0, false
		}
	}
	if nanoseconds >= 1_000_000_000 {
		return 0, false
	}
	return uint32(nanoseconds), true
}

// canonicalFragment renders one canonical TOML value fragment for
// structural editing (consema-toml materialization.rs:36-45).
func canonicalFragment(value core.Value, limits document.MaterializationLimits) ([]byte, *MaterializationFailure) {
	analyzed := make([]protocol.ValuePath, 0)
	writer := &tomlWriter{newline: document.NewlineLf, limits: limits, analyzed: &analyzed}
	path := protocol.RootValuePath()
	if failure := writer.value(value, &path, 0); failure != nil {
		return nil, failure
	}
	return writer.output, nil
}

// provenanceBuilder collects the input-to-output provenance
// (consema-toml materialization.rs:613-864).
type provenanceBuilder struct {
	document *Document
	limits   document.MaterializationLimits
	units    int
	entries  []MaterializationProvenanceEntry
}

func (b *provenanceBuilder) collect(input core.Value, path protocol.ValuePath,
	output TomlItem) *MaterializationFailure {
	relation := MaterializationRelationDirect
	if _, isMapping := input.(*core.EntryMapping); isMapping {
		relation = MaterializationRelationReencoded
	}
	if failure := b.pushOrigin(MaterializationInputLocation{Kind: "Value", Path: path},
		b.origin(output.NodeRef(), output.Span(), relation)); failure != nil {
		return failure
	}
	switch typed := input.(type) {
	case *core.Array:
		if output.Kind() != ItemKindArray {
			return &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
		elements, ok := output.ArrayElements()
		if !ok {
			return &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
		values := typed.Items()
		if len(values) != len(elements) {
			return &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
		for index, element := range elements {
			childPath := path.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
			if failure := b.collect(values[index], childPath, element.Item()); failure != nil {
				return failure
			}
			if failure := b.addOutput(MaterializationInputLocation{Kind: "Value", Path: childPath},
				b.origin(element.NodeRef(), element.Span(), MaterializationRelationGenerated)); failure != nil {
				return failure
			}
		}
	case *core.Object:
		if failure := b.collectObject(typed, path, output); failure != nil {
			return failure
		}
	case *core.EntryMapping:
		if failure := b.collectMapping(typed, path, output); failure != nil {
			return failure
		}
	default:
		if !scalarKindMatches(input, output.Kind()) {
			return &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
	}
	return nil
}

func (b *provenanceBuilder) collectObject(input *core.Object, path protocol.ValuePath,
	output TomlItem) *MaterializationFailure {
	entries, ok := output.TableEntries()
	if !ok {
		return &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	inputs := input.Entries()
	if len(inputs) != len(entries) {
		return &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	for index, entry := range entries {
		if inputs[index].Key != entry.Name() {
			return &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
		association := protocol.NewAssociationLocation(path, uint64(index),
			protocol.AssociationRoleObjectEntry)
		if failure := b.pushOrigin(MaterializationInputLocation{Kind: "Association", Association: &association},
			b.origin(entry.NodeRef(), entry.Span(), MaterializationRelationDirect)); failure != nil {
			return failure
		}
		keyAssociation := protocol.NewAssociationLocation(path, uint64(index),
			protocol.AssociationRoleObjectKey)
		if failure := b.pushOrigin(MaterializationInputLocation{Kind: "Association", Association: &keyAssociation},
			b.origin(entry.KeyNodeRef(), entry.Span(), MaterializationRelationDirect)); failure != nil {
			return failure
		}
		childPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: inputs[index].Key})
		if failure := b.collect(inputs[index].Value, childPath, entry.Item()); failure != nil {
			return failure
		}
	}
	return nil
}

func (b *provenanceBuilder) collectMapping(input *core.EntryMapping, path protocol.ValuePath,
	output TomlItem) *MaterializationFailure {
	entries, ok := output.TableEntries()
	if !ok {
		return &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	inputs := input.Entries()
	if len(inputs) != len(entries) {
		return &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	for index, entry := range entries {
		key, ok := inputs[index].Key.(core.String)
		if !ok || string(key) != entry.Name() {
			return &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
		association := protocol.NewAssociationLocation(path, uint64(index),
			protocol.AssociationRoleEntryMappingItem)
		if failure := b.pushOrigin(MaterializationInputLocation{Kind: "Association", Association: &association},
			b.origin(entry.NodeRef(), entry.Span(), MaterializationRelationReencoded)); failure != nil {
			return failure
		}
		keyPath := path.Child(protocol.ValuePathSegment{Kind: "EntryKey", Index: uint64(index)})
		if failure := b.pushOrigin(MaterializationInputLocation{Kind: "Value", Path: keyPath},
			b.origin(entry.KeyNodeRef(), entry.Span(), MaterializationRelationReencoded)); failure != nil {
			return failure
		}
		valuePath := path.Child(protocol.ValuePathSegment{Kind: "EntryValue", Index: uint64(index)})
		if failure := b.collect(inputs[index].Value, valuePath, entry.Item()); failure != nil {
			return failure
		}
	}
	return nil
}

func (b *provenanceBuilder) origin(node document.NodeRef, span document.Span,
	relation MaterializationRelation) MaterializedOrigin {
	return MaterializedOrigin{
		Snapshot: b.document.SnapshotIdentity(),
		Node:     node,
		Span:     span,
		Relation: relation,
	}
}

func (b *provenanceBuilder) pushOrigin(input MaterializationInputLocation,
	output MaterializedOrigin) *MaterializationFailure {
	b.units += 2
	if b.units > b.limits.MaxProvenanceEntries {
		return &MaterializationFailure{Kind: MaterializationResourceLimit, LimitName: "provenance-entries"}
	}
	b.entries = append(b.entries, MaterializationProvenanceEntry{
		Input: input, Outputs: []MaterializedOrigin{output},
	})
	return nil
}

func (b *provenanceBuilder) addOutput(input MaterializationInputLocation,
	output MaterializedOrigin) *MaterializationFailure {
	b.units++
	if b.units > b.limits.MaxProvenanceEntries {
		return &MaterializationFailure{Kind: MaterializationResourceLimit, LimitName: "provenance-entries"}
	}
	for index := range b.entries {
		entry := &b.entries[index]
		if sameMaterializationInput(entry.Input, input) {
			entry.Outputs = append(entry.Outputs, output)
			return nil
		}
	}
	return &MaterializationFailure{Kind: MaterializationFormationFailed}
}

func sameMaterializationInput(left, right MaterializationInputLocation) bool {
	if left.Kind != right.Kind {
		return false
	}
	if left.Kind == "Value" {
		return left.Path.Equal(right.Path)
	}
	if left.Association == nil || right.Association == nil {
		return left.Association == right.Association
	}
	return left.Association.Equal(*right.Association)
}

// scalarKindMatches reports whether the materialized scalar category
// matches the input kind (consema-toml materialization.rs:866-884).
func scalarKindMatches(input core.Value, output TomlItemKind) bool {
	switch input.(type) {
	case core.String:
		return output == ItemKindString
	case core.Integer:
		return output == ItemKindInteger
	case core.BinaryFloat64:
		return output == ItemKindFloat
	case core.Boolean:
		return output == ItemKindBoolean
	case core.Date:
		return output == ItemKindLocalDate
	case core.Time:
		return output == ItemKindLocalTime
	case core.LocalDateTime:
		return output == ItemKindLocalDateTime
	case core.OffsetDateTime:
		return output == ItemKindOffsetDateTime
	}
	return false
}
