package properties

import (
	"sort"

	"consema.dev/consema/core"
	"consema.dev/consema/document"
	"consema.dev/consema/protocol"
)

// This file implements the canonical Java Properties materialization
// (consema-properties materialization.rs; RFC 0010 §12): one flat String
// mapping becomes a new canonical `key=value` document under the exact
// Reader or Latin-1 profile. Every result reparses under the exact target
// profile and reprojects under the request's policy before a Complete
// result exists; output bytes, fidelity, and provenance are atomic and
// bounded.

// MaterializationFidelity is the materialization fidelity classification
// (materialization.rs: the Rust MaterializationFidelity).
type MaterializationFidelity string

// The two frozen fidelity levels.
const (
	// MaterializationFidelityExact means the target directly represents the
	// input semantics.
	MaterializationFidelityExact MaterializationFidelity = "Exact"
	// MaterializationFidelityTransformed means complete semantics survive an
	// explicit reversible re-encoding.
	MaterializationFidelityTransformed MaterializationFidelity = "Transformed"
)

// MaterializationFailureKind classifies a stable materialization failure
// (materialization.rs: the Rust MaterializationFailure).
type MaterializationFailureKind uint8

// The stable materialization failure classes.
const (
	// MaterializationUnsupportedProfile: the requested target profile is
	// unavailable.
	MaterializationUnsupportedProfile MaterializationFailureKind = iota
	// MaterializationUnsupportedStyle: the requested style is unavailable.
	MaterializationUnsupportedStyle
	// MaterializationUnsupportedEncoding: the target does not support the
	// requested encoding.
	MaterializationUnsupportedEncoding
	// MaterializationUnsupportedNewline: the target style does not support
	// the requested newline policy.
	MaterializationUnsupportedNewline
	// MaterializationUnrepresentable: the portable input cannot be
	// represented by the target profile.
	MaterializationUnrepresentable
	// MaterializationResourceLimit: a declared resource limit was reached.
	MaterializationResourceLimit
	// MaterializationFormationFailed: generated bytes did not form the
	// target profile.
	MaterializationFormationFailed
)

// MaterializationFailure is the typed materialization failure. It
// implements error and the RFC 0016 §6 Code() contract.
type MaterializationFailure struct {
	// Kind identifies the failure.
	Kind MaterializationFailureKind
	// Path is the offending input value path of Unrepresentable failures.
	Path protocol.ValuePath
	// KindName is the offending PortableValue kind name.
	KindName string
	// LimitName is the stable limit name of ResourceLimit failures.
	LimitName string
}

// Code returns the frozen registered code.
func (f *MaterializationFailure) Code() string {
	switch f.Kind {
	case MaterializationUnsupportedProfile:
		return "core.materialization.unsupported-profile@1"
	case MaterializationUnsupportedStyle:
		return "core.materialization.unsupported-style@1"
	case MaterializationUnsupportedEncoding:
		return "core.materialization.unsupported-encoding@1"
	case MaterializationUnsupportedNewline:
		return "core.materialization.unsupported-newline@1"
	case MaterializationUnrepresentable:
		return "core.materialization.unrepresentable@1"
	case MaterializationResourceLimit:
		return "core.materialization.resource-limit@1"
	case MaterializationFormationFailed:
		return "core.materialization.formation-failed@1"
	}
	return "core.materialization.invalid-request@1"
}

// Error implements error; the text is human presentation only.
func (f *MaterializationFailure) Error() string {
	switch f.Kind {
	case MaterializationUnsupportedProfile:
		return "properties: unsupported materialization profile"
	case MaterializationUnsupportedStyle:
		return "properties: unsupported materialization style"
	case MaterializationUnsupportedEncoding:
		return "properties: unsupported materialization encoding"
	case MaterializationUnsupportedNewline:
		return "properties: unsupported materialization newline policy"
	case MaterializationUnrepresentable:
		return "properties: input kind " + f.KindName + " is not representable"
	case MaterializationResourceLimit:
		return "properties: materialization resource limit " + f.LimitName + " was reached"
	case MaterializationFormationFailed:
		return "properties: generated bytes did not form a Properties document"
	}
	return "properties: materialization failed"
}

// MaterializationReport is the complete ordered materialization report
// (canonical Properties materialization is deterministic and emits no
// transformation events).
type MaterializationReport struct {
	events []*protocol.Diagnostic
}

// Events returns the ordered transformation/loss events. The returned
// slice is a copy.
func (r MaterializationReport) Events() []*protocol.Diagnostic {
	return append([]*protocol.Diagnostic(nil), r.events...)
}

// MaterializationInputLocation is one input value or association location.
type MaterializationInputLocation struct {
	// Kind is "Value" or "Association".
	Kind string
	// Path is the portable value location of Value locations.
	Path protocol.ValuePath
	// Association is the portable association location of Association
	// locations.
	Association *protocol.AssociationLocation
}

// MaterializationRelation is the input-to-output relation of one
// materialized origin.
type MaterializationRelation string

// The two frozen relations.
const (
	// MaterializationRelationDirect is a direct native semantic origin.
	MaterializationRelationDirect MaterializationRelation = "Direct"
	// MaterializationRelationReencoded is an explicitly re-encoded input
	// origin.
	MaterializationRelationReencoded MaterializationRelation = "Reencoded"
)

// MaterializedOrigin is one exact materialized output origin.
type MaterializedOrigin struct {
	// Snapshot is the output document snapshot.
	Snapshot document.SnapshotIdentity
	// Node is the exact structural identity.
	Node document.NodeRef
	// Span is the exact source range.
	Span document.Span
	// Relation is the output relation.
	Relation MaterializationRelation
}

// MaterializationProvenanceEntry is one input-to-outputs mapping entry.
type MaterializationProvenanceEntry struct {
	// Input is the input value or association location.
	Input MaterializationInputLocation
	// Outputs are the ordered output origins.
	Outputs []MaterializedOrigin
}

// MaterializationProvenanceMap is the immutable input-to-output provenance
// map.
type MaterializationProvenanceMap struct {
	entries []MaterializationProvenanceEntry
}

// Entries returns the deterministic entries. The returned slice is a copy.
func (m MaterializationProvenanceMap) Entries() []MaterializationProvenanceEntry {
	return append([]MaterializationProvenanceEntry(nil), m.entries...)
}

// CompleteMaterialization is the complete value materialization result.
type CompleteMaterialization struct {
	// Document is the new immutable target document.
	Document *Document
	// Fidelity is the fidelity of the whole operation.
	Fidelity MaterializationFidelity
	// Report is the machine-readable transformation report.
	Report MaterializationReport
	// Provenance maps every input value and association to its outputs.
	Provenance MaterializationProvenanceMap
}

// FailedMaterializationAttempt is the failed attempt without a document.
type FailedMaterializationAttempt struct {
	// Failure is the typed failure.
	Failure MaterializationFailure
	// Report holds the events discovered before the failure.
	Report MaterializationReport
	// AnalyzedInputPaths are the input paths analyzed before failure.
	AnalyzedInputPaths []protocol.ValuePath
}

// MaterializationResult is the value materialization completion algebra.
// Exactly one outcome is non-nil.
type MaterializationResult struct {
	// Complete is the complete success outcome.
	Complete *CompleteMaterialization
	// Failed is the failed attempt with no document.
	Failed *FailedMaterializationAttempt
}

// Materialize materializes one flat String mapping into a new canonical
// Properties document (materialization.rs:24-39). The input must be an
// Object under a unique-key request or an ordered EntryMapping of String
// keys to String values; duplicate associations are preserved in input
// order.
func Materialize(value core.Value, request document.MaterializationRequest) MaterializationResult {
	var analyzed []protocol.ValuePath
	complete, failure := materializeComplete(value, request, &analyzed)
	if failure != nil {
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure:            *failure,
			Report:             MaterializationReport{},
			AnalyzedInputPaths: analyzed,
		}}
	}
	return MaterializationResult{Complete: complete}
}

func materializeComplete(value core.Value, request document.MaterializationRequest,
	analyzed *[]protocol.ValuePath) (*CompleteMaterialization, *MaterializationFailure) {
	profile, failure := requestedProfile(request)
	if failure != nil {
		return nil, failure
	}
	if failure := validateRequest(request, profile); failure != nil {
		return nil, failure
	}
	textLimit, failure := textBudget(request.Encoding(), request.Limits().MaxOutputBytes)
	if failure != nil {
		return nil, failure
	}
	writer := &materializationWriter{
		profile:  profile,
		newline:  request.Newline(),
		limits:   request.Limits(),
		output:   boundedText{maxBytes: textLimit},
		analyzed: analyzed,
	}
	inputEntries, failure := writer.document(value, protocol.RootValuePath(), 0)
	if failure != nil {
		return nil, failure
	}
	text := writer.output.text
	raw, failure := encodeText(text, request.Encoding(), request.Limits().MaxOutputBytes)
	if failure != nil {
		return nil, failure
	}
	selection := Latin1EncodingSelection()
	if profile == PropertiesReaderV1 {
		selection = ReaderEncodingSelection(request.Encoding())
	}
	formed, formationFailure := parse(raw, profile, selection,
		parseLimitsFor(request.Limits()))
	if formationFailure != nil {
		return nil, &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	if formed.formationStatus != document.FormationStatusComplete {
		return nil, &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	if failure := verifyClosure(value, request, formed); failure != nil {
		return nil, failure
	}
	provenance, failure := buildProvenance(inputEntries, formed, request.Limits())
	if failure != nil {
		return nil, failure
	}
	return &CompleteMaterialization{
		Document:   formed,
		Fidelity:   MaterializationFidelityExact,
		Report:     MaterializationReport{},
		Provenance: provenance,
	}, nil
}

func requestedProfile(request document.MaterializationRequest) (PropertiesProfile, *MaterializationFailure) {
	target := request.TargetProfile()
	switch {
	case target.ID() == "java-properties.reader" && target.Version() == 1:
		return PropertiesReaderV1, nil
	case target.ID() == "java-properties.latin1" && target.Version() == 1:
		return PropertiesLatin1V1, nil
	}
	return PropertiesProfile{}, &MaterializationFailure{Kind: MaterializationUnsupportedProfile}
}

func validateRequest(request document.MaterializationRequest,
	profile PropertiesProfile) *MaterializationFailure {
	style := request.Style()
	styleMatches := false
	switch {
	case profile == PropertiesReaderV1 && style.ID() == "java-properties.reader-canonical" &&
		style.Version() == 1:
		styleMatches = true
	case profile == PropertiesLatin1V1 && style.ID() == "java-properties.latin1-canonical" &&
		style.Version() == 1:
		styleMatches = true
	}
	if !styleMatches {
		return &MaterializationFailure{Kind: MaterializationUnsupportedStyle}
	}
	if request.Newline() != document.NewlineLf && request.Newline() != document.NewlineCrLf {
		return &MaterializationFailure{Kind: MaterializationUnsupportedNewline}
	}
	switch {
	case profile == PropertiesReaderV1 && request.Encoding().Kind() != document.EncodingBinary:
		return nil
	case profile == PropertiesLatin1V1 && request.Encoding().Equal(document.Latin1Encoding()):
		return nil
	}
	return &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
}

// parseLimitsFor maps the materialization limits onto the re-parse limits
// (materialization.rs:124-150).
func parseLimitsFor(limits document.MaterializationLimits) PropertiesParseLimits {
	return PropertiesParseLimits{
		Common: document.ParseLimits{
			MaxSourceBytes:  limits.MaxOutputBytes,
			MaxNestingDepth: limits.MaxDepth,
			MaxTokenCount:   limits.MaxOutputBytes,
			MaxNodeCount:    limits.MaxOutputBytes*2 + 1,
			MaxDiagnostics:  limits.MaxReportEntries,
		},
		MaxDecodedUTF8Bytes:        limits.MaxOutputBytes * 3,
		MaxDecodedScalars:          limits.MaxOutputBytes * 2,
		MaxNaturalLines:            limits.MaxInputNodes,
		MaxNaturalLineBytes:        limits.MaxOutputBytes,
		MaxNaturalLineScalars:      limits.MaxOutputBytes,
		MaxLogicalLines:            limits.MaxInputNodes,
		MaxLogicalLineNaturalLines: 1,
		MaxLogicalLineScalars:      limits.MaxOutputBytes,
		MaxProperties:              limits.MaxInputNodes,
		MaxComments:                0,
		MaxEscapes:                 limits.MaxOutputBytes,
		MaxUnicodeEscapes:          limits.MaxOutputBytes,
		MaxJavaCodeUnitsPerString:  limits.MaxOutputBytes,
		MaxTotalJavaCodeUnits:      limits.MaxOutputBytes * 2,
		MaxDuplicateGroupMembers:   limits.MaxInputNodes,
		MaxRecoveryRegions:         limits.MaxReportEntries,
	}
}

// mappingItem is one prepared input association.
type mappingItem struct {
	key         string
	value       core.Value
	association protocol.AssociationLocation
	keyLocation MaterializationInputLocation
	valuePath   protocol.ValuePath
}

// inputEntry is one emitted association with its provenance locations.
type inputEntry struct {
	association MaterializationInputLocation
	key         MaterializationInputLocation
	value       MaterializationInputLocation
}

type materializationWriter struct {
	profile    PropertiesProfile
	newline    document.NewlinePolicy
	limits     document.MaterializationLimits
	inputNodes int
	output     boundedText
	analyzed   *[]protocol.ValuePath
}

type boundedText struct {
	text     string
	maxBytes int
}

func (b *boundedText) push(text string) *MaterializationFailure {
	if len(b.text)+len(text) > b.maxBytes {
		return &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "output-bytes"}
	}
	b.text += text
	return nil
}

func (b *boundedText) pushChar(ch rune) *MaterializationFailure {
	return b.push(string(ch))
}

// document emits every association of one flat mapping
// (materialization.rs:176-211).
func (w *materializationWriter) document(value core.Value, path protocol.ValuePath,
	depth int) ([]inputEntry, *MaterializationFailure) {
	items, failure := w.mappingItems(value, path, depth)
	if failure != nil {
		return nil, failure
	}
	inputEntries := make([]inputEntry, 0, len(items))
	for _, entry := range items {
		if failure := w.analyze(&entry.valuePath, depth+1); failure != nil {
			return nil, failure
		}
		value, ok := entry.value.(core.String)
		if !ok {
			return nil, &MaterializationFailure{Kind: MaterializationUnrepresentable,
				Path: entry.valuePath, KindName: kindNameOf(entry.value)}
		}
		if failure := w.writeString(entry.key, true); failure != nil {
			return nil, failure
		}
		if failure := w.output.push("="); failure != nil {
			return nil, failure
		}
		if failure := w.writeString(string(value), false); failure != nil {
			return nil, failure
		}
		if failure := w.output.push(string(w.newline.Bytes())); failure != nil {
			return nil, failure
		}
		inputEntries = append(inputEntries, inputEntry{
			association: MaterializationInputLocation{Kind: "Association",
				Association: &entry.association},
			key:   entry.keyLocation,
			value: MaterializationInputLocation{Kind: "Value", Path: entry.valuePath},
		})
	}
	return inputEntries, nil
}

// mappingItems validates one Object or EntryMapping and prepares its
// associations (materialization.rs:213-288).
func (w *materializationWriter) mappingItems(value core.Value, path protocol.ValuePath,
	depth int) ([]mappingItem, *MaterializationFailure) {
	if failure := w.analyze(&path, depth); failure != nil {
		return nil, failure
	}
	var entries []core.Entry
	var mapping *core.EntryMapping
	length := 0
	switch typed := value.(type) {
	case *core.Object:
		entries = typed.Entries()
		length = len(entries)
	case *core.EntryMapping:
		mapping = typed
		length = mapping.Len()
	default:
		return nil, &MaterializationFailure{Kind: MaterializationUnrepresentable,
			Path: path, KindName: kindNameOf(value)}
	}
	if length > w.limits.MaxInputNodes {
		return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "input-nodes"}
	}
	items := make([]mappingItem, 0, length)
	if mapping == nil {
		for index, entry := range entries {
			ordinal := uint64(index)
			keyAssociation := protocol.NewAssociationLocation(path, ordinal,
				protocol.AssociationRoleObjectKey)
			items = append(items, mappingItem{
				key:   entry.Key,
				value: entry.Value,
				association: protocol.NewAssociationLocation(path, ordinal,
					protocol.AssociationRoleObjectEntry),
				keyLocation: MaterializationInputLocation{Kind: "Association",
					Association: &keyAssociation},
				valuePath: path.Child(protocol.ValuePathSegment{Kind: "ObjectValue",
					Key: entry.Key}),
			})
		}
		return items, nil
	}
	pairs := mapping.Entries()
	for index, entry := range pairs {
		ordinal := uint64(index)
		keyPath := path.Child(protocol.ValuePathSegment{Kind: "EntryKey", Index: ordinal})
		if failure := w.analyze(&keyPath, depth+1); failure != nil {
			return nil, failure
		}
		key, ok := entry.Key.(core.String)
		if !ok {
			return nil, &MaterializationFailure{Kind: MaterializationUnrepresentable,
				Path: keyPath, KindName: kindNameOf(entry.Key)}
		}
		items = append(items, mappingItem{
			key:   string(key),
			value: entry.Value,
			association: protocol.NewAssociationLocation(path, ordinal,
				protocol.AssociationRoleEntryMappingItem),
			keyLocation: MaterializationInputLocation{Kind: "Value", Path: keyPath},
			valuePath:   path.Child(protocol.ValuePathSegment{Kind: "EntryValue", Index: ordinal}),
		})
	}
	return items, nil
}

func associationLocation(path protocol.ValuePath, ordinal uint64,
	role protocol.AssociationRole) protocol.AssociationLocation {
	return protocol.NewAssociationLocation(path, ordinal, role)
}

func (w *materializationWriter) analyze(path *protocol.ValuePath, depth int) *MaterializationFailure {
	if depth > w.limits.MaxDepth {
		return &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "input-depth"}
	}
	w.inputNodes++
	if w.inputNodes > w.limits.MaxInputNodes {
		return &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "input-nodes"}
	}
	*w.analyzed = append(*w.analyzed, *path)
	return nil
}

// writeString emits one canonical escaped string (materialization.rs:
// 308-346; RFC 0010 §12).
func (w *materializationWriter) writeString(value string, isKey bool) *MaterializationFailure {
	leadingValueSpace := !isKey
	for _, character := range value {
		switch {
		case character == ' ' && (isKey || leadingValueSpace):
			if failure := w.output.push("\\ "); failure != nil {
				return failure
			}
		case character == '\t':
			if failure := w.output.push("\\t"); failure != nil {
				return failure
			}
		case character == '\n':
			if failure := w.output.push("\\n"); failure != nil {
				return failure
			}
		case character == '\r':
			if failure := w.output.push("\\r"); failure != nil {
				return failure
			}
		case character == 0x0C:
			if failure := w.output.push("\\f"); failure != nil {
				return failure
			}
		case character == '\\':
			if failure := w.output.push("\\\\"); failure != nil {
				return failure
			}
		case character == '#' || character == '!' || character == '=' || character == ':':
			if failure := w.output.push("\\"); failure != nil {
				return failure
			}
			if failure := w.output.pushChar(character); failure != nil {
				return failure
			}
		case isControlScalar(character):
			if failure := w.writeUnicodeScalar(character); failure != nil {
				return failure
			}
		case character > 0x7E && w.profile == PropertiesLatin1V1:
			if failure := w.writeUnicodeScalar(character); failure != nil {
				return failure
			}
		default:
			if failure := w.output.pushChar(character); failure != nil {
				return failure
			}
		}
		if character != ' ' {
			leadingValueSpace = false
		}
	}
	return nil
}

// writeUnicodeScalar emits the canonical uppercase `\uXXXX` escape for
// every UTF-16 code unit of one scalar (materialization.rs:338-346).
func (w *materializationWriter) writeUnicodeScalar(value rune) *MaterializationFailure {
	if value > 0xFFFF {
		first := value - 0x10000
		if failure := w.pushHexEscape(uint16(0xD800 + (first >> 10))); failure != nil {
			return failure
		}
		return w.pushHexEscape(uint16(0xDC00 + (first & 0x3FF)))
	}
	return w.pushHexEscape(uint16(value))
}

func (w *materializationWriter) pushHexEscape(unit uint16) *MaterializationFailure {
	const hex = "0123456789ABCDEF"
	text := []byte{'\\', 'u',
		hex[(unit>>12)&0xF], hex[(unit>>8)&0xF], hex[(unit>>4)&0xF], hex[unit&0xF]}
	return w.output.push(string(text))
}

// verifyClosure reparses and reprojects the output under the request's
// policy (materialization.rs:348-395).
func verifyClosure(input core.Value, request document.MaterializationRequest,
	document *Document) *MaterializationFailure {
	projectionLimits := ProjectionLimits{
		MaxSourceAssociations: request.Limits().MaxInputNodes,
		MaxValueNodes:         request.Limits().MaxInputNodes*2 + 1,
		MaxReportEntries:      request.Limits().MaxReportEntries,
		MaxProvenanceUnits:    request.Limits().MaxProvenanceEntries,
	}
	var projection ProjectionResult
	if _, isObject := input.(*core.Object); isObject {
		projection = document.Project(RequireObject(DuplicatePolicyRequireUnique).
			WithLimits(projectionLimits))
	} else {
		projection = document.Project(BestExactEntryMapping().WithLimits(projectionLimits))
	}
	switch {
	case projection.Complete != nil && core.Equal(projection.Complete.Value, input):
		return nil
	case projection.Failed != nil && len(projection.Failed.Diagnostics) > 0 &&
		projection.Failed.Diagnostics[0].Code == "core.projection.resource-limit@1":
		name := projection.Failed.Diagnostics[0].Arguments["limit"]
		switch name {
		case "max_source_associations", "max_value_nodes":
			return &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "input-nodes"}
		case "max_report_entries":
			return &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "report-entries"}
		case "max_provenance_units":
			return &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "provenance-entries"}
		default:
			return &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "projection"}
		}
	default:
		return &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
}

// buildProvenance maps every input location to its materialized outputs
// (materialization.rs:397-468).
func buildProvenance(inputEntries []inputEntry, formed *Document,
	limits document.MaterializationLimits) (MaterializationProvenanceMap, *MaterializationFailure) {
	if len(inputEntries) != len(formed.properties) {
		return MaterializationProvenanceMap{}, &MaterializationFailure{
			Kind: MaterializationFormationFailed}
	}
	entries := make([]MaterializationProvenanceEntry, 0, len(inputEntries)*3+1)
	units := 0
	add := func(input MaterializationInputLocation, node document.NodeRef,
		spans []document.Span) *MaterializationFailure {
		if len(spans) == 0 {
			return &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
		units += 1 + len(spans)
		if units > limits.MaxProvenanceEntries {
			return &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "provenance-entries"}
		}
		outputs := make([]MaterializedOrigin, 0, len(spans))
		for _, span := range spans {
			outputs = append(outputs, MaterializedOrigin{
				Snapshot: formed.SnapshotIdentity(),
				Node:     node,
				Span:     span,
				Relation: MaterializationRelationReencoded,
			})
		}
		entries = append(entries, MaterializationProvenanceEntry{
			Input:   input,
			Outputs: outputs,
		})
		return nil
	}
	rootSpan, err := formed.authority.Span(0, formed.source.Len())
	if err != nil {
		return MaterializationProvenanceMap{}, &MaterializationFailure{
			Kind: MaterializationFormationFailed}
	}
	if failure := add(MaterializationInputLocation{Kind: "Value",
		Path: protocol.RootValuePath()}, formed.NodeRef(), []document.Span{rootSpan}); failure != nil {
		return MaterializationProvenanceMap{}, failure
	}
	for index, property := range formed.properties {
		input := inputEntries[index]
		if failure := add(input.association, property.node,
			[]document.Span{property.span}); failure != nil {
			return MaterializationProvenanceMap{}, failure
		}
		keySpans := property.keyFragments
		if len(keySpans) == 0 {
			keySpans = []document.Span{property.keyAnchor}
		}
		if failure := add(input.key, property.node, keySpans); failure != nil {
			return MaterializationProvenanceMap{}, failure
		}
		valueSpans := property.valueFragments
		if len(valueSpans) == 0 {
			valueSpans = []document.Span{property.valueAnchor}
		}
		if failure := add(input.value, property.node, valueSpans); failure != nil {
			return MaterializationProvenanceMap{}, failure
		}
	}
	return MaterializationProvenanceMap{entries: entries}, nil
}

// textBudget projects the raw byte budget onto the text budget
// (materialization.rs:520-534).
func textBudget(encoding document.SourceEncoding, maxOutputBytes int) (int, *MaterializationFailure) {
	switch encoding.Kind() {
	case document.EncodingUtf16Le, document.EncodingUtf16Be, document.EncodingLatin1:
		return maxOutputBytes * 2, nil
	case document.EncodingWindowsCodePage:
		if page, ok := encoding.WindowsCodePage(); ok && page.Number() != 65001 {
			return maxOutputBytes * 3, nil
		}
		return maxOutputBytes, nil
	case document.EncodingUtf8:
		return maxOutputBytes, nil
	}
	return 0, &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
}

// encodeText encodes the assembled text into the target encoding with the
// matching BOM (materialization.rs:536-564).
func encodeText(text string, encoding document.SourceEncoding,
	maxOutputBytes int) ([]byte, *MaterializationFailure) {
	bomBytes := 0
	if encoding.Kind() == document.EncodingUtf16Le || encoding.Kind() == document.EncodingUtf16Be {
		bomBytes = 2
	}
	fragmentLimit := maxOutputBytes - bomBytes
	if fragmentLimit < 0 {
		return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "output-bytes"}
	}
	fragment, failure := encodeFragment(text, encoding, fragmentLimit)
	if failure != nil {
		return nil, failure
	}
	if bomBytes == 0 {
		return fragment, nil
	}
	var output []byte
	if encoding.Kind() == document.EncodingUtf16Le {
		output = append(output, 0xFF, 0xFE)
	} else {
		output = append(output, 0xFE, 0xFF)
	}
	return append(output, fragment...), nil
}

// encodeFragment encodes one text fragment under one exact encoding
// (materialization.rs:566-631).
func encodeFragment(text string, encoding document.SourceEncoding,
	maxOutputBytes int) ([]byte, *MaterializationFailure) {
	var output []byte
	switch encoding.Kind() {
	case document.EncodingUtf8:
		if len(text) > maxOutputBytes {
			return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "output-bytes"}
		}
		output = []byte(text)
	case document.EncodingUtf16Le, document.EncodingUtf16Be:
		units := 0
		for _, character := range text {
			if character > 0xFFFF {
				units += 2
			} else {
				units++
			}
		}
		if units*2 > maxOutputBytes {
			return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "output-bytes"}
		}
		littleEndian := encoding.Kind() == document.EncodingUtf16Le
		for _, character := range text {
			if character > 0xFFFF {
				first := character - 0x10000
				output = appendUTF16(output, uint16(0xD800+(first>>10)), littleEndian)
				output = appendUTF16(output, uint16(0xDC00+(first&0x3FF)), littleEndian)
				continue
			}
			output = appendUTF16(output, uint16(character), littleEndian)
		}
	case document.EncodingLatin1:
		if len([]rune(text)) > maxOutputBytes {
			return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "output-bytes"}
		}
		for _, character := range text {
			if character > 0xFF {
				return nil, &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
			}
			output = append(output, byte(character))
		}
	case document.EncodingWindowsCodePage:
		page, ok := encoding.WindowsCodePage()
		if !ok {
			return nil, &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
		}
		encoded, ok := encodeCodePage(text, page.Number())
		if !ok {
			return nil, &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
		}
		output = encoded
	default:
		return nil, &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
	}
	if len(output) > maxOutputBytes {
		return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "output-bytes"}
	}
	return output, nil
}

func appendUTF16(output []byte, unit uint16, littleEndian bool) []byte {
	if littleEndian {
		return append(output, byte(unit), byte(unit>>8))
	}
	return append(output, byte(unit>>8), byte(unit))
}

// encodeCodePage encodes one text fragment through the frozen Windows code
// page data (CP65001 decodes as UTF-8; the DBCS pages CP936/CP949/CP950
// are recognized but not yet encodable).
func encodeCodePage(text string, number uint16) ([]byte, bool) {
	switch number {
	case 65001:
		return []byte(text), true
	case 874, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258:
		table := singleByteEncodeTables[number]
		if table == nil {
			return nil, false
		}
		output := make([]byte, 0, len(text))
		for _, character := range text {
			if character <= 0x7F {
				output = append(output, byte(character))
				continue
			}
			scalar, ok := encodeScalarLookup(table, uint16(character))
			if !ok {
				return nil, false
			}
			output = append(output, scalar)
		}
		return output, true
	case 932:
		return encodeCP932(text)
	}
	return nil, false
}

// encodeScalarLookup resolves one scalar through a sorted encode table.
func encodeScalarLookup(table []encodePair, scalar uint16) (byte, bool) {
	index := sort.Search(len(table), func(i int) bool { return table[i].scalar >= scalar })
	if index < len(table) && table[index].scalar == scalar {
		return table[index].byte, true
	}
	return 0, false
}

// encodeCP932 encodes one text fragment through the frozen Microsoft CP932
// mapping: ASCII identity, half-width katakana single bytes, then the
// sorted two-byte table.
func encodeCP932(text string) ([]byte, bool) {
	output := make([]byte, 0, len(text)*2)
	for _, character := range text {
		switch {
		case character <= 0x7F:
			output = append(output, byte(character))
		case character >= 0xFF61 && character <= 0xFF9F:
			output = append(output, byte(0xA1+character-0xFF61))
		default:
			if character > 0xFFFF {
				return nil, false
			}
			index := sort.Search(len(cp932EncodeTable), func(i int) bool {
				return cp932EncodeTable[i].scalar >= uint16(character)
			})
			if index >= len(cp932EncodeTable) || cp932EncodeTable[index].scalar != uint16(character) {
				return nil, false
			}
			code := cp932EncodeTable[index].code
			output = append(output, byte(code>>8), byte(code))
		}
	}
	return output, true
}

// isControlScalar mirrors the Rust `char::is_control` classification
// (Unicode category Cc: U+0000-U+001F and U+007F-U+009F).
func isControlScalar(character rune) bool {
	return character < 0x20 || (character >= 0x7F && character <= 0x9F)
}

func kindNameOf(value core.Value) string {
	switch value.(type) {
	case core.Null:
		return "Null"
	case core.Boolean:
		return "Boolean"
	case core.Integer:
		return "Integer"
	case core.Decimal:
		return "Decimal"
	case core.BinaryFloat32:
		return "BinaryFloat32"
	case core.BinaryFloat64:
		return "BinaryFloat64"
	case core.String:
		return "String"
	case core.Bytes:
		return "Bytes"
	case core.Date:
		return "Date"
	case core.Time:
		return "Time"
	case core.LocalDateTime:
		return "LocalDateTime"
	case core.OffsetDateTime:
		return "OffsetDateTime"
	case *core.Array:
		return "Sequence"
	case *core.Object:
		return "Object"
	case *core.EntryMapping:
		return "EntryMapping"
	}
	return "Unknown"
}
