package hcl

import (
	"math/big"
	"strings"

	"consema.dev/consema/core"
	"consema.dev/consema/document"
	"consema.dev/consema/protocol"
)

// This file implements the canonical `hcl.canonical-document@1`
// materialization (RFC 0014 §9).
//
// Materialization consumes one validated `hcl.body@1` record and creates a
// new `hcl.native@1` or `hcl.tfvars@1` Document. It is not a formatter for
// an existing source: the input is the projected body record, the output
// is a new snapshot whose complete native model equals the promised input
// semantics (RFC 0014 §9).
//
// The style emits UTF-8 without BOM, LF line endings, two-space
// indentation per body nesting level, `name = value` attributes, block
// headers as `type "label" {`, and a trailing newline after the final
// item. The generated bytes are reparsed under the promised Profile and
// the reparsed native model is compared to the promised input semantics —
// numbers by canonical-decimal value equality, everything else by the
// structural equality of RFC 0014 §6. Failure returns no target Document,
// partial bytes, or partial provenance.

// Style identifier `hcl.canonical-document` (RFC 0014 §9).
const styleCanonical = "hcl.canonical-document"

// Sentinel attribute name of the standalone expression parse; any text
// that would parse into an additional body item is not one expression.
const sentinelAttribute = "expr"

// MaterializationFailureKind is the stable materialization failure
// category (consema-document materialization.rs; RFC 0014 §9).
type MaterializationFailureKind uint8

// The closed materialization failure categories.
const (
	// MaterializationFailureInvalidRequest: request or record fields are
	// contradictory or the record is not `hcl.body@1`.
	MaterializationFailureInvalidRequest MaterializationFailureKind = iota
	// MaterializationFailureUnsupportedProfile: the target profile is
	// unavailable.
	MaterializationFailureUnsupportedProfile
	// MaterializationFailureUnsupportedStyle: the target style is
	// unavailable for the profile.
	MaterializationFailureUnsupportedStyle
	// MaterializationFailureUnsupportedEncoding: the target encoding is
	// unsupported.
	MaterializationFailureUnsupportedEncoding
	// MaterializationFailureUnsupportedNewline: the target style does not
	// support the newline policy.
	MaterializationFailureUnsupportedNewline
	// MaterializationFailureUnrepresentable: a portable input cannot be
	// represented by the target profile (the tfvars block restriction,
	// invalid identifiers, duplicate attributes, non-finite reals).
	MaterializationFailureUnrepresentable
	// MaterializationFailureResourceLimit: a configured bound was reached;
	// output is not truncated to success.
	MaterializationFailureResourceLimit
	// MaterializationFailureFormationFailed: the generated bytes did not
	// form the required target document, or the reparse closure failed.
	MaterializationFailureFormationFailed
)

// MaterializationFailure is the typed materialization failure. It
// implements error and the RFC 0016 §6 Code() contract with the frozen
// registered codes.
type MaterializationFailure struct {
	// Kind identifies the failure.
	Kind MaterializationFailureKind
	// Detail is the stable detail of InvalidRequest.
	Detail string
	// Path is the offending input location of Unrepresentable.
	Path protocol.ValuePath
	// ValueKind is the offending PortableValue kind of Unrepresentable.
	ValueKind core.Kind
	// LimitName is the stable limit name of a ResourceLimit.
	LimitName string
}

// Error implements error.
func (e *MaterializationFailure) Error() string {
	switch e.Kind {
	case MaterializationFailureInvalidRequest:
		return "hcl: materialization request is invalid: " + e.Detail
	case MaterializationFailureUnsupportedProfile:
		return "hcl: materialization profile is unavailable"
	case MaterializationFailureUnsupportedStyle:
		return "hcl: materialization style is unavailable for the profile"
	case MaterializationFailureUnsupportedEncoding:
		return "hcl: materialization encoding is unsupported"
	case MaterializationFailureUnsupportedNewline:
		return "hcl: materialization newline policy is unsupported by the style"
	case MaterializationFailureUnrepresentable:
		return "hcl: portable kind " + e.ValueKind.String() + " is not representable"
	case MaterializationFailureResourceLimit:
		return "hcl: materialization limit " + e.LimitName + " reached"
	case MaterializationFailureFormationFailed:
		return "hcl: generated bytes did not form the target document"
	}
	return "hcl: materialization failure"
}

// Code returns the frozen registered code for the failure (RFC 0014 §9,
// §11). InvalidRequest keeps the runner-facing `invalid-record` spelling
// through Detail; the Code here follows the shared-core mapping.
func (e *MaterializationFailure) Code() string {
	switch e.Kind {
	case MaterializationFailureInvalidRequest:
		return "core.materialization.invalid-request@1"
	case MaterializationFailureUnsupportedProfile:
		return "core.materialization.unsupported-profile@1"
	case MaterializationFailureUnsupportedStyle:
		return "core.materialization.unsupported-style@1"
	case MaterializationFailureUnsupportedEncoding:
		return "core.materialization.unsupported-encoding@1"
	case MaterializationFailureUnsupportedNewline:
		return "core.materialization.unsupported-newline@1"
	case MaterializationFailureUnrepresentable:
		return "hcl.materialization.unrepresentable@1"
	case MaterializationFailureResourceLimit:
		return "hcl.materialization.resource-limit@1"
	case MaterializationFailureFormationFailed:
		return "core.materialization.formation-failed@1"
	}
	return "core.materialization.formation-failed@1"
}

// MaterializationFidelity is the closed materialization fidelity
// (consema-document materialization.rs).
type MaterializationFidelity uint8

// The two frozen fidelity classes.
const (
	// MaterializationFidelityExact means every input fact round-trips
	// through the target's exact projection contract.
	MaterializationFidelityExact MaterializationFidelity = iota
	// MaterializationFidelityTransformed means complete semantics survive
	// an explicit reversible re-encoding.
	MaterializationFidelityTransformed
)

// String returns the stable fidelity name.
func (f MaterializationFidelity) String() string {
	switch f {
	case MaterializationFidelityExact:
		return "Exact"
	case MaterializationFidelityTransformed:
		return "Transformed"
	}
	return "Exact"
}

// MaterializationRelation is the source-to-output relation of one
// materialization provenance origin.
type MaterializationRelation string

// The three frozen relations.
const (
	// MaterializationRelationDirect is a direct native semantic origin.
	MaterializationRelationDirect MaterializationRelation = "Direct"
	// MaterializationRelationGenerated is a generated structural origin.
	MaterializationRelationGenerated MaterializationRelation = "Generated"
	// MaterializationRelationReencoded is a reversible re-encoding origin.
	MaterializationRelationReencoded MaterializationRelation = "Reencoded"
)

// MaterializedOrigin is one exact output origin.
type MaterializedOrigin struct {
	// Snapshot is the target document snapshot.
	Snapshot document.SnapshotIdentity
	// Node is the exact output structural identity.
	Node document.NodeRef
	// Span is the exact output source range.
	Span document.Span
	// Relation is the source relation.
	Relation MaterializationRelation
}

// MaterializationInputLocation is one input value or association location.
type MaterializationInputLocation struct {
	// IsAssociation reports whether the location is an association.
	IsAssociation bool
	// Path is the input value location.
	Path protocol.ValuePath
	// Association is the input association location.
	Association protocol.AssociationLocation
}

// MaterializationProvenanceEntry is one input-to-outputs mapping entry.
type MaterializationProvenanceEntry struct {
	// Input is the exact input location.
	Input MaterializationInputLocation
	// Outputs are the output origins.
	Outputs []MaterializedOrigin
}

// MaterializationProvenanceMap is the immutable input-to-output
// provenance map.
type MaterializationProvenanceMap struct {
	entries []MaterializationProvenanceEntry
}

// Entries returns the ordered entries. The returned slice is a copy.
func (m *MaterializationProvenanceMap) Entries() []MaterializationProvenanceEntry {
	return append([]MaterializationProvenanceEntry(nil), m.entries...)
}

// MaterializationReport is the complete materialization report; HCL v1
// materialization never transforms, so the report is empty.
type MaterializationReport struct {
	events []*protocol.Diagnostic
}

// Events returns the ordered report events. The returned slice is a copy.
func (r *MaterializationReport) Events() []*protocol.Diagnostic {
	return append([]*protocol.Diagnostic(nil), r.events...)
}

// CompleteMaterialization is the complete successful materialization.
type CompleteMaterialization struct {
	// Document is the new immutable target document.
	Document *Document
	// Fidelity is the worst fidelity of the whole operation.
	Fidelity MaterializationFidelity
	// Report is the transformation/loss report.
	Report MaterializationReport
	// Provenance is the input-to-output provenance map.
	Provenance MaterializationProvenanceMap
}

// FailedMaterializationAttempt is a failed attempt without a document.
type FailedMaterializationAttempt struct {
	// Failure is the stable failure.
	Failure *MaterializationFailure
	// Report holds the events discovered before the failed completion
	// check.
	Report MaterializationReport
	// AnalyzedInputPaths are the stable path descriptions of locally
	// analyzed input regions.
	AnalyzedInputPaths []protocol.ValuePath
}

// MaterializationResult is the sealed materialization outcome: exactly one
// of Complete or Failed is set.
type MaterializationResult struct {
	// Complete is the successful outcome.
	Complete *CompleteMaterialization
	// Failed is the failed attempt.
	Failed *FailedMaterializationAttempt
}

// Materialize materializes one validated `hcl.body@1` record into a new
// canonical HCL document (RFC 0014 §9).
//
// The requested profile selects the output semantics: `hcl.tfvars@1`
// rejects any record containing a block with
// `hcl.materialization.unrepresentable@1`. The generated bytes are
// reparsed under the promised Profile and the reparsed native model is
// compared to the promised input semantics; failure returns no target
// Document, no partial bytes, and no partial provenance.
func Materialize(value core.Value, request document.MaterializationRequest) MaterializationResult {
	analyzed := make([]protocol.ValuePath, 0, 16)
	complete, failure := materializeComplete(value, request, &analyzed)
	if failure != nil {
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure:            failure,
			Report:             MaterializationReport{},
			AnalyzedInputPaths: analyzed,
		}}
	}
	return MaterializationResult{Complete: complete}
}

func materializeComplete(value core.Value, request document.MaterializationRequest,
	analyzed *[]protocol.ValuePath) (*CompleteMaterialization, *MaterializationFailure) {
	target, failure := validateRequest(request)
	if failure != nil {
		return nil, failure
	}
	limits := request.Limits()
	record, failure := validateRecord(value, request, analyzed)
	if failure != nil {
		return nil, failure
	}
	writer := &materializationWriter{limits: limits}
	if failure := writeBody(writer, &record.body, 0); failure != nil {
		return nil, failure
	}
	bytes := []byte(writer.out.String())
	profile := HclProfileNativeV1
	if target == materializationTargetTfvars {
		profile = HclProfileTfvarsV1
	}
	formed, formationFailure := Parse(contextBackground(), bytes, profile,
		HclEncodingSelectionProfileDefault(), parseLimits(limits))
	if formationFailure != nil {
		return nil, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	if formed.status != document.FormationStatusComplete {
		return nil, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	provenance, failure := verifyClosure(record, formed, limits)
	if failure != nil {
		return nil, failure
	}
	return &CompleteMaterialization{
		Document:   formed,
		Fidelity:   MaterializationFidelityExact,
		Report:     MaterializationReport{},
		Provenance: provenance,
	}, nil
}

// materializationTarget is the closed materialization target selection.
type materializationTarget uint8

const (
	materializationTargetNative materializationTarget = iota
	materializationTargetTfvars
)

// validateRequest validates the request against the frozen style contract
// (RFC 0014 §9).
func validateRequest(request document.MaterializationRequest) (materializationTarget, *MaterializationFailure) {
	profile := request.TargetProfile()
	style := request.Style()
	var target materializationTarget
	switch {
	case profile.ID() == "hcl.native" && profile.Version() == 1 && style.ID() == styleCanonical && style.Version() == 1:
		target = materializationTargetNative
	case profile.ID() == "hcl.tfvars" && profile.Version() == 1 && style.ID() == styleCanonical && style.Version() == 1:
		target = materializationTargetTfvars
	case (profile.ID() != "hcl.native" && profile.ID() != "hcl.tfvars") || profile.Version() != 1:
		return 0, &MaterializationFailure{Kind: MaterializationFailureUnsupportedProfile}
	default:
		return 0, &MaterializationFailure{Kind: MaterializationFailureUnsupportedStyle}
	}
	if request.Encoding() != document.Utf8Encoding() {
		return 0, &MaterializationFailure{Kind: MaterializationFailureUnsupportedEncoding}
	}
	if request.Newline() != document.NewlineLf {
		return 0, &MaterializationFailure{Kind: MaterializationFailureUnsupportedNewline}
	}
	return target, nil
}

// parseLimits derives the reparse limits from the request so a bounded
// input cannot fail its own closure (RFC 0014 §9).
func parseLimits(limits document.MaterializationLimits) HclParseLimits {
	return HclParseLimits{
		Common: document.ParseLimits{
			MaxSourceBytes:  limits.MaxOutputBytes,
			MaxNestingDepth: limits.MaxDepth + 2,
			MaxTokenCount:   limits.MaxOutputBytes,
			MaxNodeCount:    limits.MaxOutputBytes,
			MaxDiagnostics:  limits.MaxReportEntries,
		},
		MaxDecodedUTF8Bytes:       limits.MaxOutputBytes * 3,
		MaxDecodedScalars:         limits.MaxOutputBytes,
		MaxBodyDepth:              limits.MaxDepth + 2,
		MaxExpressionDepth:        limits.MaxDepth + 2,
		MaxTemplateDepth:          limits.MaxDepth + 2,
		MaxAttributeCount:         limits.MaxInputNodes,
		MaxBlockCount:             limits.MaxInputNodes,
		MaxLabelCount:             limits.MaxInputNodes,
		MaxBodyItemCount:          limits.MaxInputNodes * 2,
		MaxIdentifierLen:          limits.MaxOutputBytes,
		MaxStringLen:              limits.MaxOutputBytes,
		MaxNumberDigits:           limits.MaxOutputBytes,
		MaxTemplateLen:            limits.MaxOutputBytes,
		MaxTemplateInterpolations: limits.MaxInputNodes,
		MaxHeredocLines:           limits.MaxOutputBytes,
		MaxHeredocBytes:           limits.MaxOutputBytes,
		MaxTupleElements:          limits.MaxInputNodes,
		MaxObjectEntries:          limits.MaxInputNodes,
		MaxForExtent:              limits.MaxInputNodes,
		MaxRecoveryRegions:        limits.MaxReportEntries,
		MaxErrorRegions:           limits.MaxReportEntries,
		MaxSyntaxPieces:           limits.MaxOutputBytes,
		MaxReportEvents:           limits.MaxReportEntries,
	}
}

// promisedExpressionLimits derives the parse limits for one standalone
// expression-text parse from the text length so a bounded text cannot fail
// its own parse (RFC 0014 §8.2 reparse discipline).
func promisedExpressionLimits(textLen int, limits document.MaterializationLimits) HclParseLimits {
	source := textLen + 8
	return HclParseLimits{
		Common: document.ParseLimits{
			MaxSourceBytes:  source,
			MaxNestingDepth: limits.MaxDepth + 2,
			MaxTokenCount:   source * 2,
			MaxNodeCount:    source * 2,
			MaxDiagnostics:  limits.MaxReportEntries,
		},
		MaxDecodedUTF8Bytes:       source * 3,
		MaxDecodedScalars:         source,
		MaxBodyDepth:              4,
		MaxExpressionDepth:        limits.MaxDepth + 2,
		MaxTemplateDepth:          limits.MaxDepth + 2,
		MaxAttributeCount:         8,
		MaxBlockCount:             8,
		MaxLabelCount:             8,
		MaxBodyItemCount:          16,
		MaxIdentifierLen:          source,
		MaxStringLen:              source,
		MaxNumberDigits:           limits.MaxOutputBytes,
		MaxTemplateLen:            source,
		MaxTemplateInterpolations: source,
		MaxHeredocLines:           source,
		MaxHeredocBytes:           source,
		MaxTupleElements:          source,
		MaxObjectEntries:          source,
		MaxForExtent:              source,
		MaxRecoveryRegions:        limits.MaxReportEntries,
		MaxErrorRegions:           limits.MaxReportEntries,
		MaxSyntaxPieces:           source * 2,
		MaxReportEvents:           limits.MaxReportEntries,
	}
}

// materializationRecord is one validated `hcl.body@1` record.
type materializationRecord struct {
	body materializationBody
}

// materializationBody is one validated body: ordered attributes and
// blocks.
type materializationBody struct {
	items []materializationBodyItem
}

// materializationBodyItem is one validated body item.
type materializationBodyItem struct {
	// Attribute payload.
	path  protocol.ValuePath
	name  string
	value materializationValue
	// Block payload.
	blockType string
	labels    []materializationLabel
	body      *materializationBody
	isBlock   bool
}

// materializationLabel is one validated block label; the canonical output
// always quotes it.
type materializationLabel struct {
	text string
}

// materializationValue is one validated value record with its kind
// semantics.
type materializationValue struct {
	kind materializationValueKind
}

// materializationValueKind is the closed validated value kinds.
type materializationValueKind struct {
	tag      materializationValueTag
	text     string
	boolean  bool
	elements []materializationValue
	entries  []materializationObjectEntry
	expr     *promisedExpression
}

type materializationValueTag uint8

// The closed validated value tags.
const (
	valueString materializationValueTag = iota
	valueInteger
	valueReal
	valueBoolean
	valueNull
	valueTuple
	valueObject
	valueExpression
)

// materializationObjectEntry is one validated object-constructor entry.
type materializationObjectEntry struct {
	key   string
	value materializationValue
}

// promisedExpression is one validated `hcl.expression@1` record.
type promisedExpression struct {
	text string
	ast  *HclExpression
}

// materializationValidator applies the input node budget during
// validation.
type materializationValidator struct {
	nodes  int
	limits document.MaterializationLimits
}

func (v *materializationValidator) step() *MaterializationFailure {
	v.nodes++
	if v.nodes > v.limits.MaxInputNodes {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit, LimitName: "input-nodes"}
	}
	return nil
}

// validateRecord validates the record name, the tfvars block restriction,
// the body tree, the input node budget, and the container depth budget.
func validateRecord(value core.Value, request document.MaterializationRequest,
	analyzed *[]protocol.ValuePath) (*materializationRecord, *MaterializationFailure) {
	*analyzed = append(*analyzed, protocol.RootValuePath())
	recordPath := protocol.RootValuePath().Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "record"})
	record, failure := expectStringField(value, "record", &recordPath,
		"input record is missing the record member")
	if failure != nil {
		return nil, failure
	}
	if record != hclBodyRecord {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest,
			Detail: "input record is not hcl.body@1"}
	}
	tfvars := request.TargetProfile() == document.NewProfileId("hcl.tfvars", 1)
	validator := &materializationValidator{limits: request.Limits()}
	body, failure := validateBody(value, protocol.RootValuePath(), validator, analyzed, tfvars, 0)
	if failure != nil {
		return nil, failure
	}
	return &materializationRecord{body: body}, nil
}

// validateBody validates one body record and its items; depth is the
// block nesting level, bounded by the container depth budget.
func validateBody(value core.Value, path protocol.ValuePath,
	validator *materializationValidator, analyzed *[]protocol.ValuePath,
	tfvars bool, depth int) (materializationBody, *MaterializationFailure) {
	itemsPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "items"})
	itemsValue, failure := expectObjectField(value, "items", &itemsPath,
		"input body record is missing the items member")
	if failure != nil {
		return materializationBody{}, failure
	}
	items, ok := itemsValue.(*core.Array)
	if !ok {
		return materializationBody{}, unrepresentableAt(itemsPath, itemsValue.Kind())
	}
	var out []materializationBodyItem
	names := make(map[string]bool)
	for index, item := range items.Items() {
		itemPath := itemsPath.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
		if failure := validator.step(); failure != nil {
			return materializationBody{}, failure
		}
		*analyzed = append(*analyzed, itemPath)
		kindPath := itemPath.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "kind"})
		kind, failure := expectStringField(item, "kind", &kindPath, "body item is missing the kind member")
		if failure != nil {
			return materializationBody{}, failure
		}
		switch kind {
		case "attribute":
			namePath := itemPath.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "name"})
			name, failure := expectStringField(item, "name", &namePath,
				"attribute item is missing the name member")
			if failure != nil {
				return materializationBody{}, failure
			}
			if !isPlainIdentifier(name) {
				return materializationBody{}, unrepresentableAt(namePath, core.KindString)
			}
			// RFC 0014 §3: a second attribute with the same name in one
			// body never forms a Complete document.
			if names[name] {
				return materializationBody{}, unrepresentableAt(itemPath, core.KindString)
			}
			names[name] = true
			valuePath := itemPath.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "value"})
			valueValue, failure := expectObjectField(item, "value", &valuePath,
				"attribute item is missing the value member")
			if failure != nil {
				return materializationBody{}, failure
			}
			value, failure := validateValue(valueValue, &valuePath, validator, analyzed, 0)
			if failure != nil {
				return materializationBody{}, failure
			}
			out = append(out, materializationBodyItem{path: itemPath, name: name, value: value})
		case "block":
			// RFC 0014 §5, §9: the tfvars target admits attribute-only
			// records; the block restriction is checked before the block
			// shape so the record's presence alone fails.
			if tfvars {
				return materializationBody{}, unrepresentableAt(itemPath, core.KindObject)
			}
			if depth+1 > validator.limits.MaxDepth {
				return materializationBody{}, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
					LimitName: "input-depth"}
			}
			typePath := itemPath.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "type"})
			blockType, failure := expectStringField(item, "type", &typePath,
				"block item is missing the type member")
			if failure != nil {
				return materializationBody{}, failure
			}
			if !isPlainIdentifier(blockType) {
				return materializationBody{}, unrepresentableAt(typePath, core.KindString)
			}
			labelsPath := itemPath.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "labels"})
			labelsValue, failure := expectObjectField(item, "labels", &labelsPath,
				"block item is missing the labels member")
			if failure != nil {
				return materializationBody{}, failure
			}
			labelsSequence, ok := labelsValue.(*core.Array)
			if !ok {
				return materializationBody{}, unrepresentableAt(labelsPath, labelsValue.Kind())
			}
			var labels []materializationLabel
			for labelIndex, label := range labelsSequence.Items() {
				labelPath := labelsPath.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(labelIndex)})
				if failure := validator.step(); failure != nil {
					return materializationBody{}, failure
				}
				*analyzed = append(*analyzed, labelPath)
				text, ok := label.(core.String)
				if !ok {
					return materializationBody{}, unrepresentableAt(labelPath, label.Kind())
				}
				if quotedLen(string(text)) > validator.limits.MaxOutputBytes {
					return materializationBody{}, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
						LimitName: "output-bytes"}
				}
				labels = append(labels, materializationLabel{text: string(text)})
			}
			bodyPath := itemPath.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "body"})
			bodyValue, failure := expectObjectField(item, "body", &bodyPath,
				"block item is missing the body member")
			if failure != nil {
				return materializationBody{}, failure
			}
			body, failure := validateBody(bodyValue, bodyPath, validator, analyzed, tfvars, depth+1)
			if failure != nil {
				return materializationBody{}, failure
			}
			out = append(out, materializationBodyItem{
				path: itemPath, blockType: blockType, labels: labels, body: &body, isBlock: true,
			})
		default:
			return materializationBody{}, unrepresentableAt(kindPath, core.KindString)
		}
	}
	return materializationBody{items: out}, nil
}

// validateValue validates one attribute value and its descendants: either
// the RFC 0014 §8.2 typed member itself or the equivalent value record
// with a string `kind` member.
func validateValue(value core.Value, path *protocol.ValuePath,
	validator *materializationValidator, analyzed *[]protocol.ValuePath,
	depth int) (materializationValue, *MaterializationFailure) {
	if failure := validator.step(); failure != nil {
		return materializationValue{}, failure
	}
	*analyzed = append(*analyzed, *path)
	if _, ok := value.(*core.Object); ok {
		return validateObjectValue(value, path, validator, analyzed, depth)
	}
	return validateTypedMember(value, path, validator, analyzed, depth)
}

// validateObjectValue validates one object-form value: the raw
// `hcl.expression@1` record object of a derived expression (RFC 0014 §8.2)
// or the value record with a string `kind` member.
func validateObjectValue(value core.Value, path *protocol.ValuePath,
	validator *materializationValidator, analyzed *[]protocol.ValuePath,
	depth int) (materializationValue, *MaterializationFailure) {
	object := value.(*core.Object)
	if record, ok := object.Get("record"); ok {
		if text, ok := record.(core.String); ok && string(text) == hclExpressionRecord {
			expression, failure := validatePromisedExpression(value, path, validator, analyzed,
				validator.limits)
			if failure != nil {
				return materializationValue{}, failure
			}
			return materializationValue{kind: materializationValueKind{tag: valueExpression, expr: expression}}, nil
		}
	}
	kindPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "kind"})
	kind, failure := expectStringField(value, "kind", &kindPath, "value record is missing the kind member")
	if failure != nil {
		return materializationValue{}, failure
	}
	limits := validator.limits
	switch kind {
	case "string":
		textPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "text"})
		text, failure := expectStringField(value, "text", &textPath,
			"string value record is missing the text member")
		if failure != nil {
			return materializationValue{}, failure
		}
		if quotedLen(text) > limits.MaxOutputBytes {
			return materializationValue{}, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
				LimitName: "output-bytes"}
		}
		return materializationValue{kind: materializationValueKind{tag: valueString, text: text}}, nil
	case "integer":
		payloadPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "value"})
		payload, failure := expectObjectField(value, "value", &payloadPath,
			"integer value record is missing the value member")
		if failure != nil {
			return materializationValue{}, failure
		}
		integer, ok := payload.(core.Integer)
		if !ok {
			return materializationValue{}, unrepresentableAt(payloadPath, payload.Kind())
		}
		spelling := integer.String()
		if len(spelling) > limits.MaxOutputBytes {
			return materializationValue{}, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
				LimitName: "output-bytes"}
		}
		return materializationValue{kind: materializationValueKind{tag: valueInteger, text: spelling}}, nil
	case "real":
		payloadPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "value"})
		payload, failure := expectObjectField(value, "value", &payloadPath,
			"real value record is missing the value member")
		if failure != nil {
			return materializationValue{}, failure
		}
		spelling, failure := realSpelling(payload, path, limits)
		if failure != nil {
			return materializationValue{}, failure
		}
		if len(spelling) > limits.MaxOutputBytes {
			return materializationValue{}, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
				LimitName: "output-bytes"}
		}
		return materializationValue{kind: materializationValueKind{tag: valueReal, text: spelling}}, nil
	case "boolean":
		payloadPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "value"})
		payload, failure := expectObjectField(value, "value", &payloadPath,
			"boolean value record is missing the value member")
		if failure != nil {
			return materializationValue{}, failure
		}
		flag, ok := payload.(core.Boolean)
		if !ok {
			return materializationValue{}, unrepresentableAt(payloadPath, payload.Kind())
		}
		return materializationValue{kind: materializationValueKind{tag: valueBoolean, boolean: bool(flag)}}, nil
	case "null":
		return materializationValue{kind: materializationValueKind{tag: valueNull}}, nil
	case "tuple":
		if depth+1 > limits.MaxDepth {
			return materializationValue{}, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
				LimitName: "input-depth"}
		}
		elementsPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "elements"})
		elementsValue, failure := expectObjectField(value, "elements", &elementsPath,
			"tuple value record is missing the elements member")
		if failure != nil {
			return materializationValue{}, failure
		}
		elements, ok := elementsValue.(*core.Array)
		if !ok {
			return materializationValue{}, unrepresentableAt(elementsPath, elementsValue.Kind())
		}
		var out []materializationValue
		for index, element := range elements.Items() {
			elementPath := elementsPath.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
			value, failure := validateValue(element, &elementPath, validator, analyzed, depth+1)
			if failure != nil {
				return materializationValue{}, failure
			}
			out = append(out, value)
		}
		return materializationValue{kind: materializationValueKind{tag: valueTuple, elements: out}}, nil
	case "object":
		if depth+1 > limits.MaxDepth {
			return materializationValue{}, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
				LimitName: "input-depth"}
		}
		entriesPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "entries"})
		entriesValue, failure := expectObjectField(value, "entries", &entriesPath,
			"object value record is missing the entries member")
		if failure != nil {
			return materializationValue{}, failure
		}
		entries, ok := entriesValue.(*core.Array)
		if !ok {
			return materializationValue{}, unrepresentableAt(entriesPath, entriesValue.Kind())
		}
		var out []materializationObjectEntry
		for index, entry := range entries.Items() {
			entryPath := entriesPath.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
			pair, ok := entry.(*core.Array)
			if !ok || len(pair.Items()) != 2 {
				return materializationValue{}, unrepresentableAt(entryPath, entry.Kind())
			}
			keyPath := entryPath.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: 0})
			key, ok := pair.Items()[0].(core.String)
			if !ok {
				return materializationValue{}, unrepresentableAt(keyPath, pair.Items()[0].Kind())
			}
			valuePath := entryPath.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: 1})
			value, failure := validateValue(pair.Items()[1], &valuePath, validator, analyzed, depth+1)
			if failure != nil {
				return materializationValue{}, failure
			}
			out = append(out, materializationObjectEntry{key: string(key), value: value})
		}
		return materializationValue{kind: materializationValueKind{tag: valueObject, entries: out}}, nil
	case "expression":
		expressionPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "expression"})
		expressionValue, failure := expectObjectField(value, "expression", &expressionPath,
			"expression value record is missing the expression member")
		if failure != nil {
			return materializationValue{}, failure
		}
		expression, failure := validatePromisedExpression(expressionValue, &expressionPath,
			validator, analyzed, limits)
		if failure != nil {
			return materializationValue{}, failure
		}
		return materializationValue{kind: materializationValueKind{tag: valueExpression, expr: expression}}, nil
	default:
		return materializationValue{}, unrepresentableAt(kindPath, core.KindString)
	}
}

// validateTypedMember validates one raw RFC 0014 §8.2 typed member exactly
// as the body projection publishes attribute values.
func validateTypedMember(value core.Value, path *protocol.ValuePath,
	validator *materializationValidator, analyzed *[]protocol.ValuePath,
	depth int) (materializationValue, *MaterializationFailure) {
	limits := validator.limits
	switch value.Kind() {
	case core.KindString:
		text := string(value.(core.String))
		if quotedLen(text) > limits.MaxOutputBytes {
			return materializationValue{}, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
				LimitName: "output-bytes"}
		}
		return materializationValue{kind: materializationValueKind{tag: valueString, text: text}}, nil
	case core.KindInteger:
		spelling := value.(core.Integer).String()
		if len(spelling) > limits.MaxOutputBytes {
			return materializationValue{}, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
				LimitName: "output-bytes"}
		}
		return materializationValue{kind: materializationValueKind{tag: valueInteger, text: spelling}}, nil
	case core.KindDecimal, core.KindBinaryFloat64, core.KindBinaryFloat32:
		spelling, failure := realSpelling(value, path, limits)
		if failure != nil {
			return materializationValue{}, failure
		}
		if len(spelling) > limits.MaxOutputBytes {
			return materializationValue{}, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
				LimitName: "output-bytes"}
		}
		return materializationValue{kind: materializationValueKind{tag: valueReal, text: spelling}}, nil
	case core.KindBoolean:
		return materializationValue{kind: materializationValueKind{
			tag: valueBoolean, boolean: bool(value.(core.Boolean))}}, nil
	case core.KindNull:
		return materializationValue{kind: materializationValueKind{tag: valueNull}}, nil
	case core.KindArray:
		if depth+1 > limits.MaxDepth {
			return materializationValue{}, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
				LimitName: "input-depth"}
		}
		var out []materializationValue
		for index, element := range value.(*core.Array).Items() {
			elementPath := path.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
			value, failure := validateValue(element, &elementPath, validator, analyzed, depth+1)
			if failure != nil {
				return materializationValue{}, failure
			}
			out = append(out, value)
		}
		return materializationValue{kind: materializationValueKind{tag: valueTuple, elements: out}}, nil
	case core.KindEntryMapping:
		if depth+1 > limits.MaxDepth {
			return materializationValue{}, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
				LimitName: "input-depth"}
		}
		var out []materializationObjectEntry
		for index, entry := range value.(*core.EntryMapping).Entries() {
			entryPath := path.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
			key, ok := entry.Key.(core.String)
			if !ok {
				return materializationValue{}, unrepresentableAt(entryPath, entry.Key.Kind())
			}
			valuePath := entryPath.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: 1})
			value, failure := validateValue(entry.Value, &valuePath, validator, analyzed, depth+1)
			if failure != nil {
				return materializationValue{}, failure
			}
			out = append(out, materializationObjectEntry{key: string(key), value: value})
		}
		return materializationValue{kind: materializationValueKind{tag: valueObject, entries: out}}, nil
	default:
		// Bytes, date, and time datums have no HCL spelling (RFC 0014 §8.2).
		return materializationValue{}, unrepresentableAt(*path, value.Kind())
	}
}

// realSpelling resolves one real payload onto its exact canonical decimal
// spelling (RFC 0014 §9).
func realSpelling(payload core.Value, path *protocol.ValuePath,
	limits document.MaterializationLimits) (string, *MaterializationFailure) {
	switch value := payload.(type) {
	case core.BinaryFloat64:
		spelling, ok := doubleToCanonicalDecimal(uint64(value))
		if !ok {
			return "", unrepresentableAt(*path, core.KindBinaryFloat64)
		}
		return spelling, nil
	case core.Decimal:
		return renderDecimal(&value, limits)
	case core.BinaryFloat32:
		spelling, ok := doubleToCanonicalDecimal(uint64(mathFloat32BitsToFloat64Bits(uint32(value))))
		if !ok {
			return "", unrepresentableAt(*path, core.KindBinaryFloat32)
		}
		return spelling, nil
	}
	return "", unrepresentableAt(*path, payload.Kind())
}

// validatePromisedExpression validates one `hcl.expression@1` record: the
// text must parse standalone as one complete expression whose structural
// kind spelling matches the record's `kind`, and an optional `fingerprint`
// field must equal the parsed expression's structural fingerprint (RFC
// 0014 §8.2, §9).
func validatePromisedExpression(value core.Value, path *protocol.ValuePath,
	validator *materializationValidator, analyzed *[]protocol.ValuePath,
	limits document.MaterializationLimits) (*promisedExpression, *MaterializationFailure) {
	if failure := validator.step(); failure != nil {
		return nil, failure
	}
	*analyzed = append(*analyzed, *path)
	recordPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "record"})
	record, failure := expectStringField(value, "record", &recordPath,
		"expression record is missing the record member")
	if failure != nil {
		return nil, failure
	}
	if record != hclExpressionRecord {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest,
			Detail: "input expression is not hcl.expression@1"}
	}
	kindPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "kind"})
	kind, failure := expectStringField(value, "kind", &kindPath,
		"expression record is missing the kind member")
	if failure != nil {
		return nil, failure
	}
	textPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "text"})
	text, failure := expectStringField(value, "text", &textPath,
		"expression record is missing the text member")
	if failure != nil {
		return nil, failure
	}
	if len(text) > limits.MaxOutputBytes {
		return nil, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
			LimitName: "output-bytes"}
	}
	ast, failure := promisedExpressionParse(text, limits)
	if failure != nil {
		return nil, failure
	}
	if expressionKindSpelling(ast) != kind {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest,
			Detail: "expression kind does not match text"}
	}
	object, ok := value.(*core.Object)
	if !ok {
		return nil, unrepresentableAt(*path, value.Kind())
	}
	if fingerprintValue, ok := object.Get("fingerprint"); ok {
		fingerprintPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "fingerprint"})
		fingerprint, ok := fingerprintValue.(core.String)
		if !ok {
			return nil, unrepresentableAt(fingerprintPath, fingerprintValue.Kind())
		}
		if string(fingerprint) != expressionFingerprint(ast) {
			return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest,
				Detail: "expression fingerprint mismatch"}
		}
	}
	return &promisedExpression{text: text, ast: ast}, nil
}

// promisedExpressionParse parses one expression text standalone by
// wrapping it in one sentinel attribute and requiring the parse to yield
// exactly that attribute (RFC 0014 §8.2 reparse discipline).
func promisedExpressionParse(text string, limits document.MaterializationLimits) (*HclExpression, *MaterializationFailure) {
	source := sentinelAttribute + " = " + text + "\n"
	formed, formationFailure := Parse(contextBackground(), []byte(source),
		HclProfileNativeV1, HclEncodingSelectionProfileDefault(),
		promisedExpressionLimits(len(text), limits))
	if formationFailure != nil {
		return nil, &MaterializationFailure{Kind: MaterializationFailureResourceLimit,
			LimitName: "input-depth"}
	}
	if formed.status != document.FormationStatusComplete {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest,
			Detail: "expression text does not parse"}
	}
	items := formed.document.body.items
	if len(items) != 1 {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest,
			Detail: "expression text does not parse"}
	}
	attribute := items[0].AsAttribute()
	if attribute == nil || attribute.name != sentinelAttribute {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest,
			Detail: "expression text does not parse"}
	}
	return attribute.expression, nil
}

// expressionKindSpelling is the stable structural kind spelling of the
// `hcl.expression@1` record (RFC 0014 §8.2); the one spelling authority is
// the projection's kindFamily mapping.
func expressionKindSpelling(expression *HclExpression) string {
	return kindFamily(expression.kind.Name())
}

// materializationWriter is the bounded canonical emitter.
type materializationWriter struct {
	out    strings.Builder
	limits document.MaterializationLimits
}

// push appends one chunk after bounding the total output.
func (w *materializationWriter) push(text string) *MaterializationFailure {
	if w.out.Len()+len(text) > w.limits.MaxOutputBytes {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit, LimitName: "output-bytes"}
	}
	w.out.WriteString(text)
	return nil
}

// indent appends one body-nesting indentation level of two spaces.
func (w *materializationWriter) indent(depth int) *MaterializationFailure {
	for i := 0; i < depth; i++ {
		if failure := w.push("  "); failure != nil {
			return failure
		}
	}
	return nil
}

// pushQuoted appends one double-quoted string with minimal deterministic
// escapes (RFC 0014 §9).
func (w *materializationWriter) pushQuoted(text string) *MaterializationFailure {
	if failure := w.push("\""); failure != nil {
		return failure
	}
	if failure := w.push(escapeText(text)); failure != nil {
		return failure
	}
	return w.push("\"")
}

// writeBody emits one body at the given block-nesting depth.
func writeBody(writer *materializationWriter, body *materializationBody, depth int) *MaterializationFailure {
	for _, item := range body.items {
		if !item.isBlock {
			if failure := writer.indent(depth); failure != nil {
				return failure
			}
			if failure := writer.push(item.name); failure != nil {
				return failure
			}
			if failure := writer.push(" = "); failure != nil {
				return failure
			}
			if failure := writeValue(writer, &item.value, depth); failure != nil {
				return failure
			}
			if failure := writer.push("\n"); failure != nil {
				return failure
			}
			continue
		}
		if failure := writer.indent(depth); failure != nil {
			return failure
		}
		if failure := writer.push(item.blockType); failure != nil {
			return failure
		}
		for _, label := range item.labels {
			if failure := writer.push(" "); failure != nil {
				return failure
			}
			if failure := writer.pushQuoted(label.text); failure != nil {
				return failure
			}
		}
		if failure := writer.push(" {\n"); failure != nil {
			return failure
		}
		if failure := writeBody(writer, item.body, depth+1); failure != nil {
			return failure
		}
		if failure := writer.indent(depth); failure != nil {
			return failure
		}
		if failure := writer.push("}\n"); failure != nil {
			return failure
		}
	}
	return nil
}

// writeValue emits one attribute value at the given indentation depth.
func writeValue(writer *materializationWriter, value *materializationValue, depth int) *MaterializationFailure {
	kind := value.kind
	switch kind.tag {
	case valueString:
		return writer.pushQuoted(kind.text)
	case valueInteger, valueReal:
		return writer.push(kind.text)
	case valueBoolean:
		if kind.boolean {
			return writer.push("true")
		}
		return writer.push("false")
	case valueNull:
		return writer.push("null")
	case valueTuple:
		if len(kind.elements) == 0 {
			return writer.push("[]")
		}
		if failure := writer.push("[\n"); failure != nil {
			return failure
		}
		last := len(kind.elements) - 1
		for index := range kind.elements {
			if failure := writer.indent(depth + 1); failure != nil {
				return failure
			}
			if failure := writeValue(writer, &kind.elements[index], depth+1); failure != nil {
				return failure
			}
			if index == last {
				if failure := writer.push("\n"); failure != nil {
					return failure
				}
			} else if failure := writer.push(",\n"); failure != nil {
				return failure
			}
		}
		if failure := writer.indent(depth); failure != nil {
			return failure
		}
		return writer.push("]")
	case valueObject:
		if len(kind.entries) == 0 {
			return writer.push("{}")
		}
		if failure := writer.push("{\n"); failure != nil {
			return failure
		}
		last := len(kind.entries) - 1
		for index := range kind.entries {
			if failure := writer.indent(depth + 1); failure != nil {
				return failure
			}
			if failure := writeObjectKey(writer, kind.entries[index].key); failure != nil {
				return failure
			}
			if failure := writer.push(" = "); failure != nil {
				return failure
			}
			if failure := writeValue(writer, &kind.entries[index].value, depth+1); failure != nil {
				return failure
			}
			if index == last {
				if failure := writer.push("\n"); failure != nil {
					return failure
				}
			} else if failure := writer.push(",\n"); failure != nil {
				return failure
			}
		}
		if failure := writer.indent(depth); failure != nil {
			return failure
		}
		return writer.push("}")
	case valueExpression:
		return writer.push(kind.expr.text)
	}
	return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
}

// writeObjectKey emits one object key: bare for a plain identifier other
// than the contextual `for` (which would trigger the for-expression
// reading, RFC 0014 §4.6), else quoted.
func writeObjectKey(writer *materializationWriter, key string) *MaterializationFailure {
	if isPlainIdentifier(key) && key != "for" {
		return writer.push(key)
	}
	return writer.pushQuoted(key)
}

// isPlainIdentifier reports whether one text is a valid UAX #31
// identifier with the frozen hyphen continuation and the underscore
// exclusion at the start (RFC 0014 §4.1, §12 D-4), matching the lexer's
// own rule.
func isPlainIdentifier(text string) bool {
	if text == "" {
		return false
	}
	first, width := decodeRune(text)
	if first == '_' || !isIdentifierStart(first) {
		return false
	}
	for offset := width; offset < len(text); {
		ch, w := decodeRune(text[offset:])
		if !isIdentifierContinue(ch) && ch != '-' {
			return false
		}
		offset += w
	}
	return true
}

// isEscapedControl reports whether one character is escaped as `\uNNNN` in
// canonical output: the C0 controls other than the three named escapes,
// DEL, and the C1 controls (RFC 0014 §9 "control characters").
func isEscapedControl(character rune) bool {
	value := uint32(character)
	return value < 0x20 || (value >= 0x7F && value <= 0x9F)
}

// escapeText escapes one string with the minimal deterministic escape set
// (RFC 0014 §9): `\n`, `\r`, `\t`, `\"`, `\\`, `\uNNNN` for control
// characters, and the `$${`/`%%{` doubling for the template openers.
//
// The `$`/`%` rule inverts the template-literal decoding exactly: a run of
// k dollars followed by `{` decodes to k dollars followed by `{`, so a run
// of k dollars followed by `{` is emitted with k + 1 dollars, and any
// other run is emitted verbatim.
func escapeText(text string) string {
	var out strings.Builder
	out.Grow(len(text))
	index := 0
	for index < len(text) {
		byte := text[index]
		if byte == '$' || byte == '%' {
			run := 1
			for index+run < len(text) && text[index+run] == byte {
				run++
			}
			doubled := index+run < len(text) && text[index+run] == '{'
			for i := 0; i < run; i++ {
				out.WriteByte(byte)
			}
			if doubled {
				out.WriteByte(byte)
			}
			index += run
			continue
		}
		character, width := decodeRune(text[index:])
		switch character {
		case '"':
			out.WriteString(`\"`)
		case '\\':
			out.WriteString(`\\`)
		case '\n':
			out.WriteString(`\n`)
		case '\r':
			out.WriteString(`\r`)
		case '\t':
			out.WriteString(`\t`)
		default:
			if isEscapedControl(character) {
				out.WriteString(escapeLowerHex(character))
			} else {
				out.WriteRune(character)
			}
		}
		index += width
	}
	return out.String()
}

// escapeLowerHex renders one \u00xx escape with lowercase hex digits (the
// materialization writer spelling).
func escapeLowerHex(character rune) string {
	const digits = "0123456789abcdef"
	value := uint32(character)
	return "\\u" + string([]byte{
		digits[(value>>12)&0xf], digits[(value>>8)&0xf], digits[(value>>4)&0xf], digits[value&0xf],
	})
}

// quotedLen is the byte length of the double-quoted, minimally escaped
// spelling of one text.
func quotedLen(text string) int {
	return len(escapeText(text)) + 2
}

// renderDecimal renders one normalized decimal as its plain canonical
// spelling: the coefficient digits with the exponent folded into the
// decimal point position, `"0"` for zero (RFC 0014 §9).
func renderDecimal(decimal *core.Decimal, limits document.MaterializationLimits) (string, *MaterializationFailure) {
	coefficient := decimal.Coefficient()
	if coefficient.Sign() == 0 {
		return "0", nil
	}
	if len(coefficient.Text(10))*3 > limits.MaxOutputBytes {
		return "", &MaterializationFailure{Kind: MaterializationFailureResourceLimit, LimitName: "output-bytes"}
	}
	exponent := decimal.Exponent()
	if !exponent.IsInt64() {
		return "", &MaterializationFailure{Kind: MaterializationFailureResourceLimit, LimitName: "output-bytes"}
	}
	exponentValue := exponent.Int64()
	digits := coefficient.String()
	planned := plannedDecimalLen(digits, exponentValue)
	if planned > limits.MaxOutputBytes {
		return "", &MaterializationFailure{Kind: MaterializationFailureResourceLimit, LimitName: "output-bytes"}
	}
	return placeDecimalPoint(digits, exponentValue), nil
}

// plannedDecimalLen is the exact planned byte length of digits × 10^exponent
// under the canonical spelling.
func plannedDecimalLen(digits string, exponent int64) int {
	signed := 0
	if len(digits) > 0 && digits[0] == '-' {
		signed = 1
	}
	magnitude := len(digits) - signed
	switch {
	case exponent > 0:
		return len(digits) + int(exponent)
	case exponent < 0:
		fraction := int(-exponent)
		if fraction < magnitude {
			return len(digits) + 1
		}
		return fraction + 2 + signed
	default:
		return len(digits)
	}
}

// placeDecimalPoint places the decimal point of digits × 10^exponent into
// the canonical spelling.
func placeDecimalPoint(digits string, exponent int64) string {
	if exponent == 0 {
		return digits
	}
	if exponent > 0 {
		var out strings.Builder
		out.Grow(len(digits) + int(exponent))
		out.WriteString(digits)
		for i := int64(0); i < exponent; i++ {
			out.WriteByte('0')
		}
		return out.String()
	}
	fraction := int(-exponent)
	signed := ""
	magnitude := digits
	if len(digits) > 0 && digits[0] == '-' {
		signed = "-"
		magnitude = digits[1:]
	}
	if fraction < len(magnitude) {
		point := len(magnitude) - fraction
		var out strings.Builder
		out.Grow(len(digits) + 1)
		out.WriteString(signed)
		out.WriteString(magnitude[:point])
		out.WriteByte('.')
		out.WriteString(magnitude[point:])
		return out.String()
	}
	zeros := fraction - len(magnitude)
	var out strings.Builder
	out.Grow(fraction + 2 + len(signed))
	out.WriteString(signed)
	out.WriteString("0.")
	for i := 0; i < zeros; i++ {
		out.WriteByte('0')
	}
	out.WriteString(magnitude)
	return out.String()
}

// decimalMulU64 multiplies one decimal digit string (no sign) by one u64
// multiplier with big.Int carry arithmetic; the multiplier is a bounded
// power of two or five.
func decimalMulU64(digits *string, multiplier uint64) {
	value := new(big.Int)
	value.SetString(*digits, 10)
	value.Mul(value, new(big.Int).SetUint64(multiplier))
	*digits = value.String()
}

// doubleToCanonicalDecimal is the exact canonical decimal spelling of one
// binary64 datum; the second result is false for NaN and infinity, which
// the HCL number grammar cannot express (RFC 0014 §9).
func doubleToCanonicalDecimal(bits uint64) (string, bool) {
	sign := bits >> 63
	exponentBits := int64((bits>>52)&0x7FF) - 1023
	fraction := bits & 0xF_FFFF_FFFF_FFFF
	var mantissa uint64
	var exponent int64
	switch {
	case exponentBits == -1023 && fraction == 0:
		return "0", true
	case exponentBits == -1023:
		mantissa = fraction
		exponent = -1074
	case exponentBits == 1024:
		return "", false
	default:
		mantissa = fraction | 0x10_0000_0000_0000
		exponent = exponentBits - 52
	}
	digits := new(big.Int).SetUint64(mantissa).String()
	if exponent >= 0 {
		remaining := exponent
		for remaining > 0 {
			chunk := remaining
			if chunk > 32 {
				chunk = 32
			}
			decimalMulU64(&digits, 1<<chunk)
			remaining -= chunk
		}
	} else {
		magnitude := -exponent
		remaining := magnitude
		for remaining > 0 {
			chunk := remaining
			if chunk > 27 {
				chunk = 27
			}
			decimalMulU64(&digits, pow5Uint64(chunk))
			remaining -= chunk
		}
		digits = placeDecimalPoint(digits, -magnitude)
	}
	canonical, ok := CanonicalDecimal(digits)
	if !ok {
		return "", false
	}
	if sign != 0 && canonical != "0" {
		canonical = "-" + canonical
	}
	return canonical, true
}

// pow5Uint64 computes 5^power for a bounded power.
func pow5Uint64(power int64) uint64 {
	result := uint64(1)
	for i := int64(0); i < power; i++ {
		result *= 5
	}
	return result
}

// mathFloat32BitsToFloat64Bits widens one binary32 datum to its binary64
// value bits.
func mathFloat32BitsToFloat64Bits(bits uint32) uint64 {
	if bits == 0 {
		return 0
	}
	sign := uint64(bits>>31) << 63
	exponent := int32((bits >> 23) & 0xFF)
	fraction := uint64(bits & 0x7FFFFF)
	switch exponent {
	case 0xFF:
		if fraction == 0 {
			return sign | 0x7FF0000000000000
		}
		return sign | 0x7FF8000000000000
	case 0:
		if fraction == 0 {
			return sign
		}
		// Subnormal: normalize by finding the leading bit.
		shift := 0
		for fraction&0x800000 == 0 {
			fraction <<= 1
			shift++
		}
		fraction &= 0x7FFFFF
		exponent = int32(1 - shift)
		return sign | uint64(exponent+1023)<<52 | fraction<<29
	default:
		return sign | uint64(exponent+1023)<<52 | fraction<<29
	}
}

// verifyClosure walks the reparsed native model in lockstep with the
// record and collects the input-to-output provenance facts (RFC 0014 §9).
func verifyClosure(record *materializationRecord, doc *Document,
	limits document.MaterializationLimits) (MaterializationProvenanceMap, *MaterializationFailure) {
	authority := doc.authority
	snapshot := doc.SnapshotIdentity()
	rootSpan, err := authority.Span(0, doc.source.Len())
	if err != nil {
		return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	context := &closureContext{
		authority: authority,
		snapshot:  snapshot,
		limits:    limits,
	}
	if failure := context.push(protocol.RootValuePath(), rootSpan, document.RoleHclDocument); failure != nil {
		return MaterializationProvenanceMap{}, failure
	}
	if failure := context.body(&record.body, doc.document.body); failure != nil {
		return MaterializationProvenanceMap{}, failure
	}
	entries := make([]MaterializationProvenanceEntry, 0, len(context.outputs))
	for _, pair := range context.outputs {
		entries = append(entries, MaterializationProvenanceEntry{
			Input:   MaterializationInputLocation{Path: pair.input},
			Outputs: []MaterializedOrigin{pair.origin},
		})
	}
	return MaterializationProvenanceMap{entries: entries}, nil
}

// closureContext is the closure walk state.
type closureContext struct {
	authority document.DocumentAuthority
	snapshot  document.SnapshotIdentity
	outputs   []closurePair
	limits    document.MaterializationLimits
}

type closurePair struct {
	input  protocol.ValuePath
	origin MaterializedOrigin
}

func (c *closureContext) push(input protocol.ValuePath, span document.Span,
	role document.NodeRole) *MaterializationFailure {
	if len(c.outputs) >= c.limits.MaxProvenanceEntries {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit, LimitName: "provenance-entries"}
	}
	c.outputs = append(c.outputs, closurePair{
		input: input,
		origin: MaterializedOrigin{
			Snapshot: c.snapshot,
			Node:     c.authority.NodeRef(uint64(len(c.outputs)), role),
			Span:     span,
			Relation: MaterializationRelationDirect,
		},
	})
	return nil
}

// body compares one body in lockstep and records its item provenance.
func (c *closureContext) body(record *materializationBody, reparsed *HclBody) *MaterializationFailure {
	items := reparsed.items
	if len(items) != len(record.items) {
		return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	for index := range record.items {
		recordItem := &record.items[index]
		nativeItem := &items[index]
		if !recordItem.isBlock {
			attribute := nativeItem.AsAttribute()
			if attribute == nil || attribute.name != recordItem.name {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
			if !closureCheckValue(&recordItem.value, attribute.expression) {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
			itemSpan, err := c.authority.Span(attribute.nameSpan.StartByte(), attribute.expression.span.EndByte())
			if err != nil {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
			if failure := c.push(recordItem.path, itemSpan, document.RoleHclAttribute); failure != nil {
				return failure
			}
			valuePath := recordItem.path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "value"})
			if failure := c.push(valuePath, attribute.expression.span, document.RoleHclExpression); failure != nil {
				return failure
			}
			continue
		}
		block := nativeItem.AsBlock()
		if block == nil || block.blockType != recordItem.blockType {
			return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		if len(block.labels) != len(recordItem.labels) {
			return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		if failure := c.push(recordItem.path, block.span, document.RoleHclBlock); failure != nil {
			return failure
		}
		labelsPath := recordItem.path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "labels"})
		for labelIndex := range recordItem.labels {
			nativeLabel := &block.labels[labelIndex]
			if nativeLabel.text != recordItem.labels[labelIndex].text {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
			labelPath := labelsPath.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(labelIndex)})
			if failure := c.push(labelPath, nativeLabel.span, document.RoleHclBlockLabel); failure != nil {
				return failure
			}
		}
		if failure := c.body(recordItem.body, block.body); failure != nil {
			return failure
		}
	}
	return nil
}

// closureCheckValue reports whether one reparsed expression carries the
// promised value semantics (RFC 0014 §9 closure): numbers by
// canonical-decimal value equality, strings and object keys by exact
// decoded text, constructors element-wise, and `hcl.expression@1` values
// by structural equality plus fingerprint equality (RFC 0014 §6).
func closureCheckValue(record *materializationValue, expression *HclExpression) bool {
	kind := record.kind
	switch kind.tag {
	case valueString:
		text, ok := quotedTemplateText(expression)
		return ok && text == kind.text
	case valueInteger, valueReal:
		return numberSpellingMatches(expression, kind.text)
	case valueBoolean:
		return expression.kind.tag == exprBoolean && expression.kind.boolean == kind.boolean
	case valueNull:
		return expression.kind.tag == exprNull
	case valueTuple:
		if expression.kind.tag != exprTuple || len(expression.kind.elements) != len(kind.elements) {
			return false
		}
		for i := range kind.elements {
			if !closureCheckValue(&kind.elements[i], expression.kind.elements[i]) {
				return false
			}
		}
		return true
	case valueObject:
		if expression.kind.tag != exprObject || len(expression.kind.entries) != len(kind.entries) {
			return false
		}
		for i := range kind.entries {
			entry := &expression.kind.entries[i]
			if !objectKeyMatches(&entry.key, kind.entries[i].key) {
				return false
			}
			if !closureCheckValue(&kind.entries[i].value, entry.value) {
				return false
			}
		}
		return true
	case valueExpression:
		return kind.expr != nil && expression.Equal(kind.expr.ast) &&
			expressionFingerprint(expression) == expressionFingerprint(kind.expr.ast)
	}
	return false
}

// quotedTemplateText is the exact decoded text of one quoted template;
// the second result is false for a heredoc, an interpolation, or a
// directive.
func quotedTemplateText(expression *HclExpression) (string, bool) {
	if expression.kind.tag != exprTemplate || expression.kind.heredoc != nil {
		return "", false
	}
	var text strings.Builder
	for i := range expression.kind.parts {
		part := &expression.kind.parts[i]
		if part.tag != partLiteral {
			return "", false
		}
		text.WriteString(part.text)
	}
	return text.String(), true
}

// numberSpellingMatches reports whether one reparsed expression is the
// canonical spelling of one promised number, including the unary-minus
// form of a negative value.
func numberSpellingMatches(expression *HclExpression, spelling string) bool {
	if strings.HasPrefix(spelling, "-") {
		if expression.kind.tag != exprUnary || expression.kind.unaryOp != UnaryOpMinus {
			return false
		}
		return numberCanonicalMatches(expression.kind.unaryOperand, spelling[1:])
	}
	return numberCanonicalMatches(expression, spelling)
}

// numberCanonicalMatches reports whether one reparsed expression is one
// number with the exact canonical decimal spelling.
func numberCanonicalMatches(expression *HclExpression, canonical string) bool {
	return expression.kind.tag == exprNumber && expression.kind.number.canonical == canonical
}

// objectKeyMatches reports whether one reparsed object key is the promised
// key text: a bare identifier or a quoted literal template with the exact
// decoded text.
func objectKeyMatches(key *HclObjectKey, promised string) bool {
	switch key.tag {
	case keyIdentifier:
		return key.name == promised
	case keyTemplate:
		var text strings.Builder
		for i := range key.template.parts {
			part := &key.template.parts[i]
			if part.tag != partLiteral {
				return false
			}
			text.WriteString(part.text)
		}
		return text.String() == promised
	case keyNumber, keyParen:
		return false
	}
	return false
}

// expectObjectField reads one required object member of one record.
func expectObjectField(value core.Value, name string, path *protocol.ValuePath,
	missing string) (core.Value, *MaterializationFailure) {
	object, ok := value.(*core.Object)
	if !ok {
		return nil, unrepresentableAt(*path, value.Kind())
	}
	field, ok := object.Get(name)
	if !ok {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest, Detail: missing}
	}
	return field, nil
}

// expectStringField reads one required string member of one record.
func expectStringField(value core.Value, name string, path *protocol.ValuePath,
	missing string) (string, *MaterializationFailure) {
	field, failure := expectObjectField(value, name, path, missing)
	if failure != nil {
		return "", failure
	}
	text, ok := field.(core.String)
	if !ok {
		return "", unrepresentableAt(path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: name}), field.Kind())
	}
	return string(text), nil
}

// unrepresentableAt builds one input value failure for the target profile
// (the runner maps this to `hcl.materialization.unrepresentable@1`).
func unrepresentableAt(path protocol.ValuePath, kind core.Kind) *MaterializationFailure {
	return &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
		Path: path, ValueKind: kind}
}

// StructuralFingerprint returns the structural fingerprint of one
// expression (RFC 0014 §6, §8.2): a 64-bit FNV-1a hash over the canonical
// structural serialization, so structurally equal expressions always carry
// the same fingerprint, and the fingerprint never depends on source spans.
func StructuralFingerprint(expression *HclExpression) uint64 {
	return expressionFingerprintValue(expression)
}

// expressionFingerprint is the hex of the shared fingerprint value (RFC
// 0014 §8.2).
func expressionFingerprint(expression *HclExpression) string {
	return fingerprintHex(expressionFingerprintValue(expression))
}

// expressionFingerprintValue computes the 64-bit FNV-1a hash (offset basis
// 0xcbf29ce484222325, prime 0x100000001b3) over the canonical structural
// serialization of one expression (RFC 0014 §6, §8.2).
func expressionFingerprintValue(expression *HclExpression) uint64 {
	var bytes []byte
	writeExpressionStructure(expression, &bytes)
	hash := uint64(0xcbf29ce484222325)
	for _, byte := range bytes {
		hash ^= uint64(byte)
		hash *= 0x100000001b3
	}
	return hash
}

// pushText appends one length-prefixed text run to the structural
// serialization (the 8-byte little-endian length spelling of the shared
// M6/M7 adaptation point).
func pushText(text string, out *[]byte) {
	var length [8]byte
	value := uint64(len(text))
	for i := 0; i < 8; i++ {
		length[i] = byte(value >> (8 * i))
	}
	*out = append(*out, length[:]...)
	*out = append(*out, text...)
}

// writeExpressionStructure appends the canonical structural serialization
// of one expression.
func writeExpressionStructure(expression *HclExpression, out *[]byte) {
	kind := &expression.kind
	switch kind.tag {
	case exprNumber:
		*out = append(*out, 'N')
		pushText(kind.number.canonical, out)
	case exprBoolean:
		*out = append(*out, 'B')
		if kind.boolean {
			*out = append(*out, 1)
		} else {
			*out = append(*out, 0)
		}
	case exprNull:
		*out = append(*out, 'Z')
	case exprTemplate:
		*out = append(*out, 'T')
		if kind.heredoc != nil {
			*out = append(*out, 'H')
			pushText(kind.heredoc.mode.AsStr(), out)
			pushText(kind.heredoc.marker, out)
		} else {
			*out = append(*out, 'Q')
		}
		for i := range kind.parts {
			part := &kind.parts[i]
			switch part.tag {
			case partLiteral:
				*out = append(*out, 'L')
				pushText(part.text, out)
			case partInterpolation:
				*out = append(*out, 'I')
				writeExpressionStructure(part.expression, out)
			case partDirective:
				*out = append(*out, 'D')
				writeDirectiveStructure(&part.directive, out)
			}
		}
	case exprFunctionCall:
		*out = append(*out, 'F')
		pushText(kind.callName, out)
		for i := range kind.callArgs {
			argument := &kind.callArgs[i]
			if argument.expand {
				*out = append(*out, 'X')
			} else {
				*out = append(*out, 'x')
			}
			writeExpressionStructure(argument.expression, out)
		}
	case exprVariableRef:
		*out = append(*out, 'V')
		pushText(kind.variableName, out)
	case exprTraversal:
		*out = append(*out, 'R')
		switch kind.root.tag {
		case traversalRootVariable:
			*out = append(*out, 'v')
			pushText(kind.root.name, out)
		case traversalRootBoolean:
			*out = append(*out, 'b')
			if kind.root.value {
				*out = append(*out, 1)
			} else {
				*out = append(*out, 0)
			}
		case traversalRootNull:
			*out = append(*out, 'n')
		}
		for i := range kind.steps {
			writeTraversalStep(&kind.steps[i], out)
		}
	case exprUnary:
		*out = append(*out, 'U')
		pushText(kind.unaryOp.AsStr(), out)
		writeExpressionStructure(kind.unaryOperand, out)
	case exprBinary:
		*out = append(*out, 'W')
		pushText(kind.binaryOp.AsStr(), out)
		writeExpressionStructure(kind.binaryLhs, out)
		writeExpressionStructure(kind.binaryRhs, out)
	case exprConditional:
		*out = append(*out, 'C')
		writeExpressionStructure(kind.condition, out)
		writeExpressionStructure(kind.thenExpr, out)
		writeExpressionStructure(kind.elseExpr, out)
	case exprForTuple:
		*out = append(*out, 'P')
		writeForIntro(&kind.intro, out)
		writeExpressionStructure(kind.forValue, out)
		if kind.forCondition != nil {
			*out = append(*out, 'c')
			writeExpressionStructure(kind.forCondition, out)
		} else {
			*out = append(*out, 'n')
		}
	case exprForObject:
		*out = append(*out, 'O')
		writeForIntro(&kind.intro, out)
		writeExpressionStructure(kind.forKey, out)
		writeExpressionStructure(kind.forValue, out)
		if kind.grouping {
			*out = append(*out, 'g')
		} else {
			*out = append(*out, 'n')
		}
		if kind.forCondition != nil {
			*out = append(*out, 'c')
			writeExpressionStructure(kind.forCondition, out)
		} else {
			*out = append(*out, 'n')
		}
	case exprTuple:
		*out = append(*out, 'L')
		for _, element := range kind.elements {
			writeExpressionStructure(element, out)
		}
	case exprObject:
		*out = append(*out, 'M')
		for i := range kind.entries {
			writeObjectKeyStructure(&kind.entries[i].key, out)
			writeExpressionStructure(kind.entries[i].value, out)
		}
	case exprParen:
		*out = append(*out, '(')
		writeExpressionStructure(kind.inner, out)
	}
}

// writeDirectiveStructure appends the canonical structural serialization
// of one template directive.
func writeDirectiveStructure(kind *HclDirectiveKind, out *[]byte) {
	switch kind.tag {
	case directiveIf:
		*out = append(*out, 'f')
		writeExpressionStructure(kind.condition, out)
	case directiveElse:
		*out = append(*out, 'e')
	case directiveEndIf:
		*out = append(*out, 'E')
	case directiveFor:
		*out = append(*out, 'o')
		writeForIntro(kind.intro, out)
	case directiveEndFor:
		*out = append(*out, 'g')
	}
}

// writeForIntro appends the canonical structural serialization of one
// `for` introduction.
func writeForIntro(intro *HclForIntro, out *[]byte) {
	if intro.key != nil {
		*out = append(*out, 'k')
		pushText(*intro.key, out)
	} else {
		*out = append(*out, 'n')
	}
	pushText(intro.value, out)
	writeExpressionStructure(intro.collection, out)
}

// writeTraversalStep appends the canonical structural serialization of one
// traversal step.
func writeTraversalStep(step *HclTraversalStep, out *[]byte) {
	switch step.tag {
	case stepGetAttr:
		*out = append(*out, 'a')
		pushText(step.name, out)
	case stepIndex:
		*out = append(*out, 'i')
		writeExpressionStructure(step.key, out)
	case stepAttrSplat:
		*out = append(*out, 's')
		for i := range step.steps {
			writeTraversalStep(&step.steps[i], out)
		}
	case stepFullSplat:
		*out = append(*out, 'S')
		for i := range step.steps {
			writeTraversalStep(&step.steps[i], out)
		}
	}
}

// writeObjectKeyStructure appends the canonical structural serialization
// of one object key.
func writeObjectKeyStructure(key *HclObjectKey, out *[]byte) {
	switch key.tag {
	case keyIdentifier:
		*out = append(*out, 'K')
		pushText(key.name, out)
	case keyNumber:
		*out = append(*out, 'k')
		pushText(key.number.canonical, out)
	case keyTemplate:
		*out = append(*out, 't')
		for i := range key.template.parts {
			part := &key.template.parts[i]
			switch part.tag {
			case partLiteral:
				*out = append(*out, 'l')
				pushText(part.text, out)
			case partInterpolation:
				*out = append(*out, 'i')
				writeExpressionStructure(part.expression, out)
			case partDirective:
				*out = append(*out, 'd')
				writeDirectiveStructure(&part.directive, out)
			}
		}
	case keyParen:
		*out = append(*out, 'p')
		writeExpressionStructure(key.parenInner, out)
	}
}
