package yaml

import (
	"fmt"
	"strings"

	"consema.dev/consema/core"
	"consema.dev/consema/document"
	"consema.dev/consema/graph"
	"consema.dev/consema/protocol"
)

// This file implements the canonical block/flow YAML materialization
// (consema-yaml materialization.rs): every retained standard repository
// tag is emitted explicitly, sharing and cycles become deterministic
// `&gN` anchors, and the generated bytes are reparsed and verified before
// a Complete result is returned.

// GraphMaterializationInputLocation is one graph input location
// (materialization.rs:33-60).
type GraphMaterializationInputLocation struct {
	// Kind is "Root", "Node", "SequenceElement", "MappingKey", or
	// "MappingValue".
	Kind string
	// Ordinal is the ordered root or association ordinal.
	Ordinal uint64
	// Parent is the parent graph node of association locations.
	Parent graph.NodeID
}

// GraphMaterializationProvenanceEntry maps one input location to its
// materialized outputs.
type GraphMaterializationProvenanceEntry struct {
	// Input is the graph input location.
	Input GraphMaterializationInputLocation
	// Outputs are the ordered materialized origins.
	Outputs []MaterializedOrigin
}

// GraphMaterializationProvenanceMap is the immutable graph materialization
// provenance map.
type GraphMaterializationProvenanceMap struct {
	entries []GraphMaterializationProvenanceEntry
}

// Entries returns the deterministic entries.
func (m GraphMaterializationProvenanceMap) Entries() []GraphMaterializationProvenanceEntry {
	return append([]GraphMaterializationProvenanceEntry(nil), m.entries...)
}

// GraphMaterializationFailureKind classifies one graph materialization
// failure (materialization.rs:86-111).
type GraphMaterializationFailureKind uint8

// The stable graph materialization failure classes.
const (
	// GraphMaterializationFailureMaterialization is a common
	// request/formation/resource contract failure.
	GraphMaterializationFailureMaterialization GraphMaterializationFailureKind = iota
	// GraphMaterializationFailureUnsupportedTag: a graph tag has no
	// published canonical YAML spelling.
	GraphMaterializationFailureUnsupportedTag
	// GraphMaterializationFailureTagKindMismatch: a known tag is on the
	// wrong node kind.
	GraphMaterializationFailureTagKindMismatch
	// GraphMaterializationFailureCrossDocumentSharing: a node is reachable
	// from more than one root document.
	GraphMaterializationFailureCrossDocumentSharing
	// GraphMaterializationFailureRoundTripMismatch: the reparse did not
	// reproduce the input graph exactly.
	GraphMaterializationFailureRoundTripMismatch
)

// GraphMaterializationFailure is the typed graph materialization failure.
// It implements error and the Code() contract.
type GraphMaterializationFailure struct {
	// Kind identifies the failure.
	Kind GraphMaterializationFailureKind
	// Node is the offending graph node.
	Node graph.NodeID
	// Tag is the offending tag.
	Tag string
	// Underlying is the common materialization failure.
	Underlying *MaterializationFailure
}

// Error implements error; the text is human presentation only.
func (f *GraphMaterializationFailure) Error() string {
	switch f.Kind {
	case GraphMaterializationFailureUnsupportedTag:
		return "yaml: unsupported materialization tag " + f.Tag
	case GraphMaterializationFailureTagKindMismatch:
		return "yaml: materialization tag-kind mismatch " + f.Tag
	case GraphMaterializationFailureCrossDocumentSharing:
		return "yaml: cross-document sharing in graph materialization"
	case GraphMaterializationFailureRoundTripMismatch:
		return "yaml: materialized graph did not round-trip"
	case GraphMaterializationFailureMaterialization:
		return "yaml: materialization failed: " + f.Underlying.Error()
	}
	return "yaml: graph materialization failed"
}

// Code returns the frozen registered code.
func (f *GraphMaterializationFailure) Code() string {
	switch f.Kind {
	case GraphMaterializationFailureUnsupportedTag:
		return "yaml.materialization.unsupported-tag@1"
	case GraphMaterializationFailureTagKindMismatch:
		return "yaml.materialization.tag-kind-mismatch@1"
	case GraphMaterializationFailureCrossDocumentSharing:
		return "yaml.materialization.cross-document-sharing@1"
	case GraphMaterializationFailureRoundTripMismatch:
		return "yaml.materialization.round-trip-mismatch@1"
	case GraphMaterializationFailureMaterialization:
		return f.Underlying.Code()
	}
	return "core.materialization.invalid-request@1"
}

// FailedGraphMaterializationAttempt is the failed graph attempt without a
// candidate document.
type FailedGraphMaterializationAttempt struct {
	// Failure is the typed failure.
	Failure GraphMaterializationFailure
	// AnalyzedInputNodes are the input nodes analyzed before failure.
	AnalyzedInputNodes []graph.NodeID
}

// CompleteGraphMaterialization is the complete graph materialization
// result.
type CompleteGraphMaterialization struct {
	// Document is the newly formed immutable YAML stream.
	Document *Document
	// Fidelity is always Exact for the published graph contract.
	Fidelity MaterializationFidelity
	// Report is the transformation report (always empty for graphs).
	Report MaterializationReport
	// Provenance maps every input location to its outputs.
	Provenance GraphMaterializationProvenanceMap
}

// GraphMaterializationResult is the graph materialization completion
// algebra. Exactly one outcome is non-nil.
type GraphMaterializationResult struct {
	// Complete is the complete success outcome.
	Complete *CompleteGraphMaterialization
	// Failed is the failed attempt with no document.
	Failed *FailedGraphMaterializationAttempt
}

// MaterializationFidelity is the materialization fidelity classification.
type MaterializationFidelity string

// The two frozen fidelity levels.
const (
	// MaterializationFidelityExact means the target directly represents
	// the input semantics.
	MaterializationFidelityExact MaterializationFidelity = "Exact"
	// MaterializationFidelityTransformed means complete semantics survive
	// an explicit reversible re-encoding.
	MaterializationFidelityTransformed MaterializationFidelity = "Transformed"
)

// MaterializationFailureKind classifies a stable materialization failure.
type MaterializationFailureKind uint8

// The stable materialization failure classes.
const (
	// MaterializationUnsupportedProfile: the requested target profile is
	// unavailable.
	MaterializationUnsupportedProfile MaterializationFailureKind = iota
	// MaterializationUnsupportedStyle: the requested style is unavailable.
	MaterializationUnsupportedStyle
	// MaterializationUnsupportedEncoding: the target does not support the
	// requested encoding.
	MaterializationUnsupportedEncoding
	// MaterializationUnsupportedNewline: the target style does not support
	// the requested newline policy.
	MaterializationUnsupportedNewline
	// MaterializationUnrepresentable: the portable input cannot be
	// represented by the target profile.
	MaterializationUnrepresentable
	// MaterializationResourceLimit: a declared resource limit was reached.
	MaterializationResourceLimit
	// MaterializationFormationFailed: generated bytes did not form the
	// target profile.
	MaterializationFormationFailed
)

// MaterializationFailure is the typed materialization failure. It
// implements error and the RFC 0016 §6 Code() contract.
type MaterializationFailure struct {
	// Kind identifies the failure.
	Kind MaterializationFailureKind
	// Path is the offending input value path of Unrepresentable failures.
	Path protocol.ValuePath
	// KindName is the offending PortableValue kind name.
	KindName string
	// LimitName is the stable limit name of ResourceLimit failures.
	LimitName string
}

// Code returns the frozen registered code.
func (f *MaterializationFailure) Code() string {
	switch f.Kind {
	case MaterializationUnsupportedProfile:
		return "core.materialization.unsupported-profile@1"
	case MaterializationUnsupportedStyle:
		return "core.materialization.unsupported-style@1"
	case MaterializationUnsupportedEncoding:
		return "core.materialization.unsupported-encoding@1"
	case MaterializationUnsupportedNewline:
		return "core.materialization.unsupported-newline@1"
	case MaterializationUnrepresentable:
		return "core.materialization.unrepresentable@1"
	case MaterializationResourceLimit:
		return "core.materialization.resource-limit@1"
	case MaterializationFormationFailed:
		return "core.materialization.formation-failed@1"
	}
	return "core.materialization.invalid-request@1"
}

// Error implements error; the text is human presentation only.
func (f *MaterializationFailure) Error() string {
	switch f.Kind {
	case MaterializationUnsupportedProfile:
		return "yaml: unsupported materialization profile"
	case MaterializationUnsupportedStyle:
		return "yaml: unsupported materialization style"
	case MaterializationUnsupportedEncoding:
		return "yaml: unsupported materialization encoding"
	case MaterializationUnsupportedNewline:
		return "yaml: unsupported materialization newline policy"
	case MaterializationUnrepresentable:
		return "yaml: input kind " + f.KindName + " is not representable"
	case MaterializationResourceLimit:
		return "yaml: materialization resource limit " + f.LimitName + " was reached"
	case MaterializationFormationFailed:
		return "yaml: generated bytes did not form a YAML document"
	}
	return "yaml: materialization failed"
}

// MaterializationReport is the complete ordered materialization report.
type MaterializationReport struct {
	events []*protocol.Diagnostic
}

// Events returns the ordered transformation/loss events.
func (r MaterializationReport) Events() []*protocol.Diagnostic {
	return append([]*protocol.Diagnostic(nil), r.events...)
}

// MaterializationRelation is the input-to-output relation of one
// materialized origin.
type MaterializationRelation string

// The three frozen relations.
const (
	// MaterializationRelationDirect is a direct native semantic origin.
	MaterializationRelationDirect MaterializationRelation = "Direct"
	// MaterializationRelationGenerated is an output identity synthesized
	// by the materializer.
	MaterializationRelationGenerated MaterializationRelation = "Generated"
	// MaterializationRelationReencoded is an explicitly re-encoded input
	// origin.
	MaterializationRelationReencoded MaterializationRelation = "Reencoded"
)

// MaterializationInputLocation is one input value or association location.
type MaterializationInputLocation struct {
	// Path is the portable value location of Value locations.
	Path protocol.ValuePath
	// Association is the portable association location of Association
	// locations.
	Association *protocol.AssociationLocation
	// Kind is "Value" or "Association".
	Kind string
}

// MaterializedOrigin is one exact materialized output origin.
type MaterializedOrigin struct {
	// Snapshot is the output document snapshot.
	Snapshot document.SnapshotIdentity
	// Node is the exact structural identity.
	Node document.NodeRef
	// Span is the exact source range.
	Span document.Span
	// Relation is the output relation.
	Relation MaterializationRelation
}

// MaterializationProvenanceEntry is one input-to-outputs mapping entry.
type MaterializationProvenanceEntry struct {
	// Input is the input value or association location.
	Input MaterializationInputLocation
	// Outputs are the ordered output origins.
	Outputs []MaterializedOrigin
}

// MaterializationProvenanceMap is the immutable input-to-output provenance
// map.
type MaterializationProvenanceMap struct {
	entries []MaterializationProvenanceEntry
}

// Entries returns the deterministic entries.
func (m MaterializationProvenanceMap) Entries() []MaterializationProvenanceEntry {
	return append([]MaterializationProvenanceEntry(nil), m.entries...)
}

// CompleteMaterialization is the complete value materialization result.
type CompleteMaterialization struct {
	// Document is the new immutable target document.
	Document *Document
	// Fidelity is the fidelity of the whole operation.
	Fidelity MaterializationFidelity
	// Report is the machine-readable transformation report.
	Report MaterializationReport
	// Provenance maps every input value and association to its outputs.
	Provenance MaterializationProvenanceMap
}

// FailedMaterializationAttempt is the failed attempt without a document.
type FailedMaterializationAttempt struct {
	// Failure is the typed failure.
	Failure MaterializationFailure
	// Report holds the events discovered before the failure.
	Report MaterializationReport
	// AnalyzedInputPaths are the input paths analyzed before failure.
	AnalyzedInputPaths []protocol.ValuePath
}

// MaterializationResult is the value materialization completion algebra.
// Exactly one outcome is non-nil.
type MaterializationResult struct {
	// Complete is the complete success outcome.
	Complete *CompleteMaterialization
	// Failed is the failed attempt with no document.
	Failed *FailedMaterializationAttempt
}

// yamlStyle is the closed internal materialization style.
type yamlStyle uint8

const (
	styleBlock yamlStyle = iota
	styleFlow
)

// materializeGraph materializes one complete PortableGraph into a new
// immutable YAML document (materialization.rs:192-238). The graph is
// numbered canonically; nodes whose topology requires an alias receive
// deterministic `&g0`, `&g1`, ... anchors; every retained standard tag is
// emitted explicitly; the generated bytes are reparsed and the graph
// equality is verified before a Complete result is returned.
func MaterializeGraph(graphValue *graph.Graph,
	request document.MaterializationRequest) GraphMaterializationResult {
	profile, style, contractFailure := requestedContract(request)
	if contractFailure != nil {
		return GraphMaterializationResult{Failed: &FailedGraphMaterializationAttempt{
			Failure: GraphMaterializationFailure{Kind: GraphMaterializationFailureMaterialization,
				Underlying: contractFailure},
		}}
	}
	layout, layoutFailure := analyzeGraphLayout(graphValue, request.Limits())
	if layoutFailure != nil {
		return GraphMaterializationResult{Failed: &FailedGraphMaterializationAttempt{
			Failure: *layoutFailure, AnalyzedInputNodes: layout.analyzed,
		}}
	}
	writer := &graphWriter{
		style:   style,
		newline: request.Newline(),
		limits:  request.Limits(),
		layout:  layout,
	}
	text, streamFailure := writer.stream()
	if streamFailure != nil {
		return GraphMaterializationResult{Failed: &FailedGraphMaterializationAttempt{
			Failure: *streamFailure, AnalyzedInputNodes: layout.analyzed,
		}}
	}
	raw, encodeFailure := encodeOutput(text, request.Encoding(), request.Limits().MaxOutputBytes)
	if encodeFailure != nil {
		return GraphMaterializationResult{Failed: &FailedGraphMaterializationAttempt{
			Failure: GraphMaterializationFailure{Kind: GraphMaterializationFailureMaterialization,
				Underlying: encodeFailure},
			AnalyzedInputNodes: layout.analyzed,
		}}
	}
	document, formationFailure := Parse(raw, profile, materializationParseLimits(request.Limits()))
	if formationFailure != nil {
		f := &MaterializationFailure{Kind: MaterializationFormationFailed}
		return GraphMaterializationResult{Failed: &FailedGraphMaterializationAttempt{
			Failure: GraphMaterializationFailure{Kind: GraphMaterializationFailureMaterialization,
				Underlying: f},
			AnalyzedInputNodes: layout.analyzed,
		}}
	}
	reparsed, err := document.ProjectGraph()
	if err != nil || !graph.Equal(reparsed, graphValue) {
		f := &GraphMaterializationFailure{Kind: GraphMaterializationFailureRoundTripMismatch}
		return GraphMaterializationResult{Failed: &FailedGraphMaterializationAttempt{
			Failure: *f, AnalyzedInputNodes: layout.analyzed,
		}}
	}
	if len(graphValue.Roots()) != document.DocumentCount() {
		// The reparsed stream must carry exactly one document per root.
		f := &GraphMaterializationFailure{Kind: GraphMaterializationFailureRoundTripMismatch}
		return GraphMaterializationResult{Failed: &FailedGraphMaterializationAttempt{
			Failure: *f, AnalyzedInputNodes: layout.analyzed,
		}}
	}
	provenance, provenanceFailure := collectGraphProvenance(graphValue, document, request.Limits())
	if provenanceFailure != nil {
		return GraphMaterializationResult{Failed: &FailedGraphMaterializationAttempt{
			Failure: *provenanceFailure, AnalyzedInputNodes: layout.analyzed,
		}}
	}
	return GraphMaterializationResult{Complete: &CompleteGraphMaterialization{
		Document:   document,
		Fidelity:   MaterializationFidelityExact,
		Report:     MaterializationReport{},
		Provenance: provenance,
	}}
}

// requestedContract validates the common request facts and returns the
// selected profile and style.
func requestedContract(request document.MaterializationRequest) (YamlProfile, yamlStyle, *MaterializationFailure) {
	var profile YamlProfile
	switch {
	case request.TargetProfile().ID() == "yaml.1.2-core" && request.TargetProfile().Version() == 1:
		profile = Yaml12CoreV1
	case request.TargetProfile().ID() == "yaml.1.1-compat" && request.TargetProfile().Version() == 1:
		profile = Yaml11CompatV1
	default:
		return YamlProfile{}, 0, &MaterializationFailure{Kind: MaterializationUnsupportedProfile}
	}
	var style yamlStyle
	switch {
	case request.Style().ID() == "yaml.canonical-block" && request.Style().Version() == 1:
		style = styleBlock
	case request.Style().ID() == "yaml.canonical-flow" && request.Style().Version() == 1:
		style = styleFlow
	default:
		return YamlProfile{}, 0, &MaterializationFailure{Kind: MaterializationUnsupportedStyle}
	}
	switch request.Encoding().Kind() {
	case document.EncodingUtf8, document.EncodingUtf16Le, document.EncodingUtf16Be:
	default:
		return YamlProfile{}, 0, &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
	}
	if request.Newline() == document.NewlineNone {
		return YamlProfile{}, 0, &MaterializationFailure{Kind: MaterializationUnsupportedNewline}
	}
	return profile, style, nil
}

// materializationParseLimits maps the materialization limits onto the
// re-parse limits (materialization.rs:282-290).
func materializationParseLimits(limits document.MaterializationLimits) document.ParseLimits {
	return document.ParseLimits{
		MaxSourceBytes:  limits.MaxOutputBytes,
		MaxNestingDepth: limits.MaxDepth,
		MaxTokenCount:   limits.MaxOutputBytes,
		MaxNodeCount:    limits.MaxInputNodes * 4,
		MaxDiagnostics:  limits.MaxReportEntries,
	}
}

// graphLayout is the analyzed canonical layout of one input graph
// (materialization.rs:296-401).
type graphLayout struct {
	graph       *graph.Graph
	canonical   []graph.NodeID
	owner       map[graph.NodeID]int
	occurrences map[graph.NodeID]int
	anchors     map[graph.NodeID]int
	nextAnchor  int
	analyzed    []graph.NodeID
}

// analyzeGraphLayout computes the canonical first-visit order, checks the
// cross-document sharing boundary, and numbers the anchors.
func analyzeGraphLayout(graphValue *graph.Graph,
	limits document.MaterializationLimits) (*graphLayout, *GraphMaterializationFailure) {
	layout := &graphLayout{
		graph:       graphValue,
		owner:       make(map[graph.NodeID]int),
		occurrences: make(map[graph.NodeID]int),
		anchors:     make(map[graph.NodeID]int),
	}
	seen := make(map[graph.NodeID]bool)
	roots := graphValue.Roots()
	type stackEntry struct {
		id    graph.NodeID
		depth int
	}
	// Roots are pushed in reverse so they pop in root order.
	var stack []stackEntry
	for index := len(roots) - 1; index >= 0; index-- {
		stack = append(stack, stackEntry{id: roots[index], depth: 0})
	}
	for len(stack) > 0 {
		entry := stack[len(stack)-1]
		stack = stack[:len(stack)-1]
		if seen[entry.id] {
			continue
		}
		if entry.depth > limits.MaxDepth {
			return layout, materializationResourceFailure("input-depth", entry.depth, limits.MaxDepth)
		}
		if len(layout.canonical) >= limits.MaxInputNodes {
			return layout, materializationResourceFailure("input-nodes",
				len(layout.canonical)+1, limits.MaxInputNodes)
		}
		node, ok := graphValue.Node(entry.id)
		if !ok {
			return layout, &GraphMaterializationFailure{
				Kind: GraphMaterializationFailureRoundTripMismatch, Node: entry.id}
		}
		if failure := validateTagKind(entry.id, node); failure != nil {
			return layout, failure
		}
		seen[entry.id] = true
		layout.canonical = append(layout.canonical, entry.id)
		childDepth := entry.depth + 1
		switch node.Kind() {
		case graph.KindSequence:
			items, _ := node.SequenceItems()
			for index := len(items) - 1; index >= 0; index-- {
				stack = append(stack, stackEntry{id: items[index], depth: childDepth})
			}
		case graph.KindMapping:
			entries, _ := node.MappingEntries()
			for index := len(entries) - 1; index >= 0; index-- {
				stack = append(stack, stackEntry{id: entries[index].Value, depth: childDepth})
				stack = append(stack, stackEntry{id: entries[index].Key, depth: childDepth})
			}
		}
	}
	// Cross-document ownership: one per-root walk claims every reachable
	// node; a node reachable from a second root fails atomically.
	for rootOrdinal, root := range roots {
		var walk []graph.NodeID
		walk = append(walk, root)
		visited := make(map[graph.NodeID]bool)
		for len(walk) > 0 {
			id := walk[len(walk)-1]
			walk = walk[:len(walk)-1]
			if visited[id] {
				continue
			}
			visited[id] = true
			if previous, claimed := layout.owner[id]; claimed && previous != rootOrdinal {
				return layout, &GraphMaterializationFailure{
					Kind: GraphMaterializationFailureCrossDocumentSharing, Node: id}
			}
			layout.owner[id] = rootOrdinal
			node, _ := graphValue.Node(id)
			switch node.Kind() {
			case graph.KindSequence:
				items, _ := node.SequenceItems()
				walk = append(walk, items...)
			case graph.KindMapping:
				entries, _ := node.MappingEntries()
				for _, entry := range entries {
					walk = append(walk, entry.Key, entry.Value)
				}
			}
		}
	}
	// Occurrence counts: every root position and every edge endpoint
	// contributes once (a static count, so cycles terminate).
	for _, root := range roots {
		layout.occurrences[root]++
	}
	for _, id := range layout.canonical {
		node, _ := graphValue.Node(id)
		switch node.Kind() {
		case graph.KindSequence:
			items, _ := node.SequenceItems()
			for _, item := range items {
				layout.occurrences[item]++
			}
		case graph.KindMapping:
			entries, _ := node.MappingEntries()
			for _, entry := range entries {
				layout.occurrences[entry.Key]++
				layout.occurrences[entry.Value]++
			}
		}
	}
	for _, id := range layout.canonical {
		if layout.occurrences[id] > 1 {
			layout.anchors[id] = layout.nextAnchor
			layout.nextAnchor++
		}
	}
	return layout, nil
}

// validateTagKind checks one known tag against its node kind
// (materialization.rs:403-428).
func validateTagKind(id graph.NodeID, node *graph.Node) *GraphMaterializationFailure {
	tag := node.Tag()
	switch node.Kind() {
	case graph.KindScalar:
		switch tag {
		case tagNull, tagBool, tagInt, tagFloat, tagStr, tagTimestamp, tagBinary,
			tagMerge, tagValue, tagYaml:
			return nil
		}
	case graph.KindSequence:
		switch tag {
		case tagSeq, tagOmap, tagPairs:
			return nil
		}
	case graph.KindMapping:
		switch tag {
		case tagMap, tagSet:
			return nil
		}
	}
	if standardGraphTags[tag] {
		return &GraphMaterializationFailure{Kind: GraphMaterializationFailureTagKindMismatch,
			Node: id, Tag: tag}
	}
	return &GraphMaterializationFailure{Kind: GraphMaterializationFailureUnsupportedTag,
		Node: id, Tag: tag}
}

func materializationResourceFailure(name string, observed, limit int) *GraphMaterializationFailure {
	return &GraphMaterializationFailure{
		Kind:       GraphMaterializationFailureMaterialization,
		Underlying: &MaterializationFailure{Kind: MaterializationResourceLimit, LimitName: name},
	}
}

// graphWriter emits the canonical stream (materialization.rs:430-717).
type graphWriter struct {
	style    yamlStyle
	newline  document.NewlinePolicy
	limits   document.MaterializationLimits
	layout   *graphLayout
	output   strings.Builder
	emitted  map[graph.NodeID]bool
	analyzed []graph.NodeID
}

// stream writes every root as one explicit document.
func (w *graphWriter) stream() (string, *GraphMaterializationFailure) {
	roots := w.layout.graph.Roots()
	for ordinal, root := range roots {
		if ordinal != 0 {
			w.output.WriteString(string(w.newline.Bytes()))
		}
		w.emitted = make(map[graph.NodeID]bool)
		w.output.WriteString("---")
		if w.style == styleFlow {
			w.output.WriteString(" ")
			if failure := w.flowNode(root, 0); failure != nil {
				return "", failure
			}
		} else {
			if failure := w.blockAfterIndicator(root, 0, 0); failure != nil {
				return "", failure
			}
		}
		w.output.WriteString(string(w.newline.Bytes()))
	}
	return w.output.String(), nil
}

// flowNode emits one flow-context node (materialization.rs:484-538).
func (w *graphWriter) flowNode(id graph.NodeID, depth int) *GraphMaterializationFailure {
	if w.emitted[id] {
		return w.writeAlias(id)
	}
	if failure := w.beginDefinition(id, depth); failure != nil {
		return failure
	}
	if failure := w.writeProperties(id); failure != nil {
		return failure
	}
	node, _ := w.layout.graph.Node(id)
	switch node.Kind() {
	case graph.KindScalar:
		w.output.WriteString(" ")
		content, _ := node.ScalarContent()
		return w.writeQuoted(scalarPresentation(node.Tag(), content))
	case graph.KindSequence:
		items, _ := node.SequenceItems()
		w.output.WriteString(" [")
		for index, item := range items {
			if index != 0 {
				w.output.WriteString(", ")
			}
			if failure := w.flowNode(item, depth+1); failure != nil {
				return failure
			}
		}
		w.output.WriteString("]")
	case graph.KindMapping:
		entries, _ := node.MappingEntries()
		w.output.WriteString(" {")
		for index, entry := range entries {
			if index != 0 {
				w.output.WriteString(", ")
			}
			w.output.WriteString("? ")
			if failure := w.flowNode(entry.Key, depth+1); failure != nil {
				return failure
			}
			w.output.WriteString(" : ")
			if failure := w.flowNode(entry.Value, depth+1); failure != nil {
				return failure
			}
		}
		w.output.WriteString("}")
	}
	return nil
}

// blockAfterIndicator emits one block-context node after an indicator
// (materialization.rs:540-575).
func (w *graphWriter) blockAfterIndicator(id graph.NodeID, childIndent, depth int) *GraphMaterializationFailure {
	if w.emitted[id] {
		w.output.WriteString(" ")
		return w.writeAlias(id)
	}
	node, _ := w.layout.graph.Node(id)
	block := false
	switch node.Kind() {
	case graph.KindSequence:
		items, _ := node.SequenceItems()
		block = len(items) > 0
	case graph.KindMapping:
		entries, _ := node.MappingEntries()
		block = len(entries) > 0
	}
	if failure := w.beginDefinition(id, depth); failure != nil {
		return failure
	}
	w.output.WriteString(" ")
	if failure := w.writeProperties(id); failure != nil {
		return failure
	}
	switch node.Kind() {
	case graph.KindScalar:
		w.output.WriteString(" ")
		content, _ := node.ScalarContent()
		return w.writeQuoted(scalarPresentation(node.Tag(), content))
	case graph.KindSequence:
		if block {
			w.output.WriteString(string(w.newline.Bytes()))
			return w.blockContent(id, childIndent, depth)
		}
		w.output.WriteString(" []")
	case graph.KindMapping:
		if block {
			w.output.WriteString(string(w.newline.Bytes()))
			return w.blockContent(id, childIndent, depth)
		}
		w.output.WriteString(" {}")
	}
	return nil
}

// blockContent emits the block layout of one collection
// (materialization.rs:577-627).
func (w *graphWriter) blockContent(id graph.NodeID, indent, depth int) *GraphMaterializationFailure {
	node, _ := w.layout.graph.Node(id)
	first := true
	switch node.Kind() {
	case graph.KindSequence:
		items, _ := node.SequenceItems()
		for _, item := range items {
			if !first {
				w.output.WriteString(string(w.newline.Bytes()))
			}
			first = false
			w.writeIndent(indent)
			w.output.WriteString("-")
			if failure := w.blockAfterIndicator(item, indent+2, depth+1); failure != nil {
				return failure
			}
		}
	case graph.KindMapping:
		entries, _ := node.MappingEntries()
		for _, entry := range entries {
			if !first {
				w.output.WriteString(string(w.newline.Bytes()))
			}
			first = false
			w.writeIndent(indent)
			w.output.WriteString("?")
			if failure := w.blockAfterIndicator(entry.Key, indent+2, depth+1); failure != nil {
				return failure
			}
			w.output.WriteString(string(w.newline.Bytes()))
			w.writeIndent(indent)
			w.output.WriteString(":")
			if failure := w.blockAfterIndicator(entry.Value, indent+2, depth+1); failure != nil {
				return failure
			}
		}
	}
	return nil
}

func (w *graphWriter) writeIndent(indent int) {
	for index := 0; index < indent; index++ {
		w.output.WriteString(" ")
	}
}

// beginDefinition charges one definition visit (materialization.rs:
// 629-645).
func (w *graphWriter) beginDefinition(id graph.NodeID, depth int) *GraphMaterializationFailure {
	if depth > w.limits.MaxDepth {
		return materializationResourceFailure("input-depth", depth, w.limits.MaxDepth)
	}
	if w.emitted[id] {
		return &GraphMaterializationFailure{Kind: GraphMaterializationFailureRoundTripMismatch,
			Node: id}
	}
	w.emitted[id] = true
	if len(w.analyzed) >= w.limits.MaxInputNodes {
		return materializationResourceFailure("input-nodes", len(w.analyzed)+1, w.limits.MaxInputNodes)
	}
	w.analyzed = append(w.analyzed, id)
	w.layout.analyzed = append(w.layout.analyzed, id)
	return nil
}

// writeProperties emits the anchor and the explicit `!!` tag
// (materialization.rs:669-687).
func (w *graphWriter) writeProperties(id graph.NodeID) *GraphMaterializationFailure {
	if anchor, ok := w.layout.anchors[id]; ok {
		w.output.WriteString(fmt.Sprintf("&g%d ", anchor))
	}
	node, _ := w.layout.graph.Node(id)
	suffix, ok := strings.CutPrefix(node.Tag(), "tag:yaml.org,2002:")
	if !ok {
		return &GraphMaterializationFailure{Kind: GraphMaterializationFailureUnsupportedTag,
			Node: id, Tag: node.Tag()}
	}
	w.output.WriteString("!!")
	w.output.WriteString(suffix)
	return nil
}

// writeAlias emits one `*gN` alias (materialization.rs:659-667).
func (w *graphWriter) writeAlias(id graph.NodeID) *GraphMaterializationFailure {
	anchor, ok := w.layout.anchors[id]
	if !ok {
		return &GraphMaterializationFailure{Kind: GraphMaterializationFailureRoundTripMismatch,
			Node: id}
	}
	w.output.WriteString(fmt.Sprintf("*g%d", anchor))
	return nil
}

// writeQuoted emits the canonical double-quoted scalar
// (materialization.rs:689-709).
func (w *graphWriter) writeQuoted(value string) *GraphMaterializationFailure {
	text := "\""
	for _, character := range value {
		switch character {
		case '"':
			text += `\"`
		case '\\':
			text += `\\`
		case 0x08:
			text += `\b`
		case '\t':
			text += `\t`
		case '\n':
			text += `\n`
		case 0x0C:
			text += `\f`
		case '\r':
			text += `\r`
		default:
			if character <= 0x1F || character == 0x7F {
				text += fmt.Sprintf(`\u%04x`, character)
				continue
			}
			text += string(character)
		}
	}
	text += "\""
	return w.pushOutput(text)
}

func (w *graphWriter) pushOutput(text string) *GraphMaterializationFailure {
	if w.output.Len()+len(text) > w.limits.MaxOutputBytes {
		return materializationResourceFailure("output-bytes", w.output.Len()+len(text),
			w.limits.MaxOutputBytes)
	}
	w.output.WriteString(text)
	return nil
}

// scalarPresentation rewrites integer-looking float canonicals to the
// `e0` form (materialization.rs:719-728).
func scalarPresentation(tag, canonical string) string {
	if tag == tagFloat && canonical != ".inf" && canonical != "-.inf" && canonical != ".nan" &&
		!strings.ContainsAny(canonical, ".eE") {
		return canonical + "e0"
	}
	return canonical
}

// encodeOutput encodes the assembled text into the target encoding with
// the matching BOM (materialization.rs:775-819).
func encodeOutput(text string, encoding document.SourceEncoding,
	maxBytes int) ([]byte, *MaterializationFailure) {
	switch encoding.Kind() {
	case document.EncodingUtf8:
		if len(text) > maxBytes {
			return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "output-bytes"}
		}
		return []byte(text), nil
	case document.EncodingUtf16Le, document.EncodingUtf16Be:
		units := 0
		for _, character := range text {
			if character >= 0x10000 {
				units += 2
			} else {
				units++
			}
		}
		length := units*2 + 2
		if length > maxBytes {
			return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "output-bytes"}
		}
		output := make([]byte, 0, length)
		if encoding.Kind() == document.EncodingUtf16Le {
			output = append(output, 0xff, 0xfe)
		} else {
			output = append(output, 0xfe, 0xff)
		}
		for _, character := range text {
			if character >= 0x10000 {
				value := character - 0x10000
				first := 0xD800 + value>>10
				second := 0xDC00 + value&0x3FF
				output = appendUTF16(output, uint16(first), encoding.Kind() == document.EncodingUtf16Le)
				output = appendUTF16(output, uint16(second), encoding.Kind() == document.EncodingUtf16Le)
				continue
			}
			output = appendUTF16(output, uint16(character), encoding.Kind() == document.EncodingUtf16Le)
		}
		return output, nil
	}
	return nil, &MaterializationFailure{Kind: MaterializationUnsupportedEncoding}
}

func appendUTF16(output []byte, unit uint16, littleEndian bool) []byte {
	if littleEndian {
		return append(output, byte(unit), byte(unit>>8))
	}
	return append(output, byte(unit>>8), byte(unit))
}

// collectGraphProvenance builds the input-to-output provenance of one
// graph materialization (materialization.rs:821-1056).
func collectGraphProvenance(graphValue *graph.Graph, document *Document,
	limits document.MaterializationLimits) (GraphMaterializationProvenanceMap, *GraphMaterializationFailure) {
	if len(graphValue.Roots()) != document.DocumentCount() {
		return GraphMaterializationProvenanceMap{},
			&GraphMaterializationFailure{Kind: GraphMaterializationFailureRoundTripMismatch}
	}
	var entries []GraphMaterializationProvenanceEntry
	index := make(map[GraphMaterializationInputLocation]int)
	units := 0
	add := func(location GraphMaterializationInputLocation,
		origin MaterializedOrigin) *GraphMaterializationFailure {
		if existing, ok := index[location]; ok {
			units++
			if units > limits.MaxProvenanceEntries {
				return materializationResourceFailure("provenance-entries", units,
					limits.MaxProvenanceEntries)
			}
			entries[existing].Outputs = append(entries[existing].Outputs, origin)
			return nil
		}
		units += 2
		if units > limits.MaxProvenanceEntries {
			return materializationResourceFailure("provenance-entries", units,
				limits.MaxProvenanceEntries)
		}
		index[location] = len(entries)
		entries = append(entries, GraphMaterializationProvenanceEntry{
			Input: location, Outputs: []MaterializedOrigin{origin},
		})
		return nil
	}
	for ordinal := 0; ordinal < document.DocumentCount(); ordinal++ {
		doc, _ := document.Document(ordinal)
		origin := MaterializedOrigin{
			Snapshot: document.SnapshotIdentity(),
			Node:     doc.NodeRef(),
			Span:     doc.Span(),
			Relation: MaterializationRelationGenerated,
		}
		if failure := add(GraphMaterializationInputLocation{Kind: "Root", Ordinal: uint64(ordinal)},
			origin); failure != nil {
			return GraphMaterializationProvenanceMap{}, failure
		}
	}
	seen := make(map[graph.NodeID]bool)
	var collect func(id graph.NodeID, ordinal int,
		kind string) *GraphMaterializationFailure
	collect = func(id graph.NodeID, ordinal int,
		kind string) *GraphMaterializationFailure {
		if seen[id] {
			return nil
		}
		seen[id] = true
		node, ok := graphValue.Node(id)
		if !ok {
			return &GraphMaterializationFailure{Kind: GraphMaterializationFailureRoundTripMismatch,
				Node: id}
		}
		location := GraphMaterializationInputLocation{Kind: "Node"}
		origin := MaterializedOrigin{
			Snapshot: document.SnapshotIdentity(),
			Node:     document.nodeRef(nativeIndexFor(document, id)),
			Span:     document.native.nodes[nativeIndexFor(document, id)].span,
			Relation: MaterializationRelationDirect,
		}
		if failure := add(location, origin); failure != nil {
			return failure
		}
		switch node.Kind() {
		case graph.KindSequence:
			items, _ := node.SequenceItems()
			for itemOrdinal, item := range items {
				edgeLocation := GraphMaterializationInputLocation{
					Kind: "SequenceElement", Parent: id, Ordinal: uint64(itemOrdinal),
				}
				if failure := collect(item, itemOrdinal, "SequenceElement"); failure != nil {
					return failure
				}
				edgeNode := edgeNodeOf(document, id, itemOrdinal, "SequenceElement")
				edgeOrigin := MaterializedOrigin{
					Snapshot: document.SnapshotIdentity(),
					Node:     edgeNode.NodeRef(),
					Span:     edgeNode.Span(),
					Relation: MaterializationRelationDirect,
				}
				if failure := add(edgeLocation, edgeOrigin); failure != nil {
					return failure
				}
			}
		case graph.KindMapping:
			entries, _ := node.MappingEntries()
			for entryOrdinal, entry := range entries {
				if failure := collect(entry.Key, entryOrdinal, "MappingKey"); failure != nil {
					return failure
				}
				edgeLocation := GraphMaterializationInputLocation{
					Kind: "MappingKey", Parent: id, Ordinal: uint64(entryOrdinal),
				}
				keyEdge := edgeNodeOf(document, id, entryOrdinal, "MappingKey")
				keyOrigin := MaterializedOrigin{
					Snapshot: document.SnapshotIdentity(),
					Node:     keyEdge.NodeRef(),
					Span:     keyEdge.Span(),
					Relation: MaterializationRelationDirect,
				}
				if failure := add(edgeLocation, keyOrigin); failure != nil {
					return failure
				}
				if failure := collect(entry.Value, entryOrdinal, "MappingValue"); failure != nil {
					return failure
				}
				valueLocation := GraphMaterializationInputLocation{
					Kind: "MappingValue", Parent: id, Ordinal: uint64(entryOrdinal),
				}
				valueEdge := edgeNodeOf(document, id, entryOrdinal, "MappingValue")
				valueOrigin := MaterializedOrigin{
					Snapshot: document.SnapshotIdentity(),
					Node:     valueEdge.NodeRef(),
					Span:     valueEdge.Span(),
					Relation: MaterializationRelationDirect,
				}
				if failure := add(valueLocation, valueOrigin); failure != nil {
					return failure
				}
			}
		}
		return nil
	}
	for ordinal := 0; ordinal < document.DocumentCount(); ordinal++ {
		if failure := collect(graphValue.Roots()[ordinal], 0, "Root"); failure != nil {
			return GraphMaterializationProvenanceMap{}, failure
		}
	}
	return GraphMaterializationProvenanceMap{entries: entries}, nil
}

// nativeIndexFor resolves the native node index of one graph node in the
// reparsed document (the projection reserves nodes in native order, so the
// graph IDs align with the native indexes).
func nativeIndexFor(document *Document, id graph.NodeID) int {
	return int(id.AsUint64())
}

// edgeNodeOf resolves the materialized edge node for one association.
func edgeNodeOf(document *Document, parent graph.NodeID, ordinal int,
	kind string) YamlNode {
	index := nativeIndexFor(document, parent)
	content := &document.native.nodes[index].content
	if kind == "SequenceElement" {
		item := content.items[ordinal]
		return YamlNode{owner: document, index: item.node}
	}
	entry := content.entries[ordinal]
	return YamlNode{owner: document, index: entry.value}
}

// materializeValue materializes one complete PortableValue into a new
// immutable YAML document (materialization.rs:1063-1078). ExactOnly is
// the frozen representability policy: a unique-string EntryMapping
// requires the explicit UniqueStringEntriesToObject transformation policy,
// and every local conversion is reported.
func MaterializeValue(value core.Value,
	request document.MaterializationRequest) MaterializationResult {
	_, _, failure := requestedContract(request)
	if failure != nil {
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure: *failure,
		}}
	}
	attempt := &valueMaterializationAttempt{}
	prepared, failure := prepareValue(value, protocol.RootValuePath(), 0, request, attempt)
	if failure != nil {
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure: *failure, Report: attempt.report(), AnalyzedInputPaths: attempt.analyzed,
		}}
	}
	graphValue, failure := valueGraph(prepared, request.Limits())
	if failure != nil {
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure: *failure, Report: attempt.report(), AnalyzedInputPaths: attempt.analyzed,
		}}
	}
	graphLimits := request.Limits()
	graphLimits.MaxInputNodes = request.Limits().MaxInputNodes*2 + 1
	graphRequest := request
	graphRequest = graphRequest.WithLimits(graphLimits)
	graphResult := MaterializeGraph(graphValue, graphRequest)
	if graphResult.Failed != nil {
		inner := graphResult.Failed.Failure
		if inner.Kind == GraphMaterializationFailureMaterialization {
			return MaterializationResult{Failed: &FailedMaterializationAttempt{
				Failure: *inner.Underlying, Report: attempt.report(),
				AnalyzedInputPaths: attempt.analyzed,
			}}
		}
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure: MaterializationFailure{Kind: MaterializationFormationFailed},
			Report:  attempt.report(), AnalyzedInputPaths: attempt.analyzed,
		}}
	}
	document := graphResult.Complete.Document
	reprojected := document.ProjectValue(BestExactValueV1())
	if reprojected.Failed != nil || reprojected.Complete.Fidelity != FidelityExact ||
		!core.Equal(reprojected.Complete.Value, prepared) {
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure: MaterializationFailure{Kind: MaterializationFormationFailed},
			Report:  attempt.report(), AnalyzedInputPaths: attempt.analyzed,
		}}
	}
	provenance, failure := collectValueProvenance(prepared, document, request.Limits())
	if failure != nil {
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure: *failure, Report: attempt.report(), AnalyzedInputPaths: attempt.analyzed,
		}}
	}
	fidelity := MaterializationFidelityExact
	if len(attempt.events) > 0 {
		fidelity = MaterializationFidelityTransformed
	}
	return MaterializationResult{Complete: &CompleteMaterialization{
		Document:   document,
		Fidelity:   fidelity,
		Report:     attempt.report(),
		Provenance: provenance,
	}}
}

// valueMaterializationAttempt accumulates the transformation events and
// analyzed paths of one value materialization.
type valueMaterializationAttempt struct {
	events     []*protocol.Diagnostic
	analyzed   []protocol.ValuePath
	inputNodes int
}

func (a *valueMaterializationAttempt) report() MaterializationReport {
	return MaterializationReport{events: a.events}
}

// prepareValue validates and clones one portable value
// (materialization.rs:1146-1490).
func prepareValue(value core.Value, path protocol.ValuePath, depth int,
	request document.MaterializationRequest,
	attempt *valueMaterializationAttempt) (core.Value, *MaterializationFailure) {
	if depth > request.Limits().MaxDepth {
		return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "input-depth"}
	}
	attempt.inputNodes++
	if attempt.inputNodes > request.Limits().MaxInputNodes {
		return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "input-nodes"}
	}
	attempt.analyzed = append(attempt.analyzed, path)
	switch typed := value.(type) {
	case core.Null, core.Boolean, core.Integer, core.Decimal, core.String, core.Bytes:
		return typed, nil
	case core.BinaryFloat64:
		switch uint64(typed) {
		case 0x7ff0000000000000, 0xfff0000000000000, 0x7ff8000000000000:
			return typed, nil
		}
		return nil, unrepresentable(path, "BinaryFloat64")
	case core.Date:
		if _, ok := canonicalDate(typed); !ok {
			return nil, unrepresentable(path, "Date")
		}
		return typed, nil
	case core.OffsetDateTime:
		_, ok, failure := canonicalOffsetDateTime(typed, request.Limits().MaxOutputBytes)
		if failure != nil {
			return nil, failure
		}
		if !ok {
			return nil, unrepresentable(path, "OffsetDateTime")
		}
		return typed, nil
	case *core.Array:
		items := typed.Items()
		prepared := make([]core.Value, 0, len(items))
		for ordinal, item := range items {
			childPath := path.Child(protocol.ValuePathSegment{Kind: "SequenceElement",
				Index: uint64(ordinal)})
			value, failure := prepareValue(item, childPath, depth+1, request, attempt)
			if failure != nil {
				return nil, failure
			}
			prepared = append(prepared, value)
		}
		return core.NewArray(prepared...), nil
	case *core.Object:
		entries := typed.Entries()
		prepared := make([]core.Entry, 0, len(entries))
		for _, entry := range entries {
			childPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue",
				Key: entry.Key})
			value, failure := prepareValue(entry.Value, childPath, depth+1, request, attempt)
			if failure != nil {
				return nil, failure
			}
			prepared = append(prepared, core.Entry{Key: entry.Key, Value: value})
		}
		object, err := core.NewObject(prepared...)
		if err != nil {
			return nil, &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
		return object, nil
	case *core.EntryMapping:
		return prepareMapping(typed, path, depth, request, attempt)
	}
	return nil, unrepresentable(path, kindNameOf(value))
}

// prepareMapping applies the mapping transformation policy to one
// EntryMapping (materialization.rs:1248-1335).
func prepareMapping(mapping *core.EntryMapping, path protocol.ValuePath, depth int,
	request document.MaterializationRequest,
	attempt *valueMaterializationAttempt) (core.Value, *MaterializationFailure) {
	entries := mapping.Entries()
	keys := make(map[string]bool, len(entries))
	objectEligible := true
	for _, entry := range entries {
		key, ok := entry.Key.(core.String)
		if !ok || keys[string(key)] {
			objectEligible = false
			break
		}
		keys[string(key)] = true
	}
	if !objectEligible {
		prepared := make([]core.EntryMappingEntry, 0, len(entries))
		for ordinal, entry := range entries {
			keyPath := path.Child(protocol.ValuePathSegment{Kind: "EntryKey",
				Index: uint64(ordinal)})
			key, failure := prepareValue(entry.Key, keyPath, depth+1, request, attempt)
			if failure != nil {
				return nil, failure
			}
			valuePath := path.Child(protocol.ValuePathSegment{Kind: "EntryValue",
				Index: uint64(ordinal)})
			value, failure := prepareValue(entry.Value, valuePath, depth+1, request, attempt)
			if failure != nil {
				return nil, failure
			}
			prepared = append(prepared, core.EntryMappingEntry{Key: key, Value: value})
		}
		result, err := core.NewEntryMapping(prepared...)
		if err != nil {
			return nil, &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
		return result, nil
	}
	if request.MappingPolicy() != document.MappingPolicyUniqueStringEntriesToObject {
		return nil, unrepresentable(path, "EntryMapping")
	}
	event, err := protocol.NewDiagnostic("core.materialization.mapping-transformed@1",
		protocol.CategoryMaterialization, protocol.SeverityInfo, nil, nil, map[string]string{
			"from":   "EntryMapping",
			"policy": "UniqueStringEntriesToObject",
			"to":     "Object",
			"path":   path.LenString(),
		}, nil, nil, 0, protocol.NewErrorCodeRegistry(protocol.ErrorRegistryV7))
	if err != nil {
		return nil, &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	if len(attempt.events)+1 > request.Limits().MaxReportEntries {
		return nil, &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "report-entries"}
	}
	attempt.events = append(attempt.events, event)
	prepared := make([]core.Entry, 0, len(entries))
	for _, entry := range entries {
		valuePath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue",
			Key: string(entry.Key.(core.String))})
		value, failure := prepareValue(entry.Value, valuePath, depth+1, request, attempt)
		if failure != nil {
			return nil, failure
		}
		prepared = append(prepared, core.Entry{Key: string(entry.Key.(core.String)),
			Value: value})
	}
	object, err := core.NewObject(prepared...)
	if err != nil {
		return nil, &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	return object, nil
}

// canonicalDate formats one core Date in the frozen YYYY-MM-DD form
// (materialization.rs:1505-1510).
func canonicalDate(value core.Date) (string, bool) {
	year := value.Year().Int()
	if !year.IsInt64() {
		return "", false
	}
	yearNumber := year.Int64()
	if yearNumber < 0 || yearNumber > 9999 {
		return "", false
	}
	return fmt.Sprintf("%04d-%02d-%02d", yearNumber, value.Month(), value.Day()), true
}

// canonicalOffsetDateTime formats one core OffsetDateTime
// (materialization.rs:1512-1543).
func canonicalOffsetDateTime(value core.OffsetDateTime,
	maxOutputBytes int) (string, bool, *MaterializationFailure) {
	date, ok := canonicalDate(value.Local().Date())
	if !ok {
		return "", false, nil
	}
	fraction, failure := canonicalFraction(value.Local().Time().FractionalSecond(), maxOutputBytes)
	if failure != nil {
		return "", false, failure
	}
	seconds := value.OffsetSeconds()
	if seconds%60 != 0 {
		return "", false, nil
	}
	zone := "Z"
	if seconds != 0 {
		absolute := seconds
		sign := byte('+')
		if absolute < 0 {
			sign = '-'
			absolute = -absolute
		}
		zone = string([]byte{sign}) + fmt.Sprintf("%02d:%02d", absolute/3600, (absolute%3600)/60)
	}
	output := fmt.Sprintf("%sT%02d:%02d:%02d%s%s", date,
		value.Local().Time().Hour(), value.Local().Time().Minute(),
		value.Local().Time().Second(), fraction, zone)
	if len(output) > maxOutputBytes {
		return "", false, &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "output-bytes"}
	}
	return output, true, nil
}

// canonicalFraction formats one fractional second (materialization.rs:
// 1545-1572).
func canonicalFraction(fraction core.Decimal, maxOutputBytes int) (string, *MaterializationFailure) {
	coefficient := fraction.Coefficient()
	if coefficient.Sign() == 0 {
		return "", nil
	}
	if coefficient.Sign() < 0 {
		return "", &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	exponent := fraction.Exponent()
	if !exponent.IsInt64() {
		return "", &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	exponentNumber := exponent.Int64()
	if exponentNumber >= 0 {
		return "", &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	places := -exponentNumber
	digits := coefficient.String()
	if int64(len(digits)) > places {
		return "", &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	if places+1 > int64(maxOutputBytes) {
		return "", &MaterializationFailure{Kind: MaterializationResourceLimit,
			LimitName: "output-bytes"}
	}
	zeros := ""
	for index := int64(0); index < places-int64(len(digits)); index++ {
		zeros += "0"
	}
	return "." + zeros + digits, nil
}

func unrepresentable(path protocol.ValuePath, kind string) *MaterializationFailure {
	return &MaterializationFailure{Kind: MaterializationUnrepresentable, Path: path,
		KindName: kind}
}

func kindNameOf(value core.Value) string {
	switch value.(type) {
	case core.Null:
		return "Null"
	case core.Boolean:
		return "Boolean"
	case core.Integer:
		return "Integer"
	case core.Decimal:
		return "Decimal"
	case core.BinaryFloat32:
		return "BinaryFloat32"
	case core.BinaryFloat64:
		return "BinaryFloat64"
	case core.String:
		return "String"
	case core.Bytes:
		return "Bytes"
	case core.Date:
		return "Date"
	case core.Time:
		return "Time"
	case core.LocalDateTime:
		return "LocalDateTime"
	case core.OffsetDateTime:
		return "OffsetDateTime"
	case *core.Array:
		return "Sequence"
	case *core.Object:
		return "Object"
	case *core.EntryMapping:
		return "EntryMapping"
	}
	return "Unknown"
}

// valueGraph builds one PortableGraph from a prepared value
// (materialization.rs:1337-1490).
func valueGraph(value core.Value,
	limits document.MaterializationLimits) (*graph.Graph, *MaterializationFailure) {
	builder := graph.NewBuilder(graph.Limits{
		MaxRoots:            1,
		MaxNodes:            limits.MaxInputNodes*2 + 1,
		MaxEdges:            limits.MaxInputNodes * 4,
		MaxContainerEntries: limits.MaxInputNodes,
		MaxTagBytes:         64,
		MaxScalarBytes:      limits.MaxOutputBytes,
		MaxTraversalDepth:   limits.MaxDepth,
	})
	root, failure := defineValueNode(builder, value, limits)
	if failure != nil {
		return nil, failure
	}
	if err := builder.PushRoot(root); err != nil {
		return nil, graphBuildFailure(err)
	}
	result, err := builder.Build()
	if err != nil {
		return nil, graphBuildFailure(err)
	}
	return result, nil
}

// defineValueNode defines one graph node for one prepared value
// (materialization.rs:1356-1490).
func defineValueNode(builder *graph.Builder, value core.Value,
	limits document.MaterializationLimits) (graph.NodeID, *MaterializationFailure) {
	id, err := builder.ReserveNode()
	if err != nil {
		return graph.NodeID{}, graphBuildFailure(err)
	}
	switch typed := value.(type) {
	case core.Null:
		if err := builder.DefineScalar(id, tagNull, ""); err != nil {
			return graph.NodeID{}, graphBuildFailure(err)
		}
	case core.Boolean:
		text := "false"
		if typed {
			text = "true"
		}
		if err := builder.DefineScalar(id, tagBool, text); err != nil {
			return graph.NodeID{}, graphBuildFailure(err)
		}
	case core.Integer:
		if err := builder.DefineScalar(id, tagInt, typed.Int().String()); err != nil {
			return graph.NodeID{}, graphBuildFailure(err)
		}
	case core.Decimal:
		text := typed.Coefficient().String()
		if typed.Exponent().Sign() != 0 {
			text = typed.Coefficient().String() + "e" + typed.Exponent().String()
		}
		if err := builder.DefineScalar(id, tagFloat, text); err != nil {
			return graph.NodeID{}, graphBuildFailure(err)
		}
	case core.BinaryFloat64:
		var text string
		switch uint64(typed) {
		case 0x7ff0000000000000:
			text = ".inf"
		case 0xfff0000000000000:
			text = "-.inf"
		case 0x7ff8000000000000:
			text = ".nan"
		default:
			return graph.NodeID{}, &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
		if err := builder.DefineScalar(id, tagFloat, text); err != nil {
			return graph.NodeID{}, graphBuildFailure(err)
		}
	case core.String:
		if err := builder.DefineScalar(id, tagStr, string(typed)); err != nil {
			return graph.NodeID{}, graphBuildFailure(err)
		}
	case core.Bytes:
		encoded := encodeBase64([]byte(typed))
		if len(encoded) > limits.MaxOutputBytes {
			return graph.NodeID{}, &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "output-bytes"}
		}
		if err := builder.DefineScalar(id, tagBinary, encoded); err != nil {
			return graph.NodeID{}, graphBuildFailure(err)
		}
	case core.Date:
		text, ok := canonicalDate(typed)
		if !ok {
			return graph.NodeID{}, &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
		if err := builder.DefineScalar(id, tagTimestamp, text); err != nil {
			return graph.NodeID{}, graphBuildFailure(err)
		}
	case core.OffsetDateTime:
		text, ok, failure := canonicalOffsetDateTime(typed, limits.MaxOutputBytes)
		if failure != nil {
			return graph.NodeID{}, failure
		}
		if !ok {
			return graph.NodeID{}, &MaterializationFailure{Kind: MaterializationFormationFailed}
		}
		if err := builder.DefineScalar(id, tagTimestamp, text); err != nil {
			return graph.NodeID{}, graphBuildFailure(err)
		}
	case *core.Array:
		items := typed.Items()
		ids := make([]graph.NodeID, 0, len(items))
		for _, item := range items {
			child, failure := defineValueNode(builder, item, limits)
			if failure != nil {
				return graph.NodeID{}, failure
			}
			ids = append(ids, child)
		}
		if err := builder.DefineSequence(id, tagSeq, ids); err != nil {
			return graph.NodeID{}, graphBuildFailure(err)
		}
	case *core.Object:
		entries := typed.Entries()
		graphEntries := make([]graph.MappingEntry, 0, len(entries))
		for _, entry := range entries {
			key, failure := defineValueNode(builder, core.String(entry.Key), limits)
			if failure != nil {
				return graph.NodeID{}, failure
			}
			child, failure := defineValueNode(builder, entry.Value, limits)
			if failure != nil {
				return graph.NodeID{}, failure
			}
			graphEntries = append(graphEntries, graph.MappingEntry{Key: key, Value: child})
		}
		if err := builder.DefineMapping(id, tagMap, graphEntries); err != nil {
			return graph.NodeID{}, graphBuildFailure(err)
		}
	case *core.EntryMapping:
		entries := typed.Entries()
		graphEntries := make([]graph.MappingEntry, 0, len(entries))
		for _, entry := range entries {
			key, failure := defineValueNode(builder, entry.Key, limits)
			if failure != nil {
				return graph.NodeID{}, failure
			}
			child, failure := defineValueNode(builder, entry.Value, limits)
			if failure != nil {
				return graph.NodeID{}, failure
			}
			graphEntries = append(graphEntries, graph.MappingEntry{Key: key, Value: child})
		}
		if err := builder.DefineMapping(id, tagMap, graphEntries); err != nil {
			return graph.NodeID{}, graphBuildFailure(err)
		}
	default:
		return graph.NodeID{}, &MaterializationFailure{Kind: MaterializationFormationFailed}
	}
	return id, nil
}

// encodeBase64 encodes bytes with the standard alphabet and padding.
func encodeBase64(value []byte) string {
	const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
	var builder strings.Builder
	for offset := 0; offset < len(value); offset += 3 {
		var chunk [3]byte
		count := copy(chunk[:], value[offset:])
		accumulator := uint32(chunk[0])<<16 | uint32(chunk[1])<<8 | uint32(chunk[2])
		builder.WriteByte(alphabet[(accumulator>>18)&0x3F])
		builder.WriteByte(alphabet[(accumulator>>12)&0x3F])
		if count > 1 {
			builder.WriteByte(alphabet[(accumulator>>6)&0x3F])
		} else {
			builder.WriteByte('=')
		}
		if count > 2 {
			builder.WriteByte(alphabet[accumulator&0x3F])
		} else {
			builder.WriteByte('=')
		}
	}
	return builder.String()
}

// graphBuildFailure maps one graph construction failure onto the shared
// materialization failure contract (materialization.rs:1337-1354).
func graphBuildFailure(err error) *MaterializationFailure {
	if graphError, ok := err.(*graph.GraphError); ok {
		if graphError.Kind == graph.ErrGraphResourceLimit {
			return &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: graphError.Field}
		}
		if graphError.Kind == graph.ErrGraphSizeOverflow {
			return &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "graph-size"}
		}
	}
	return &MaterializationFailure{Kind: MaterializationFormationFailed}
}

// collectValueProvenance builds the input-to-output provenance of one
// value materialization.
func collectValueProvenance(value core.Value, document *Document,
	limits document.MaterializationLimits) (MaterializationProvenanceMap, *MaterializationFailure) {
	var entries []MaterializationProvenanceEntry
	index := make(map[string]int)
	units := 0
	add := func(location MaterializationInputLocation,
		origin MaterializedOrigin) *MaterializationFailure {
		key := materializationInputKey(location)
		if existing, ok := index[key]; ok {
			units++
			if units > limits.MaxProvenanceEntries {
				return &MaterializationFailure{Kind: MaterializationResourceLimit,
					LimitName: "provenance-entries"}
			}
			entries[existing].Outputs = append(entries[existing].Outputs, origin)
			return nil
		}
		units += 2
		if units > limits.MaxProvenanceEntries {
			return &MaterializationFailure{Kind: MaterializationResourceLimit,
				LimitName: "provenance-entries"}
		}
		index[key] = len(entries)
		entries = append(entries, MaterializationProvenanceEntry{
			Input: location, Outputs: []MaterializedOrigin{origin},
		})
		return nil
	}
	var collect func(value core.Value, path protocol.ValuePath,
		node YamlNode, transformed bool) *MaterializationFailure
	collect = func(value core.Value, path protocol.ValuePath, node YamlNode,
		transformed bool) *MaterializationFailure {
		relation := MaterializationRelationDirect
		if transformed {
			relation = MaterializationRelationReencoded
		}
		origin := MaterializedOrigin{Snapshot: document.SnapshotIdentity(),
			Node: node.NodeRef(), Span: node.Span(), Relation: relation}
		if failure := add(MaterializationInputLocation{Kind: "Value", Path: path}, origin); failure != nil {
			return failure
		}
		switch typed := value.(type) {
		case *core.Array:
			elements := node.sequenceElements()
			items := typed.Items()
			if len(items) != len(elements) {
				return &MaterializationFailure{Kind: MaterializationFormationFailed}
			}
			for ordinal, element := range elements {
				childPath := path.Child(protocol.ValuePathSegment{Kind: "SequenceElement",
					Index: uint64(ordinal)})
				if failure := collect(items[ordinal], childPath, element.Node(), false); failure != nil {
					return failure
				}
				generated := MaterializedOrigin{Snapshot: document.SnapshotIdentity(),
					Node: element.NodeRef(), Span: element.Span(),
					Relation: MaterializationRelationGenerated}
				if failure := add(MaterializationInputLocation{Kind: "Value", Path: childPath},
					generated); failure != nil {
					return failure
				}
			}
		case *core.Object:
			entries := node.mappingEntries()
			inputs := typed.Entries()
			if len(inputs) != len(entries) {
				return &MaterializationFailure{Kind: MaterializationFormationFailed}
			}
			for ordinal, entry := range entries {
				association := protocol.NewAssociationLocation(path, uint64(ordinal),
					protocol.AssociationRoleObjectEntry)
				entryOrigin := MaterializedOrigin{Snapshot: document.SnapshotIdentity(),
					Node: entry.NodeRef(), Span: entry.Span(), Relation: MaterializationRelationDirect}
				if failure := add(MaterializationInputLocation{Kind: "Association",
					Association: &association}, entryOrigin); failure != nil {
					return failure
				}
				keyAssociation := protocol.NewAssociationLocation(path, uint64(ordinal),
					protocol.AssociationRoleObjectKey)
				keyOrigin := MaterializedOrigin{Snapshot: document.SnapshotIdentity(),
					Node: entry.Key().NodeRef(), Span: entry.Key().Span(),
					Relation: MaterializationRelationDirect}
				if failure := add(MaterializationInputLocation{Kind: "Association",
					Association: &keyAssociation}, keyOrigin); failure != nil {
					return failure
				}
				childPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue",
					Key: inputs[ordinal].Key})
				if failure := collect(inputs[ordinal].Value, childPath, entry.Value(), false); failure != nil {
					return failure
				}
			}
		case *core.EntryMapping:
			entries := node.mappingEntries()
			inputs := typed.Entries()
			if len(inputs) != len(entries) {
				return &MaterializationFailure{Kind: MaterializationFormationFailed}
			}
			for ordinal, entry := range entries {
				association := protocol.NewAssociationLocation(path, uint64(ordinal),
					protocol.AssociationRoleEntryMappingItem)
				entryOrigin := MaterializedOrigin{Snapshot: document.SnapshotIdentity(),
					Node: entry.NodeRef(), Span: entry.Span(),
					Relation: MaterializationRelationReencoded}
				if failure := add(MaterializationInputLocation{Kind: "Association",
					Association: &association}, entryOrigin); failure != nil {
					return failure
				}
				keyPath := path.Child(protocol.ValuePathSegment{Kind: "EntryKey",
					Index: uint64(ordinal)})
				if failure := collect(inputs[ordinal].Key, keyPath, entry.Key(), true); failure != nil {
					return failure
				}
				valuePath := path.Child(protocol.ValuePathSegment{Kind: "EntryValue",
					Index: uint64(ordinal)})
				if failure := collect(inputs[ordinal].Value, valuePath, entry.Value(), true); failure != nil {
					return failure
				}
			}
		}
		return nil
	}
	doc, _ := document.Document(0)
	if failure := collect(value, protocol.RootValuePath(), doc.Root(), false); failure != nil {
		return MaterializationProvenanceMap{}, failure
	}
	return MaterializationProvenanceMap{entries: entries}, nil
}

// materializationInputKey builds the deterministic unique key of one
// materialization input location.
func materializationInputKey(location MaterializationInputLocation) string {
	if location.Kind == "Association" {
		key := "A" + pathKey(location.Path)
		if location.Association != nil {
			key += "|" + itoaU64(location.Association.Ordinal()) + "|" +
				string(location.Association.Role())
		}
		return key
	}
	return "V" + pathKey(location.Path)
}

// sequenceElements returns the ordered sequence associations of one node.
func (n YamlNode) sequenceElements() []YamlSequenceItem {
	content := &n.owner.native.nodes[n.index].content
	if content.kind != contentSequence {
		return nil
	}
	items := make([]YamlSequenceItem, 0, len(content.items))
	for ordinal := range content.items {
		items = append(items, YamlSequenceItem{owner: n.owner, item: &content.items[ordinal]})
	}
	return items
}

// mappingEntries returns the ordered mapping associations of one node.
func (n YamlNode) mappingEntries() []YamlMappingEntry {
	content := &n.owner.native.nodes[n.index].content
	if content.kind != contentMapping {
		return nil
	}
	entries := make([]YamlMappingEntry, 0, len(content.entries))
	for ordinal := range content.entries {
		entries = append(entries, YamlMappingEntry{owner: n.owner, entry: &content.entries[ordinal]})
	}
	return entries
}
