package xml

// This file implements canonical `xml.safe-canonical-document@1`
// materialization (RFC 0012 §10; consema-rs/consema-xml/src/materialization.rs).
// The style consumes one fully validated `xml.element-tree@1` value and
// creates a new `xml.1.0-safe@1` Document. It is not W3C Canonical XML and
// does not claim C14N equivalence. The style deterministically chooses
// declaration spelling, double-quoted attributes, generated namespace
// prefixes, first-use namespace declaration placement, empty-element
// spelling, reference spelling, and the requested LF/CRLF final newline.
//
// UTF-8, UTF-16LE, and UTF-16BE output are supported under the source
// rules; UTF-16 output always carries its BOM. The complete tree is
// validated before generation, the exact generated bytes are reparsed
// under the promised Profile and encoding, and the reparsed native tree is
// compared to the promised input semantics. Failure returns no target
// Document and no partial output bytes.

import (
	"strings"

	"consema.dev/consema/core"
	"consema.dev/consema/document"
	"consema.dev/consema/protocol"
)

// MaterializationFailureKind is the stable materialization failure
// category (consema-document materialization.rs).
type MaterializationFailureKind uint8

// The closed materialization failure categories.
const (
	// MaterializationFailureInvalidRequest: request fields or input records
	// are contradictory.
	MaterializationFailureInvalidRequest MaterializationFailureKind = iota
	// MaterializationFailureUnsupportedProfile: the target profile is
	// unavailable.
	MaterializationFailureUnsupportedProfile
	// MaterializationFailureUnsupportedStyle: the target style is
	// unavailable for the profile.
	MaterializationFailureUnsupportedStyle
	// MaterializationFailureUnsupportedEncoding: the target encoding is
	// unsupported.
	MaterializationFailureUnsupportedEncoding
	// MaterializationFailureUnsupportedNewline: the target style does not
	// support the newline policy.
	MaterializationFailureUnsupportedNewline
	// MaterializationFailureUnrepresentable: a portable input cannot be
	// represented by the target profile.
	MaterializationFailureUnrepresentable
	// MaterializationFailureResourceLimit: a configured bound was reached;
	// output is not truncated to success.
	MaterializationFailureResourceLimit
	// MaterializationFailureFormationFailed: the generated bytes did not
	// form the required target document.
	MaterializationFailureFormationFailed
)

// MaterializationFailure is the typed materialization failure. It
// implements error and the RFC 0016 §6 Code() contract with the frozen
// registered codes.
type MaterializationFailure struct {
	// Kind identifies the failure.
	Kind MaterializationFailureKind
	// Path is the offending input location of Unrepresentable.
	Path protocol.ValuePath
	// ValueKind is the offending PortableValue kind of Unrepresentable.
	ValueKind core.Kind
	// LimitName is the stable limit name of a ResourceLimit.
	LimitName string
	// Reason is the admission reason of InvalidRequest.
	Reason string
}

// Error implements error.
func (e *MaterializationFailure) Error() string {
	switch e.Kind {
	case MaterializationFailureInvalidRequest:
		return "xml: materialization request is invalid: " + e.Reason
	case MaterializationFailureUnsupportedProfile:
		return "xml: materialization profile is unavailable"
	case MaterializationFailureUnsupportedStyle:
		return "xml: materialization style is unavailable for the profile"
	case MaterializationFailureUnsupportedEncoding:
		return "xml: materialization encoding is unsupported"
	case MaterializationFailureUnsupportedNewline:
		return "xml: materialization newline policy is unsupported by the style"
	case MaterializationFailureUnrepresentable:
		return "xml: portable kind " + e.ValueKind.String() + " is not representable"
	case MaterializationFailureResourceLimit:
		return "xml: materialization limit " + e.LimitName + " reached"
	case MaterializationFailureFormationFailed:
		return "xml: generated bytes did not form the target document"
	}
	return "xml: materialization failure"
}

// Code returns the frozen registered code for the failure.
func (e *MaterializationFailure) Code() string {
	switch e.Kind {
	case MaterializationFailureInvalidRequest:
		return "core.materialization.invalid-request@1"
	case MaterializationFailureUnsupportedProfile:
		return "core.materialization.unsupported-profile@1"
	case MaterializationFailureUnsupportedStyle:
		return "core.materialization.unsupported-style@1"
	case MaterializationFailureUnsupportedEncoding:
		return "core.materialization.unsupported-encoding@1"
	case MaterializationFailureUnsupportedNewline:
		return "core.materialization.unsupported-newline@1"
	case MaterializationFailureUnrepresentable:
		return "core.materialization.unrepresentable@1"
	case MaterializationFailureResourceLimit:
		return "core.materialization.resource-limit@1"
	case MaterializationFailureFormationFailed:
		return "core.materialization.formation-failed@1"
	}
	return "core.materialization.formation-failed@1"
}

// Name returns the stable failure name used by the conformance vectors
// (xml_v1.rs materialization_failure_code).
func (e *MaterializationFailure) Name() string {
	switch e.Kind {
	case MaterializationFailureInvalidRequest:
		return "invalid-record"
	case MaterializationFailureUnsupportedProfile:
		return "unsupported-profile"
	case MaterializationFailureUnsupportedStyle:
		return "unsupported-style"
	case MaterializationFailureUnsupportedEncoding:
		return "unsupported-encoding"
	case MaterializationFailureUnsupportedNewline:
		return "unsupported-newline"
	case MaterializationFailureUnrepresentable:
		return "unrepresentable"
	case MaterializationFailureResourceLimit:
		return "resource-limit"
	case MaterializationFailureFormationFailed:
		return "formation-failed"
	}
	return "formation-failed"
}

// MaterializationFidelity is the closed materialization fidelity
// (consema-document materialization.rs).
type MaterializationFidelity uint8

// The two frozen fidelity classes.
const (
	// MaterializationFidelityExact means every input fact round-trips
	// through the target's exact projection contract.
	MaterializationFidelityExact MaterializationFidelity = iota
	// MaterializationFidelityTransformed means complete semantics survive
	// an explicit reversible re-encoding.
	MaterializationFidelityTransformed
)

// String returns the stable fidelity name.
func (f MaterializationFidelity) String() string {
	switch f {
	case MaterializationFidelityExact:
		return "Exact"
	case MaterializationFidelityTransformed:
		return "Transformed"
	}
	return "Exact"
}

// MaterializationRelation is the source-to-output relation of one
// materialization provenance origin (consema-document materialization.rs).
type MaterializationRelation string

// The three frozen relations.
const (
	// MaterializationRelationDirect is a direct native semantic origin.
	MaterializationRelationDirect MaterializationRelation = "Direct"
	// MaterializationRelationGenerated is a generated structural origin.
	MaterializationRelationGenerated MaterializationRelation = "Generated"
	// MaterializationRelationReencoded is a reversible re-encoding origin.
	MaterializationRelationReencoded MaterializationRelation = "Reencoded"
)

// MaterializedOrigin is one exact output origin.
type MaterializedOrigin struct {
	// Snapshot is the target document snapshot.
	Snapshot document.SnapshotIdentity
	// Node is the exact output structural identity.
	Node document.NodeRef
	// Span is the exact output source range.
	Span document.Span
	// Relation is the source relation.
	Relation MaterializationRelation
}

// MaterializationInputLocation is one input value or association location.
type MaterializationInputLocation struct {
	// IsAssociation reports whether the location is an association.
	IsAssociation bool
	// Path is the input value location.
	Path protocol.ValuePath
	// Association is the input association location.
	Association protocol.AssociationLocation
}

// MaterializationProvenanceEntry is one input-to-outputs mapping entry.
type MaterializationProvenanceEntry struct {
	// Input is the exact input location.
	Input MaterializationInputLocation
	// Outputs are the output origins.
	Outputs []MaterializedOrigin
}

// MaterializationProvenanceMap is the immutable input-to-output
// provenance map.
type MaterializationProvenanceMap struct {
	entries []MaterializationProvenanceEntry
}

// Entries returns the ordered entries. The returned slice is a copy.
func (m *MaterializationProvenanceMap) Entries() []MaterializationProvenanceEntry {
	return append([]MaterializationProvenanceEntry(nil), m.entries...)
}

// MaterializationReport is the complete materialization report; XML
// canonical materialization never transforms, so the report is empty by
// default.
type MaterializationReport struct {
	events []*protocol.Diagnostic
}

// Events returns the ordered report events. The returned slice is a copy.
func (r *MaterializationReport) Events() []*protocol.Diagnostic {
	return append([]*protocol.Diagnostic(nil), r.events...)
}

// CompleteMaterialization is the complete successful materialization.
type CompleteMaterialization struct {
	// Document is the new immutable target document.
	Document *Document
	// Fidelity is the worst fidelity of the whole operation.
	Fidelity MaterializationFidelity
	// Report is the transformation/loss report.
	Report MaterializationReport
	// Provenance is the input-to-output provenance map.
	Provenance MaterializationProvenanceMap
}

// FailedMaterializationAttempt is a failed attempt without a document.
type FailedMaterializationAttempt struct {
	// Failure is the stable failure.
	Failure *MaterializationFailure
	// Report holds the events discovered before the failed completion
	// check.
	Report MaterializationReport
	// AnalyzedInputPaths are the stable path descriptions of locally
	// analyzed input regions.
	AnalyzedInputPaths []protocol.ValuePath
}

// MaterializationResult is the sealed materialization outcome: exactly one
// of Complete or Failed is set.
type MaterializationResult struct {
	// Complete is the successful outcome.
	Complete *CompleteMaterialization
	// Failed is the failed attempt.
	Failed *FailedMaterializationAttempt
}

// Materialize materializes one complete `xml.element-tree@1` record into a
// new immutable canonical XML document (materialization.rs:36-50).
func Materialize(value core.Value, request document.MaterializationRequest) MaterializationResult {
	analyzed := make([]protocol.ValuePath, 0, 16)
	complete, failure := materializeComplete(value, request, &analyzed)
	if failure != nil {
		return MaterializationResult{Failed: &FailedMaterializationAttempt{
			Failure:            failure,
			Report:             MaterializationReport{},
			AnalyzedInputPaths: analyzed,
		}}
	}
	return MaterializationResult{Complete: complete}
}

// materializeComplete runs the two-phase materialization
// (materialization.rs:52-88).
func materializeComplete(value core.Value, request document.MaterializationRequest,
	analyzed *[]protocol.ValuePath) (*CompleteMaterialization, *MaterializationFailure) {
	if failure := validateRequest(request); failure != nil {
		return nil, failure
	}
	input, failure := validateRecord(value, analyzed)
	if failure != nil {
		return nil, failure
	}
	writer := &materializationWriter{
		limits: request.Limits(),
	}
	if failure := writer.emitDocument(input, request); failure != nil {
		return nil, failure
	}
	bytes, failure := encodeText(writer.output, request.Encoding(), request.Limits().MaxOutputBytes)
	if failure != nil {
		return nil, failure
	}
	limits := parseLimitsFor(request.Limits())
	target, formationFailure := Parse(nil, bytes, XmlProfileSafeV1, XmlEncodingProfileDefault(), limits)
	if formationFailure != nil {
		return nil, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	if target.status != document.FormationStatusComplete {
		return nil, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	provenance, failure := verifyClosure(input, target, writer.items, request.Limits())
	if failure != nil {
		return nil, failure
	}
	return &CompleteMaterialization{
		Document:   target,
		Fidelity:   MaterializationFidelityExact,
		Report:     MaterializationReport{},
		Provenance: provenance,
	}, nil
}

// validateRequest checks the request contract (materialization.rs:90-107).
func validateRequest(request document.MaterializationRequest) *MaterializationFailure {
	if request.TargetProfile().ID() != "xml.1.0-safe" || request.TargetProfile().Version() != 1 {
		return &MaterializationFailure{Kind: MaterializationFailureUnsupportedProfile}
	}
	if request.Style().ID() != "xml.safe-canonical-document" || request.Style().Version() != 1 {
		return &MaterializationFailure{Kind: MaterializationFailureUnsupportedStyle}
	}
	encoding := request.Encoding()
	if !encoding.Equal(document.Utf8Encoding()) && !encoding.Equal(document.Utf16LeEncoding()) &&
		!encoding.Equal(document.Utf16BeEncoding()) {
		return &MaterializationFailure{Kind: MaterializationFailureUnsupportedEncoding}
	}
	if request.Newline() != document.NewlineLf && request.Newline() != document.NewlineCrLf {
		return &MaterializationFailure{Kind: MaterializationFailureUnsupportedNewline}
	}
	return nil
}

// parseLimitsFor derives the reparse limits from the materialization
// limits (materialization.rs:109-140).
func parseLimitsFor(limits document.MaterializationLimits) XmlParseLimits {
	return XmlParseLimits{
		Common: document.ParseLimits{
			MaxSourceBytes:  limits.MaxOutputBytes,
			MaxNestingDepth: limits.MaxDepth,
			MaxTokenCount:   limits.MaxOutputBytes,
			MaxNodeCount:    limits.MaxInputNodes,
			MaxDiagnostics:  limits.MaxReportEntries,
		},
		MaxDecodedUTF8Bytes:          limits.MaxOutputBytes * 3,
		MaxDecodedScalars:            limits.MaxOutputBytes,
		MaxElementCount:              limits.MaxInputNodes,
		MaxAttributeCount:            limits.MaxInputNodes,
		MaxNamespaceDeclarationCount: limits.MaxInputNodes,
		MaxMixedContentItems:         limits.MaxInputNodes,
		MaxQNameLength:               limits.MaxOutputBytes,
		MaxNamespaceURILength:        limits.MaxOutputBytes,
		MaxAttributeValueLength:      limits.MaxOutputBytes,
		MaxCommentLength:             limits.MaxOutputBytes,
		MaxPiLength:                  limits.MaxOutputBytes,
		MaxCdataLength:               limits.MaxOutputBytes,
		MaxTextLength:                limits.MaxOutputBytes,
		MaxDtdBytes:                  limits.MaxOutputBytes,
		MaxEntityDeclarations:        limits.MaxInputNodes,
		MaxEntityReferences:          limits.MaxInputNodes,
		MaxEntityExpansionDepth:      limits.MaxDepth,
		MaxExpandedEntityBytes:       limits.MaxOutputBytes,
		MaxExpandedEntityScalars:     limits.MaxOutputBytes,
		MaxEntityAmplificationRatio:  ^uint64(0),
		MaxRecoveryRegions:           limits.MaxReportEntries,
	}
}

// encodeText encodes canonical UTF-8 text into the requested output
// encoding (materialization.rs:143-172).
func encodeText(text []byte, encoding document.SourceEncoding,
	maxOutputBytes int) ([]byte, *MaterializationFailure) {
	var output []byte
	switch {
	case encoding.Equal(document.Utf8Encoding()):
		output = append(output, text...)
	case encoding.Equal(document.Utf16LeEncoding()), encoding.Equal(document.Utf16BeEncoding()):
		decoded := string(text)
		if encoding.Equal(document.Utf16LeEncoding()) {
			output = append(output, 0xFF, 0xFE)
		} else {
			output = append(output, 0xFE, 0xFF)
		}
		for _, unit := range utf16Encode(decoded) {
			if encoding.Equal(document.Utf16LeEncoding()) {
				output = append(output, byte(unit), byte(unit>>8))
			} else {
				output = append(output, byte(unit>>8), byte(unit))
			}
		}
	default:
		return nil, &MaterializationFailure{Kind: MaterializationFailureUnsupportedEncoding}
	}
	if len(output) > maxOutputBytes {
		return nil, &MaterializationFailure{Kind: MaterializationFailureResourceLimit, LimitName: "output-bytes"}
	}
	return output, nil
}

// utf16Encode encodes one string into UTF-16 code units.
func utf16Encode(text string) []uint16 {
	var units []uint16
	for _, r := range text {
		if r >= 0x10000 {
			value := r - 0x10000
			units = append(units, uint16(0xD800+value>>10), uint16(0xDC00+value&0x3FF))
		} else {
			units = append(units, uint16(r))
		}
	}
	return units
}

// record is the validated input record mirroring `xml.element-tree@1`
// (materialization.rs:174-237).
type record struct {
	declaration *declarationRecord
	entities    []entityRecord
	root        *elementRecord
}

type declarationRecord struct {
	version    string
	encoding   *string
	standalone *bool
	path       protocol.ValuePath
}

type entityRecord struct {
	name        string
	replacement string
	path        protocol.ValuePath
}

type elementRecord struct {
	namespace  *string
	local      string
	namespaces []namespacePair
	attributes []attributeRecord
	content    []contentRecord
	path       protocol.ValuePath
}

type namespacePair struct {
	prefix *string
	uri    string
}

type attributeRecord struct {
	namespace *string
	local     string
	value     string
	path      protocol.ValuePath
}

type contentRecord struct {
	kind      contentRecordKind
	element   *elementRecord
	fragments []fragmentRecord
	text      string
	target    string
	content   *string
	path      protocol.ValuePath
}

type contentRecordKind uint8

const (
	contentRecordElement contentRecordKind = iota
	contentRecordText
	contentRecordCdata
	contentRecordComment
	contentRecordProcessingInstruction
)

type fragmentRecord struct {
	kind         fragmentRecordKind
	text         string
	resolved     rune
	name         string
	resolvedText string
}

type fragmentRecordKind uint8

const (
	fragmentRecordLiteral fragmentRecordKind = iota
	fragmentRecordCharacterReference
	fragmentRecordPredefinedEntity
	fragmentRecordGeneralEntity
)

// validateRecord validates the input record (materialization.rs:238-304).
func validateRecord(value core.Value, analyzed *[]protocol.ValuePath) (*record, *MaterializationFailure) {
	*analyzed = append(*analyzed, protocol.RootValuePath())
	recordValue, failure := expectStringField(value, "record", protocol.RootValuePath())
	if failure != nil {
		return nil, failure
	}
	if recordValue != "xml.element-tree@1" {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest,
			Reason: "input record is not xml.element-tree@1"}
	}
	rootPath := protocol.RootValuePath().Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "root"})
	rootValue, failure := expectObjectField(value, "root", rootPath)
	if failure != nil {
		return nil, failure
	}
	var declaration *declarationRecord
	if field, ok := optionalObjectField(value, "declaration"); ok {
		path := protocol.RootValuePath().Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "declaration"})
		version, failure := expectStringField(field, "version", path)
		if failure != nil {
			return nil, failure
		}
		if version != "1.0" {
			return nil, &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
				Path:      path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "version"}),
				ValueKind: core.KindString}
		}
		encoding, failure := optionalStringField(field, "encoding", path)
		if failure != nil {
			return nil, failure
		}
		standalone, failure := optionalBooleanField(field, "standalone", path)
		if failure != nil {
			return nil, failure
		}
		declaration = &declarationRecord{
			version: version, encoding: encoding, standalone: standalone, path: path,
		}
	}
	var entities []entityRecord
	if field, ok := optionalSequenceField(value, "entities"); ok {
		path := protocol.RootValuePath().Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "entities"})
		for index, entity := range field {
			entityPath := path.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
			name, failure := expectStringField(entity, "name", entityPath)
			if failure != nil {
				return nil, failure
			}
			replacement, failure := expectStringField(entity, "replacement", entityPath)
			if failure != nil {
				return nil, failure
			}
			if strings.Contains(replacement, "<") {
				return nil, &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
					Path:      entityPath.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "replacement"}),
					ValueKind: core.KindString}
			}
			entities = append(entities, entityRecord{name: name, replacement: replacement, path: entityPath})
		}
	}
	root, failure := validateElementRecord(rootValue, rootPath, analyzed)
	if failure != nil {
		return nil, failure
	}
	return &record{declaration: declaration, entities: entities, root: root}, nil
}

// validateElementRecord validates one element record (materialization.rs:306-500).
func validateElementRecord(value core.Value, path protocol.ValuePath,
	analyzed *[]protocol.ValuePath) (*elementRecord, *MaterializationFailure) {
	*analyzed = append(*analyzed, path)
	namespace, local, failure := expectExpandedName(value, path)
	if failure != nil {
		return nil, failure
	}
	var namespaces []namespacePair
	if field, ok := optionalSequenceField(value, "namespaces"); ok {
		bindingsPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "namespaces"})
		for index, binding := range field {
			bindingPath := bindingsPath.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
			prefix, failure := optionalStringField(binding, "prefix", bindingPath)
			if failure != nil {
				return nil, failure
			}
			uri, failure := expectStringField(binding, "uri", bindingPath)
			if failure != nil {
				return nil, failure
			}
			namespaces = append(namespaces, namespacePair{prefix: prefix, uri: uri})
		}
	}
	var attributes []attributeRecord
	if field, ok := optionalSequenceField(value, "attributes"); ok {
		attributesPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "attributes"})
		for index, attribute := range field {
			attributePath := attributesPath.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
			attrNamespace, attrLocal, failure := expectExpandedName(attribute, attributePath)
			if failure != nil {
				return nil, failure
			}
			valueText, failure := expectStringField(attribute, "value", attributePath)
			if failure != nil {
				return nil, failure
			}
			attributes = append(attributes, attributeRecord{
				namespace: attrNamespace, local: attrLocal, value: valueText, path: attributePath,
			})
		}
	}
	var content []contentRecord
	if field, ok := optionalSequenceField(value, "content"); ok {
		contentPath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "content"})
		for index, item := range field {
			itemPath := contentPath.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(index)})
			if _, ok := objectEntry(item, "expanded-name"); ok {
				element, failure := validateElementRecord(item, itemPath, analyzed)
				if failure != nil {
					return nil, failure
				}
				content = append(content, contentRecord{kind: contentRecordElement, element: element, path: itemPath})
				continue
			}
			kind, failure := expectStringField(item, "kind", itemPath)
			if failure != nil {
				return nil, failure
			}
			switch kind {
			case "text":
				fragmentsPath := itemPath.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "fragments"})
				fragmentsValue, failure := expectObjectField(item, "fragments", fragmentsPath)
				if failure != nil {
					return nil, failure
				}
				sequence := asSequence(fragmentsValue)
				if sequence == nil {
					return nil, &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
						Path: fragmentsPath, ValueKind: kindOf(fragmentsValue)}
				}
				var fragments []fragmentRecord
				for fragmentIndex, fragment := range sequence {
					fragmentPath := fragmentsPath.Child(protocol.ValuePathSegment{Kind: "SequenceElement", Index: uint64(fragmentIndex)})
					fragmentKind, failure := expectStringField(fragment, "kind", fragmentPath)
					if failure != nil {
						return nil, failure
					}
					switch fragmentKind {
					case "literal":
						text, failure := expectStringField(fragment, "text", fragmentPath)
						if failure != nil {
							return nil, failure
						}
						fragments = append(fragments, fragmentRecord{kind: fragmentRecordLiteral, text: text})
					case "character-reference":
						resolved, failure := expectStringField(fragment, "resolved", fragmentPath)
						if failure != nil {
							return nil, failure
						}
						runes := []rune(resolved)
						if len(runes) != 1 {
							return nil, &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
								Path: fragmentPath, ValueKind: core.KindString}
						}
						fragments = append(fragments, fragmentRecord{
							kind: fragmentRecordCharacterReference, resolved: runes[0],
						})
					case "predefined-entity":
						name, failure := expectStringField(fragment, "name", fragmentPath)
						if failure != nil {
							return nil, failure
						}
						resolved, failure := expectStringField(fragment, "resolved", fragmentPath)
						if failure != nil {
							return nil, failure
						}
						fragments = append(fragments, fragmentRecord{
							kind: fragmentRecordPredefinedEntity, name: name, resolvedText: resolved,
						})
					case "general-entity":
						name, failure := expectStringField(fragment, "name", fragmentPath)
						if failure != nil {
							return nil, failure
						}
						resolved, failure := expectStringField(fragment, "resolved", fragmentPath)
						if failure != nil {
							return nil, failure
						}
						fragments = append(fragments, fragmentRecord{
							kind: fragmentRecordGeneralEntity, name: name, resolvedText: resolved,
						})
					default:
						return nil, &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
							Path: fragmentPath, ValueKind: kindOf(fragment)}
					}
				}
				content = append(content, contentRecord{
					kind: contentRecordText, fragments: fragments, path: itemPath,
				})
			case "cdata":
				text, failure := expectStringField(item, "text", itemPath)
				if failure != nil {
					return nil, failure
				}
				content = append(content, contentRecord{kind: contentRecordCdata, text: text, path: itemPath})
			case "comment":
				text, failure := expectStringField(item, "text", itemPath)
				if failure != nil {
					return nil, failure
				}
				content = append(content, contentRecord{kind: contentRecordComment, text: text, path: itemPath})
			case "processing-instruction":
				target, failure := expectStringField(item, "target", itemPath)
				if failure != nil {
					return nil, failure
				}
				piContent, failure := optionalStringField(item, "content", itemPath)
				if failure != nil {
					return nil, failure
				}
				content = append(content, contentRecord{
					kind: contentRecordProcessingInstruction, target: target, content: piContent, path: itemPath,
				})
			default:
				return nil, &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
					Path: itemPath, ValueKind: kindOf(item)}
			}
		}
	}
	var names []namespacePair
	for _, attribute := range attributes {
		pair := namespacePair{prefix: attribute.namespace, uri: attribute.local}
		for _, existing := range names {
			if existing.prefix == pair.prefix && existing.uri == pair.uri {
				return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest,
					Reason: "duplicate expanded attribute in input record"}
			}
		}
		names = append(names, pair)
	}
	return &elementRecord{
		namespace: namespace, local: local, namespaces: namespaces,
		attributes: attributes, content: content, path: path,
	}, nil
}

// materializationWriter is the deterministic output writer
// (materialization.rs:565-574).
type materializationWriter struct {
	limits     document.MaterializationLimits
	inputNodes int
	output     []byte
	prefixes   map[string]string
	nextPrefix int
	scope      []namespacePair
	items      []inputItem
}

// inputItemKind is the closed input location category (materialization.rs:528-541).
type inputItemKind uint8

const (
	inputItemDeclaration inputItemKind = iota
	inputItemEntity
	inputItemElement
	inputItemNamespaceBinding
	inputItemAttribute
	inputItemText
	inputItemFragment
	inputItemCdata
	inputItemComment
	inputItemProcessingInstruction
)

// inputItem is one input location recorded during generation, paired by
// order with the reparsed document during closure verification.
type inputItem struct {
	kind inputItemKind
	path protocol.ValuePath
}

func (p *materializationWriter) step() *MaterializationFailure {
	p.inputNodes++
	if p.inputNodes > p.limits.MaxInputNodes {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit, LimitName: "input-nodes"}
	}
	return nil
}

func (p *materializationWriter) push(bytes []byte) *MaterializationFailure {
	p.output = append(p.output, bytes...)
	if len(p.output) > p.limits.MaxOutputBytes {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit, LimitName: "output-bytes"}
	}
	return nil
}

// spellingPrefix is the spelling prefix for one expanded namespace using
// the current scope (materialization.rs:601-621).
func (p *materializationWriter) spellingPrefix(uri *string) *string {
	if uri == nil {
		empty := ""
		return &empty
	}
	if *uri == XMLNamespaceURI {
		prefix := "xml"
		return &prefix
	}
	for index := len(p.scope) - 1; index >= 0; index-- {
		binding := p.scope[index]
		if binding.prefix == nil && binding.uri == *uri {
			empty := ""
			return &empty
		}
	}
	for index := len(p.scope) - 1; index >= 0; index-- {
		binding := p.scope[index]
		if binding.prefix != nil && binding.uri == *uri {
			return binding.prefix
		}
	}
	return nil
}

// prefixFor is the deterministic generated-prefix assignment by
// first-encounter order (materialization.rs:503-526).
func (p *materializationWriter) prefixFor(namespace string) string {
	if namespace == XMLNamespaceURI {
		return "xml"
	}
	if prefix, ok := p.prefixes[namespace]; ok {
		return prefix
	}
	if p.prefixes == nil {
		p.prefixes = make(map[string]string)
	}
	p.nextPrefix++
	prefix := "ns" + itoa(p.nextPrefix)
	p.prefixes[namespace] = prefix
	return prefix
}

func (p *materializationWriter) pushEscapedText(text string) *MaterializationFailure {
	rest := text
	for {
		at := strings.IndexAny(rest, "&<")
		if at < 0 {
			break
		}
		if failure := p.push([]byte(rest[:at])); failure != nil {
			return failure
		}
		switch rest[at] {
		case '&':
			if failure := p.push([]byte("&amp;")); failure != nil {
				return failure
			}
		default:
			if failure := p.push([]byte("&lt;")); failure != nil {
				return failure
			}
		}
		rest = rest[at+1:]
	}
	return p.push([]byte(rest))
}

func (p *materializationWriter) pushEscapedAttribute(text string) *MaterializationFailure {
	rest := text
	for {
		at := strings.IndexAny(rest, "&<\"")
		if at < 0 {
			break
		}
		if failure := p.push([]byte(rest[:at])); failure != nil {
			return failure
		}
		switch rest[at] {
		case '&':
			if failure := p.push([]byte("&amp;")); failure != nil {
				return failure
			}
		case '<':
			if failure := p.push([]byte("&lt;")); failure != nil {
				return failure
			}
		default:
			if failure := p.push([]byte("&quot;")); failure != nil {
				return failure
			}
		}
		rest = rest[at+1:]
	}
	return p.push([]byte(rest))
}

// emitDocument writes the complete canonical document
// (materialization.rs:650-715).
func (p *materializationWriter) emitDocument(input *record,
	request document.MaterializationRequest) *MaterializationFailure {
	if failure := p.step(); failure != nil {
		return failure
	}
	if input.declaration != nil {
		p.items = append(p.items, inputItem{kind: inputItemDeclaration, path: input.declaration.path})
		if failure := p.push([]byte("<?xml version=\"")); failure != nil {
			return failure
		}
		if failure := p.pushEscapedAttribute(input.declaration.version); failure != nil {
			return failure
		}
		if failure := p.push([]byte("\"")); failure != nil {
			return failure
		}
		declaredEncoding := input.declaration.encoding
		if declaredEncoding == nil && (request.Encoding().Equal(document.Utf16LeEncoding()) ||
			request.Encoding().Equal(document.Utf16BeEncoding())) {
			encoding := "UTF-16"
			declaredEncoding = &encoding
		}
		if declaredEncoding != nil {
			if failure := p.push([]byte(" encoding=\"")); failure != nil {
				return failure
			}
			if failure := p.pushEscapedAttribute(*declaredEncoding); failure != nil {
				return failure
			}
			if failure := p.push([]byte("\"")); failure != nil {
				return failure
			}
		}
		if input.declaration.standalone != nil {
			if *input.declaration.standalone {
				if failure := p.push([]byte(" standalone=\"yes\"")); failure != nil {
					return failure
				}
			} else {
				if failure := p.push([]byte(" standalone=\"no\"")); failure != nil {
					return failure
				}
			}
		}
		if failure := p.push([]byte("?>")); failure != nil {
			return failure
		}
	}
	if len(input.entities) > 0 {
		if failure := p.push([]byte("<!DOCTYPE ")); failure != nil {
			return failure
		}
		prefix := p.spellingPrefix(input.root.namespace)
		var doctypeName string
		if prefix != nil && *prefix == "" {
			doctypeName = input.root.local
		} else if prefix != nil {
			doctypeName = *prefix + ":" + input.root.local
		} else {
			// An unbound root namespace cannot be named in the DOCTYPE
			// without a declaration; fail honestly.
			return &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
				Path: input.root.path, ValueKind: core.KindObject}
		}
		if failure := p.push([]byte(doctypeName)); failure != nil {
			return failure
		}
		if failure := p.push([]byte(" [")); failure != nil {
			return failure
		}
		for _, entity := range input.entities {
			p.items = append(p.items, inputItem{kind: inputItemEntity, path: entity.path})
			if failure := p.push([]byte("<!ENTITY ")); failure != nil {
				return failure
			}
			if failure := p.push([]byte(entity.name)); failure != nil {
				return failure
			}
			if failure := p.push([]byte(" \"")); failure != nil {
				return failure
			}
			if failure := p.pushEscapedAttribute(entity.replacement); failure != nil {
				return failure
			}
			if failure := p.push([]byte("\">")); failure != nil {
				return failure
			}
		}
		if failure := p.push([]byte("]>")); failure != nil {
			return failure
		}
	}
	if failure := p.emitElement(input.root, 0); failure != nil {
		return failure
	}
	return p.push(request.Newline().Bytes())
}

// emitElement writes one element record (materialization.rs:717-899).
func (p *materializationWriter) emitElement(element *elementRecord, depth int) *MaterializationFailure {
	if failure := p.step(); failure != nil {
		return failure
	}
	if depth > p.limits.MaxDepth {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit, LimitName: "input-depth"}
	}
	p.items = append(p.items, inputItem{kind: inputItemElement, path: element.path})
	scopeLen := len(p.scope)
	// The record's namespace declarations are reproduced verbatim in
	// order; the spelling of names follows the resulting scope.
	for _, binding := range element.namespaces {
		p.scope = append(p.scope, binding)
	}
	elementPrefix := p.spellingPrefix(element.namespace)
	if elementPrefix == nil {
		// Unbound URI in a hand-built record: declare a generated default
		// namespace on this element.
		uri := XMLNamespaceURI
		if element.namespace != nil {
			uri = *element.namespace
		}
		if uri == XMLNamespaceURI {
			prefix := "xml"
			elementPrefix = &prefix
		} else {
			if failure := p.push([]byte("<")); failure != nil {
				return failure
			}
			if failure := p.push([]byte(element.local)); failure != nil {
				return failure
			}
			if failure := p.push([]byte(" xmlns=\"")); failure != nil {
				return failure
			}
			if failure := p.pushEscapedAttribute(uri); failure != nil {
				return failure
			}
			if failure := p.push([]byte("\"")); failure != nil {
				return failure
			}
			p.scope = append(p.scope, namespacePair{uri: uri})
			p.items = append(p.items, inputItem{kind: inputItemNamespaceBinding, path: element.path})
			empty := ""
			elementPrefix = &empty
		}
	}
	if failure := p.push([]byte("<")); failure != nil {
		return failure
	}
	if *elementPrefix == "" {
		if failure := p.push([]byte(element.local)); failure != nil {
			return failure
		}
	} else {
		if failure := p.push([]byte(*elementPrefix + ":" + element.local)); failure != nil {
			return failure
		}
	}
	for _, binding := range element.namespaces {
		p.items = append(p.items, inputItem{kind: inputItemNamespaceBinding, path: element.path})
		if binding.prefix != nil {
			if failure := p.push([]byte(" xmlns:" + *binding.prefix + "=\"")); failure != nil {
				return failure
			}
		} else {
			if failure := p.push([]byte(" xmlns=\"")); failure != nil {
				return failure
			}
		}
		if failure := p.pushEscapedAttribute(binding.uri); failure != nil {
			return failure
		}
		if failure := p.push([]byte("\"")); failure != nil {
			return failure
		}
	}
	for _, attribute := range element.attributes {
		p.items = append(p.items, inputItem{kind: inputItemAttribute, path: attribute.path})
		attributePrefix := p.spellingPrefix(attribute.namespace)
		if attributePrefix == nil {
			// Unbound attribute namespace: declare a generated prefix on
			// this element.
			uri := XMLNamespaceURI
			if attribute.namespace != nil {
				uri = *attribute.namespace
			}
			generated := p.prefixFor(uri)
			if failure := p.push([]byte(" xmlns:" + generated + "=\"")); failure != nil {
				return failure
			}
			if failure := p.pushEscapedAttribute(uri); failure != nil {
				return failure
			}
			if failure := p.push([]byte("\"")); failure != nil {
				return failure
			}
			p.scope = append(p.scope, namespacePair{prefix: &generated, uri: uri})
			p.items = append(p.items, inputItem{kind: inputItemNamespaceBinding, path: element.path})
			attributePrefix = &generated
		}
		if failure := p.push([]byte(" ")); failure != nil {
			return failure
		}
		if *attributePrefix == "" {
			if failure := p.push([]byte(attribute.local)); failure != nil {
				return failure
			}
		} else {
			if failure := p.push([]byte(*attributePrefix + ":" + attribute.local)); failure != nil {
				return failure
			}
		}
		if failure := p.push([]byte("=\"")); failure != nil {
			return failure
		}
		if failure := p.pushEscapedAttribute(attribute.value); failure != nil {
			return failure
		}
		if failure := p.push([]byte("\"")); failure != nil {
			return failure
		}
	}
	if len(element.content) == 0 {
		if failure := p.push([]byte("/>")); failure != nil {
			return failure
		}
		p.scope = p.scope[:scopeLen]
		return nil
	}
	if failure := p.push([]byte(">")); failure != nil {
		return failure
	}
	for _, item := range element.content {
		switch item.kind {
		case contentRecordElement:
			if failure := p.emitElement(item.element, depth+1); failure != nil {
				return failure
			}
		case contentRecordText:
			p.items = append(p.items, inputItem{kind: inputItemText, path: item.path})
			for _, fragment := range item.fragments {
				p.items = append(p.items, inputItem{kind: inputItemFragment, path: item.path})
				switch fragment.kind {
				case fragmentRecordLiteral:
					if failure := p.pushEscapedText(fragment.text); failure != nil {
						return failure
					}
				case fragmentRecordCharacterReference:
					if failure := p.push([]byte("&#" + itoa(int(fragment.resolved)) + ";")); failure != nil {
						return failure
					}
				case fragmentRecordPredefinedEntity, fragmentRecordGeneralEntity:
					if failure := p.push([]byte("&" + fragment.name + ";")); failure != nil {
						return failure
					}
				}
			}
		case contentRecordCdata:
			p.items = append(p.items, inputItem{kind: inputItemCdata, path: item.path})
			if strings.Contains(item.text, "]]>") {
				return &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
					Path: item.path, ValueKind: core.KindString}
			}
			if failure := p.push([]byte("<![CDATA[" + item.text + "]]>")); failure != nil {
				return failure
			}
		case contentRecordComment:
			p.items = append(p.items, inputItem{kind: inputItemComment, path: item.path})
			if strings.Contains(item.text, "--") || strings.HasSuffix(item.text, "-") {
				return &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
					Path: item.path, ValueKind: core.KindString}
			}
			if failure := p.push([]byte("<!--" + item.text + "-->")); failure != nil {
				return failure
			}
		case contentRecordProcessingInstruction:
			p.items = append(p.items, inputItem{kind: inputItemProcessingInstruction, path: item.path})
			if strings.EqualFold(item.target, "xml") ||
				(item.content != nil && strings.Contains(*item.content, "?>")) {
				return &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
					Path: item.path, ValueKind: core.KindString}
			}
			if failure := p.push([]byte("<?" + item.target)); failure != nil {
				return failure
			}
			if item.content != nil {
				if failure := p.push([]byte(" " + *item.content)); failure != nil {
					return failure
				}
			}
			if failure := p.push([]byte("?>")); failure != nil {
				return failure
			}
		}
	}
	if failure := p.push([]byte("</")); failure != nil {
		return failure
	}
	if *elementPrefix == "" {
		if failure := p.push([]byte(element.local)); failure != nil {
			return failure
		}
	} else {
		if failure := p.push([]byte(*elementPrefix + ":" + element.local)); failure != nil {
			return failure
		}
	}
	if failure := p.push([]byte(">")); failure != nil {
		return failure
	}
	p.scope = p.scope[:scopeLen]
	return nil
}

// outputItem is one matched output origin in the reparsed document.
type outputItem struct {
	node     document.NodeRef
	span     document.Span
	relation MaterializationRelation
}

// verifyClosure walks the input record and the reparsed document in
// lockstep, compares the promised semantics, and pairs every recorded
// input location with its exact output origin (materialization.rs:912-1014).
func verifyClosure(input *record, target *Document, items []inputItem,
	limits document.MaterializationLimits) (MaterializationProvenanceMap, *MaterializationFailure) {
	var outputs []outputItem
	root := target.Root()
	if root == nil {
		return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	// Declaration closure.
	switch {
	case input.declaration == nil && target.declaration == nil:
	case input.declaration != nil && target.declaration != nil:
		if target.declaration.Version != input.declaration.version ||
			standaloneValue(target.declaration) != input.declaration.standalone {
			return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
	default:
		return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	// Entity closure.
	if doctype := target.doctype; doctype != nil {
		if len(doctype.Entities) != len(input.entities) {
			return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		for index, entity := range doctype.Entities {
			if entity.Name != input.entities[index].name ||
				entity.Replacement != input.entities[index].replacement {
				return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
		}
	} else if len(input.entities) > 0 {
		return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	// Declaration and entity outputs precede the tree walk, matching the
	// generation order of their input items.
	if input.declaration != nil {
		declared := target.declaration
		if declared == nil {
			return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		outputs = append(outputs, outputItem{
			node:     target.authority.NodeRef(0, document.RoleXmlDeclaration),
			span:     declared.Span,
			relation: MaterializationRelationDirect,
		})
	}
	if doctype := target.doctype; doctype != nil {
		for _, entity := range doctype.Entities {
			outputs = append(outputs, outputItem{
				node:     target.authority.NodeRef(0, document.RoleXmlDoctype),
				span:     entity.Span,
				relation: MaterializationRelationDirect,
			})
		}
	}
	context := &closureContext{document: target, outputs: &outputs, limits: limits}
	if failure := context.element(input.root, root); failure != nil {
		return MaterializationProvenanceMap{}, failure
	}
	// Pair input items with outputs by traversal order; adjacent items with
	// the same input location share one provenance entry.
	if len(outputs) != len(items) {
		return MaterializationProvenanceMap{}, &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	var entries []MaterializationProvenanceEntry
	for index, item := range items {
		location := inputLocation(item)
		origin := MaterializedOrigin{
			Snapshot: target.SnapshotIdentity(),
			Node:     outputs[index].node,
			Span:     outputs[index].span,
			Relation: outputs[index].relation,
		}
		if len(entries) > 0 && entries[len(entries)-1].Input.Equal(location) {
			entries[len(entries)-1].Outputs = append(entries[len(entries)-1].Outputs, origin)
			continue
		}
		entries = append(entries, MaterializationProvenanceEntry{
			Input: location, Outputs: []MaterializedOrigin{origin},
		})
	}
	return MaterializationProvenanceMap{entries: entries}, nil
}

// inputLocation maps one recorded input item to its portable location.
func inputLocation(item inputItem) MaterializationInputLocation {
	if item.kind == inputItemNamespaceBinding {
		association := protocol.NewAssociationLocation(item.path, 0, protocol.AssociationRoleObjectEntry)
		return MaterializationInputLocation{IsAssociation: true, Association: association}
	}
	return MaterializationInputLocation{Path: item.path}
}

// closureContext walks the reparsed document against the input record.
type closureContext struct {
	document *Document
	outputs  *[]outputItem
	limits   document.MaterializationLimits
}

func (c *closureContext) push(node document.NodeRef, span document.Span,
	relation MaterializationRelation) *MaterializationFailure {
	if len(*c.outputs) >= c.limits.MaxProvenanceEntries {
		return &MaterializationFailure{Kind: MaterializationFailureResourceLimit, LimitName: "provenance-entries"}
	}
	*c.outputs = append(*c.outputs, outputItem{node: node, span: span, relation: relation})
	return nil
}

// element walks one input element against one reparsed element
// (materialization.rs:1040-1209).
func (c *closureContext) element(input *elementRecord, element *XmlElement) *MaterializationFailure {
	if failure := c.push(element.NodeRef(), element.Span(), MaterializationRelationDirect); failure != nil {
		return failure
	}
	expanded := element.Expanded()
	if expanded == nil {
		return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	if !namespacesMatch(input.namespace, expanded.Namespace) || expanded.Local != input.local {
		return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	for _, binding := range element.NamespaceBindings() {
		if failure := c.push(c.document.authority.NodeRef(binding.Ordinal, document.RoleXmlNamespaceBinding),
			binding.Span, MaterializationRelationGenerated); failure != nil {
			return failure
		}
	}
	attributes := element.Attributes()
	if len(attributes) != len(input.attributes) {
		return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	for index, attribute := range attributes {
		if failure := c.push(c.document.authority.NodeRef(attribute.Ordinal, document.RoleXmlAttribute),
			attribute.Span, MaterializationRelationDirect); failure != nil {
			return failure
		}
		if attribute.Expanded == nil {
			return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
		if !namespacesMatch(input.attributes[index].namespace, attribute.Expanded.Namespace) ||
			attribute.Expanded.Local != input.attributes[index].local ||
			attribute.NormalizedValue != input.attributes[index].value {
			return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
	}
	children := element.Children()
	if len(children) != len(input.content) {
		return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
	}
	for index, child := range children {
		inputContent := &input.content[index]
		switch {
		case inputContent.kind == contentRecordElement:
			childElement := child.Element()
			if childElement == nil {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
			if failure := c.element(inputContent.element, childElement); failure != nil {
				return failure
			}
		case inputContent.kind == contentRecordText:
			text := child.Text()
			if text == nil {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
			if failure := c.push(c.document.authority.NodeRef(text.Ordinal, document.RoleXmlText),
				text.Span, MaterializationRelationDirect); failure != nil {
				return failure
			}
			var semantic strings.Builder
			for _, fragment := range inputContent.fragments {
				switch fragment.kind {
				case fragmentRecordLiteral:
					pushNormalized(&semantic, fragment.text)
				case fragmentRecordCharacterReference:
					semantic.WriteRune(fragment.resolved)
				case fragmentRecordPredefinedEntity, fragmentRecordGeneralEntity:
					pushNormalized(&semantic, fragment.resolvedText)
				}
				fragmentSpan := text.Span
				if len(text.Fragments) > 0 {
					fragmentSpan = text.Fragments[0].Span
				}
				if failure := c.push(c.document.authority.NodeRef(text.Ordinal,
					document.RoleXmlEntityReference), fragmentSpan, MaterializationRelationDirect); failure != nil {
					return failure
				}
			}
			if TextSemantic(text) != semantic.String() {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
		case inputContent.kind == contentRecordCdata:
			cdata := child.Cdata()
			if cdata == nil {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
			if failure := c.push(c.document.authority.NodeRef(cdata.Ordinal, document.RoleXmlCdata),
				cdata.Span, MaterializationRelationDirect); failure != nil {
				return failure
			}
			if cdata.Text != inputContent.text {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
		case inputContent.kind == contentRecordComment:
			comment := child.Comment()
			if comment == nil {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
			if failure := c.push(c.document.authority.NodeRef(comment.Ordinal, document.RoleXmlComment),
				comment.Span, MaterializationRelationDirect); failure != nil {
				return failure
			}
			if comment.Text != inputContent.text {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
		case inputContent.kind == contentRecordProcessingInstruction:
			pi := child.ProcessingInstruction()
			if pi == nil {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
			if failure := c.push(c.document.authority.NodeRef(pi.Ordinal,
				document.RoleXmlProcessingInstruction), pi.Span, MaterializationRelationDirect); failure != nil {
				return failure
			}
			var piContent *string
			if pi.Content != nil {
				text := pi.Content.Text
				piContent = &text
			}
			if pi.Target != inputContent.target || !stringPtrsEqual(piContent, inputContent.content) {
				return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
			}
		default:
			return &MaterializationFailure{Kind: MaterializationFailureFormationFailed}
		}
	}
	return nil
}

// standaloneValue extracts the declared standalone boolean.
func standaloneValue(declared *XmlDeclarationData) *bool {
	if declared.Standalone == nil {
		return nil
	}
	value := declared.Standalone.Value
	return &value
}

// namespacesMatch compares two namespace URI facts.
func namespacesMatch(left, right *string) bool {
	if left == nil || right == nil {
		return left == right
	}
	return *left == *right
}

// expectExpandedName reads one expanded-name record.
func expectExpandedName(value core.Value, path protocol.ValuePath) (*string, string, *MaterializationFailure) {
	name, failure := expectObjectField(value, "expanded-name", path)
	if failure != nil {
		return nil, "", failure
	}
	namePath := path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: "expanded-name"})
	namespace, failure := optionalStringField(name, "namespace", namePath)
	if failure != nil {
		return nil, "", failure
	}
	local, failure := expectStringField(name, "local", namePath)
	if failure != nil {
		return nil, "", failure
	}
	return namespace, local, nil
}

// expectObjectField reads one required object field.
func expectObjectField(value core.Value, name string, path protocol.ValuePath) (core.Value, *MaterializationFailure) {
	object := asObject(value)
	if object == nil {
		return nil, &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
			Path: path, ValueKind: kindOf(value)}
	}
	field, ok := objectEntry(value, name)
	if !ok {
		return nil, &MaterializationFailure{Kind: MaterializationFailureInvalidRequest,
			Reason: "missing record field"}
	}
	return field, nil
}

// expectStringField reads one required string field.
func expectStringField(value core.Value, name string, path protocol.ValuePath) (string, *MaterializationFailure) {
	field, failure := expectObjectField(value, name, path)
	if failure != nil {
		return "", failure
	}
	text, ok := field.(core.String)
	if !ok {
		return "", &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
			Path:      path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: name}),
			ValueKind: kindOf(field)}
	}
	return string(text), nil
}

// optionalObjectField reads one optional object field.
func optionalObjectField(value core.Value, name string) (core.Value, bool) {
	object := asObject(value)
	if object == nil {
		return nil, false
	}
	field, ok := objectEntry(value, name)
	if !ok {
		return nil, false
	}
	return field, true
}

// optionalStringField reads one optional string field; Null is absent.
func optionalStringField(value core.Value, name string, path protocol.ValuePath) (*string, *MaterializationFailure) {
	object := asObject(value)
	if object == nil {
		return nil, nil
	}
	field, ok := objectEntry(value, name)
	if !ok {
		return nil, nil
	}
	if _, isNull := field.(core.Null); isNull {
		return nil, nil
	}
	text, ok := field.(core.String)
	if !ok {
		return nil, &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
			Path:      path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: name}),
			ValueKind: kindOf(field)}
	}
	valueText := string(text)
	return &valueText, nil
}

// optionalBooleanField reads one optional boolean field; Null is absent.
func optionalBooleanField(value core.Value, name string, path protocol.ValuePath) (*bool, *MaterializationFailure) {
	object := asObject(value)
	if object == nil {
		return nil, nil
	}
	field, ok := objectEntry(value, name)
	if !ok {
		return nil, nil
	}
	if _, isNull := field.(core.Null); isNull {
		return nil, nil
	}
	boolean, ok := field.(core.Boolean)
	if !ok {
		return nil, &MaterializationFailure{Kind: MaterializationFailureUnrepresentable,
			Path:      path.Child(protocol.ValuePathSegment{Kind: "ObjectValue", Key: name}),
			ValueKind: kindOf(field)}
	}
	valueBoolean := bool(boolean)
	return &valueBoolean, nil
}

// optionalSequenceField reads one optional sequence field.
func optionalSequenceField(value core.Value, name string) ([]core.Value, bool) {
	object := asObject(value)
	if object == nil {
		return nil, false
	}
	field, ok := objectEntry(value, name)
	if !ok {
		return nil, false
	}
	return asSequence(field), asSequence(field) != nil
}

// asObject returns the object value, when present.
func asObject(value core.Value) *core.Object {
	object, _ := value.(*core.Object)
	return object
}

// asSequence returns the sequence items, when present.
func asSequence(value core.Value) []core.Value {
	array, ok := value.(*core.Array)
	if !ok {
		return nil
	}
	return array.Items()
}

// objectEntry reads one named entry of an object value.
func objectEntry(value core.Value, name string) (core.Value, bool) {
	object, ok := value.(*core.Object)
	if !ok {
		return nil, false
	}
	return object.Get(name)
}

// kindOf reports the portable kind of one value.
func kindOf(value core.Value) core.Kind {
	return value.Kind()
}

// Equal reports whether two input locations are identical.
func (l MaterializationInputLocation) Equal(other MaterializationInputLocation) bool {
	if l.IsAssociation != other.IsAssociation {
		return false
	}
	if l.IsAssociation {
		return l.Association.Equal(other.Association)
	}
	return l.Path.Equal(other.Path)
}

// stringPtrsEqual compares two optional strings by value.
func stringPtrsEqual(left, right *string) bool {
	if left == nil || right == nil {
		return left == right
	}
	return *left == *right
}

// itoa formats one integer as decimal.
func itoa(value int) string {
	if value == 0 {
		return "0"
	}
	var buffer [24]byte
	position := len(buffer)
	for value > 0 {
		position--
		buffer[position] = byte('0' + value%10)
		value /= 10
	}
	return string(buffer[position:])
}
